// Code generated by protoc-gen-go.
// source: dstore/values.proto
// DO NOT EDIT!

/*
Package values is a generated protocol buffer package.

It is generated from these files:
	dstore/values.proto

It has these top-level messages:
	IntegerValue
	StringValue
	BytesValue
	DoubleValue
	BooleanValue
	DecimalValue
	TimestampValue
	LongValue
	Value
*/
package values

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IntegerValue struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *IntegerValue) Reset()                    { *m = IntegerValue{} }
func (m *IntegerValue) String() string            { return proto.CompactTextString(m) }
func (*IntegerValue) ProtoMessage()               {}
func (*IntegerValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StringValue struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *StringValue) Reset()                    { *m = StringValue{} }
func (m *StringValue) String() string            { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()               {}
func (*StringValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BytesValue struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *BytesValue) Reset()                    { *m = BytesValue{} }
func (m *BytesValue) String() string            { return proto.CompactTextString(m) }
func (*BytesValue) ProtoMessage()               {}
func (*BytesValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DoubleValue struct {
	Value float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
}

func (m *DoubleValue) Reset()                    { *m = DoubleValue{} }
func (m *DoubleValue) String() string            { return proto.CompactTextString(m) }
func (*DoubleValue) ProtoMessage()               {}
func (*DoubleValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type BooleanValue struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *BooleanValue) Reset()                    { *m = BooleanValue{} }
func (m *BooleanValue) String() string            { return proto.CompactTextString(m) }
func (*BooleanValue) ProtoMessage()               {}
func (*BooleanValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DecimalValue struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *DecimalValue) Reset()                    { *m = DecimalValue{} }
func (m *DecimalValue) String() string            { return proto.CompactTextString(m) }
func (*DecimalValue) ProtoMessage()               {}
func (*DecimalValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type TimestampValue struct {
	Value *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *TimestampValue) Reset()                    { *m = TimestampValue{} }
func (m *TimestampValue) String() string            { return proto.CompactTextString(m) }
func (*TimestampValue) ProtoMessage()               {}
func (*TimestampValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TimestampValue) GetValue() *google_protobuf.Timestamp {
	if m != nil {
		return m.Value
	}
	return nil
}

type LongValue struct {
	Value int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *LongValue) Reset()                    { *m = LongValue{} }
func (m *LongValue) String() string            { return proto.CompactTextString(m) }
func (*LongValue) ProtoMessage()               {}
func (*LongValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_IntegerValue
	//	*Value_StringValue
	//	*Value_ByteValue
	//	*Value_DoubleValue
	//	*Value_BooleanValue
	//	*Value_DecimalValue
	//	*Value_TimestampValue
	//	*Value_LongValue
	Value isValue_Value `protobuf_oneof:"value"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isValue_Value interface {
	isValue_Value()
}

type Value_IntegerValue struct {
	IntegerValue *IntegerValue `protobuf:"bytes,10,opt,name=integer_value,json=integerValue,oneof"`
}
type Value_StringValue struct {
	StringValue *StringValue `protobuf:"bytes,11,opt,name=string_value,json=stringValue,oneof"`
}
type Value_ByteValue struct {
	ByteValue *BytesValue `protobuf:"bytes,12,opt,name=byte_value,json=byteValue,oneof"`
}
type Value_DoubleValue struct {
	DoubleValue *DoubleValue `protobuf:"bytes,13,opt,name=double_value,json=doubleValue,oneof"`
}
type Value_BooleanValue struct {
	BooleanValue *BooleanValue `protobuf:"bytes,14,opt,name=boolean_value,json=booleanValue,oneof"`
}
type Value_DecimalValue struct {
	DecimalValue *DecimalValue `protobuf:"bytes,15,opt,name=decimal_value,json=decimalValue,oneof"`
}
type Value_TimestampValue struct {
	TimestampValue *TimestampValue `protobuf:"bytes,16,opt,name=timestamp_value,json=timestampValue,oneof"`
}
type Value_LongValue struct {
	LongValue *LongValue `protobuf:"bytes,17,opt,name=long_value,json=longValue,oneof"`
}

func (*Value_IntegerValue) isValue_Value()   {}
func (*Value_StringValue) isValue_Value()    {}
func (*Value_ByteValue) isValue_Value()      {}
func (*Value_DoubleValue) isValue_Value()    {}
func (*Value_BooleanValue) isValue_Value()   {}
func (*Value_DecimalValue) isValue_Value()   {}
func (*Value_TimestampValue) isValue_Value() {}
func (*Value_LongValue) isValue_Value()      {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetIntegerValue() *IntegerValue {
	if x, ok := m.GetValue().(*Value_IntegerValue); ok {
		return x.IntegerValue
	}
	return nil
}

func (m *Value) GetStringValue() *StringValue {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return nil
}

func (m *Value) GetByteValue() *BytesValue {
	if x, ok := m.GetValue().(*Value_ByteValue); ok {
		return x.ByteValue
	}
	return nil
}

func (m *Value) GetDoubleValue() *DoubleValue {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return nil
}

func (m *Value) GetBooleanValue() *BooleanValue {
	if x, ok := m.GetValue().(*Value_BooleanValue); ok {
		return x.BooleanValue
	}
	return nil
}

func (m *Value) GetDecimalValue() *DecimalValue {
	if x, ok := m.GetValue().(*Value_DecimalValue); ok {
		return x.DecimalValue
	}
	return nil
}

func (m *Value) GetTimestampValue() *TimestampValue {
	if x, ok := m.GetValue().(*Value_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *Value) GetLongValue() *LongValue {
	if x, ok := m.GetValue().(*Value_LongValue); ok {
		return x.LongValue
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_IntegerValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_ByteValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BooleanValue)(nil),
		(*Value_DecimalValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_LongValue)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_IntegerValue:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.IntegerValue); err != nil {
			return err
		}
	case *Value_StringValue:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StringValue); err != nil {
			return err
		}
	case *Value_ByteValue:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ByteValue); err != nil {
			return err
		}
	case *Value_DoubleValue:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DoubleValue); err != nil {
			return err
		}
	case *Value_BooleanValue:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BooleanValue); err != nil {
			return err
		}
	case *Value_DecimalValue:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DecimalValue); err != nil {
			return err
		}
	case *Value_TimestampValue:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TimestampValue); err != nil {
			return err
		}
	case *Value_LongValue:
		b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LongValue); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 10: // value.integer_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IntegerValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_IntegerValue{msg}
		return true, err
	case 11: // value.string_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StringValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_StringValue{msg}
		return true, err
	case 12: // value.byte_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BytesValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_ByteValue{msg}
		return true, err
	case 13: // value.double_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DoubleValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_DoubleValue{msg}
		return true, err
	case 14: // value.boolean_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BooleanValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_BooleanValue{msg}
		return true, err
	case 15: // value.decimal_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecimalValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_DecimalValue{msg}
		return true, err
	case 16: // value.timestamp_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TimestampValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_TimestampValue{msg}
		return true, err
	case 17: // value.long_value
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LongValue)
		err := b.DecodeMessage(msg)
		m.Value = &Value_LongValue{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_IntegerValue:
		s := proto.Size(x.IntegerValue)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_StringValue:
		s := proto.Size(x.StringValue)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_ByteValue:
		s := proto.Size(x.ByteValue)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_DoubleValue:
		s := proto.Size(x.DoubleValue)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_BooleanValue:
		s := proto.Size(x.BooleanValue)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_DecimalValue:
		s := proto.Size(x.DecimalValue)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_TimestampValue:
		s := proto.Size(x.TimestampValue)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_LongValue:
		s := proto.Size(x.LongValue)
		n += proto.SizeVarint(17<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*IntegerValue)(nil), "dstore.values.integerValue")
	proto.RegisterType((*StringValue)(nil), "dstore.values.stringValue")
	proto.RegisterType((*BytesValue)(nil), "dstore.values.bytesValue")
	proto.RegisterType((*DoubleValue)(nil), "dstore.values.doubleValue")
	proto.RegisterType((*BooleanValue)(nil), "dstore.values.booleanValue")
	proto.RegisterType((*DecimalValue)(nil), "dstore.values.decimalValue")
	proto.RegisterType((*TimestampValue)(nil), "dstore.values.timestampValue")
	proto.RegisterType((*LongValue)(nil), "dstore.values.longValue")
	proto.RegisterType((*Value)(nil), "dstore.values.Value")
}

func init() { proto.RegisterFile("dstore/values.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x93, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xa9, 0xa0, 0x40, 0xae, 0x69, 0x0b, 0x05, 0xa1, 0x52, 0x84, 0x80, 0x96, 0x81, 0xc9,
	0x45, 0x30, 0xc1, 0x82, 0x94, 0xa9, 0x73, 0x85, 0x18, 0x58, 0x50, 0x42, 0x4c, 0x14, 0x91, 0xd6,
	0x55, 0xe2, 0x20, 0xf1, 0x69, 0xf8, 0xaa, 0xf8, 0xcf, 0x39, 0xd8, 0x91, 0xc5, 0xe8, 0xe4, 0xdd,
	0xef, 0x9c, 0xf7, 0x5e, 0xe0, 0x28, 0xad, 0x38, 0x2b, 0xe9, 0xfc, 0x2b, 0x2e, 0x6a, 0x5a, 0x91,
	0x4d, 0xc9, 0x38, 0x1b, 0xf5, 0xf5, 0x43, 0xa2, 0x1f, 0x4e, 0x2e, 0x32, 0xc6, 0xb2, 0x82, 0xce,
	0xd5, 0xcb, 0xa4, 0xfe, 0x98, 0xf3, 0x7c, 0x45, 0x2b, 0x1e, 0xaf, 0x36, 0x5a, 0x3f, 0xbd, 0x86,
	0x30, 0x5f, 0x73, 0x9a, 0xd1, 0xf2, 0x45, 0x4e, 0x8c, 0x8e, 0xa1, 0xab, 0x46, 0xc7, 0x9d, 0xcb,
	0xce, 0x4d, 0x77, 0xa9, 0x0f, 0xd3, 0x19, 0xf4, 0x2a, 0x5e, 0xe6, 0xeb, 0xcc, 0x23, 0x0a, 0x8c,
	0x68, 0x0a, 0x90, 0x7c, 0x73, 0x5a, 0x79, 0x34, 0xa1, 0x05, 0x4a, 0x59, 0x9d, 0x14, 0xd4, 0x23,
	0xea, 0x18, 0x91, 0xb8, 0x53, 0xc2, 0x58, 0x41, 0xe3, 0xb5, 0x47, 0xb5, 0x6f, 0xa9, 0x52, 0xfa,
	0x9e, 0xaf, 0xe2, 0xe2, 0xbf, 0x4b, 0x45, 0x30, 0x68, 0x3e, 0x59, 0xeb, 0x6e, 0x6d, 0x5d, 0xef,
	0x6e, 0x42, 0xb4, 0x45, 0xc4, 0x58, 0x44, 0x9e, 0x8d, 0xde, 0x30, 0xae, 0x20, 0x28, 0x98, 0xf7,
	0xdb, 0xb7, 0x8d, 0xe4, 0x67, 0x07, 0xba, 0xfa, 0x7d, 0x04, 0x7d, 0x34, 0xf4, 0x4d, 0xeb, 0x40,
	0xad, 0x39, 0x23, 0x4e, 0x30, 0xc4, 0x36, 0x7d, 0xb1, 0xb5, 0x74, 0x43, 0x78, 0x82, 0x50, 0xdb,
	0x8d, 0x88, 0x1e, 0xde, 0xd4, 0x45, 0x58, 0x89, 0x08, 0x82, 0x13, 0xd0, 0xa3, 0x8e, 0x02, 0xc7,
	0x43, 0x35, 0x7e, 0xda, 0x1a, 0xff, 0xcb, 0x4a, 0x4c, 0x07, 0xf2, 0xd4, 0x2c, 0xd7, 0x11, 0xe1,
	0x74, 0xdf, 0xbb, 0xdc, 0x4a, 0x51, 0x2e, 0xb7, 0x43, 0x15, 0x0e, 0x60, 0x7c, 0x48, 0x18, 0x78,
	0x1d, 0xb0, 0x23, 0x96, 0x0e, 0x38, 0x91, 0x0b, 0x06, 0x86, 0x8b, 0x8c, 0xa1, 0x97, 0x61, 0x17,
	0x40, 0x32, 0x9c, 0x42, 0x2c, 0x60, 0xd8, 0x44, 0x8f, 0x94, 0x03, 0x45, 0x39, 0x6f, 0x51, 0xdc,
	0x82, 0x08, 0x4e, 0xbb, 0x32, 0x0f, 0x00, 0xb2, 0x00, 0x08, 0x39, 0x54, 0x90, 0x71, 0x0b, 0xd2,
	0x34, 0x44, 0xba, 0xd9, 0x1c, 0xa2, 0x3d, 0xac, 0x4b, 0x34, 0x83, 0x20, 0x67, 0x38, 0xf3, 0x7a,
	0x92, 0xb1, 0x2a, 0xfd, 0x34, 0x84, 0xd4, 0xfc, 0xc3, 0xc9, 0xae, 0x2a, 0xe1, 0xfd, 0x6f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe7, 0xec, 0x60, 0x4d, 0xdb, 0x03, 0x00, 0x00,
}
