// Code generated by protoc-gen-go.
// source: dstore/engine/procedures/om_GetOrders_Pu.proto
// DO NOT EDIT!

/*
Package om_GetOrders_Pu is a generated protocol buffer package.

It is generated from these files:
	dstore/engine/procedures/om_GetOrders_Pu.proto

It has these top-level messages:
	Parameters
	Response
*/
package om_GetOrders_Pu

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_values "dstore/values"
import dstore_engine_error "dstore/engine/error"
import dstore_engine_message "dstore/engine/message"
import dstore_engine_metainformation "dstore/engine/metainformation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameters struct {
	GetACertainOrder                *dstore_values.BooleanValue   `protobuf:"bytes,1,opt,name=get_a_certain_order,json=getACertainOrder" json:"get_a_certain_order,omitempty"`
	GetACertainOrderNull            bool                          `protobuf:"varint,1001,opt,name=get_a_certain_order_null,json=getACertainOrderNull" json:"get_a_certain_order_null,omitempty"`
	PersonIdentificationValues      *dstore_values.StringValue    `protobuf:"bytes,2,opt,name=person_identification_values,json=personIdentificationValues" json:"person_identification_values,omitempty"`
	PersonIdentificationValuesNull  bool                          `protobuf:"varint,1002,opt,name=person_identification_values_null,json=personIdentificationValuesNull" json:"person_identification_values_null,omitempty"`
	PersonTypeId                    *dstore_values.IntegerValue   `protobuf:"bytes,3,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	PersonTypeIdNull                bool                          `protobuf:"varint,1003,opt,name=person_type_id_null,json=personTypeIdNull" json:"person_type_id_null,omitempty"`
	DateAndTimeFormat               *dstore_values.IntegerValue   `protobuf:"bytes,4,opt,name=date_and_time_format,json=dateAndTimeFormat" json:"date_and_time_format,omitempty"`
	DateAndTimeFormatNull           bool                          `protobuf:"varint,1004,opt,name=date_and_time_format_null,json=dateAndTimeFormatNull" json:"date_and_time_format_null,omitempty"`
	IncludeTime                     *dstore_values.BooleanValue   `protobuf:"bytes,5,opt,name=include_time,json=includeTime" json:"include_time,omitempty"`
	IncludeTimeNull                 bool                          `protobuf:"varint,1005,opt,name=include_time_null,json=includeTimeNull" json:"include_time_null,omitempty"`
	FromDate                        *dstore_values.TimestampValue `protobuf:"bytes,6,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	FromDateNull                    bool                          `protobuf:"varint,1006,opt,name=from_date_null,json=fromDateNull" json:"from_date_null,omitempty"`
	ToDate                          *dstore_values.TimestampValue `protobuf:"bytes,7,opt,name=to_date,json=toDate" json:"to_date,omitempty"`
	ToDateNull                      bool                          `protobuf:"varint,1007,opt,name=to_date_null,json=toDateNull" json:"to_date_null,omitempty"`
	OrderStateList                  *dstore_values.StringValue    `protobuf:"bytes,8,opt,name=order_state_list,json=orderStateList" json:"order_state_list,omitempty"`
	OrderStateListNull              bool                          `protobuf:"varint,1008,opt,name=order_state_list_null,json=orderStateListNull" json:"order_state_list_null,omitempty"`
	SkipOHavingDifferentOStates     *dstore_values.BooleanValue   `protobuf:"bytes,9,opt,name=skip_o_having_different_o_states,json=skipOHavingDifferentOStates" json:"skip_o_having_different_o_states,omitempty"`
	SkipOHavingDifferentOStatesNull bool                          `protobuf:"varint,1009,opt,name=skip_o_having_different_o_states_null,json=skipOHavingDifferentOStatesNull" json:"skip_o_having_different_o_states_null,omitempty"`
	OrderId                         *dstore_values.IntegerValue   `protobuf:"bytes,10,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	OrderIdNull                     bool                          `protobuf:"varint,1010,opt,name=order_id_null,json=orderIdNull" json:"order_id_null,omitempty"`
	Rowcount                        *dstore_values.IntegerValue   `protobuf:"bytes,11,opt,name=rowcount" json:"rowcount,omitempty"`
	RowcountNull                    bool                          `protobuf:"varint,1011,opt,name=rowcount_null,json=rowcountNull" json:"rowcount_null,omitempty"`
	CaseSensitive                   *dstore_values.BooleanValue   `protobuf:"bytes,12,opt,name=case_sensitive,json=caseSensitive" json:"case_sensitive,omitempty"`
	CaseSensitiveNull               bool                          `protobuf:"varint,1012,opt,name=case_sensitive_null,json=caseSensitiveNull" json:"case_sensitive_null,omitempty"`
	IncludeItemNo                   *dstore_values.BooleanValue   `protobuf:"bytes,13,opt,name=include_item_no,json=includeItemNo" json:"include_item_no,omitempty"`
	IncludeItemNoNull               bool                          `protobuf:"varint,1013,opt,name=include_item_no_null,json=includeItemNoNull" json:"include_item_no_null,omitempty"`
	OrderDesc                       *dstore_values.BooleanValue   `protobuf:"bytes,14,opt,name=order_desc,json=orderDesc" json:"order_desc,omitempty"`
	OrderDescNull                   bool                          `protobuf:"varint,1014,opt,name=order_desc_null,json=orderDescNull" json:"order_desc_null,omitempty"`
	InformationTypeId               *dstore_values.IntegerValue   `protobuf:"bytes,15,opt,name=information_type_id,json=informationTypeId" json:"information_type_id,omitempty"`
	InformationTypeIdNull           bool                          `protobuf:"varint,1015,opt,name=information_type_id_null,json=informationTypeIdNull" json:"information_type_id_null,omitempty"`
	Information                     *dstore_values.StringValue    `protobuf:"bytes,16,opt,name=information" json:"information,omitempty"`
	InformationNull                 bool                          `protobuf:"varint,1016,opt,name=information_null,json=informationNull" json:"information_null,omitempty"`
	NodeCharacteristicId            *dstore_values.IntegerValue   `protobuf:"bytes,17,opt,name=node_characteristic_id,json=nodeCharacteristicId" json:"node_characteristic_id,omitempty"`
	NodeCharacteristicIdNull        bool                          `protobuf:"varint,1017,opt,name=node_characteristic_id_null,json=nodeCharacteristicIdNull" json:"node_characteristic_id_null,omitempty"`
	LanguageId                      *dstore_values.IntegerValue   `protobuf:"bytes,18,opt,name=language_id,json=languageId" json:"language_id,omitempty"`
	LanguageIdNull                  bool                          `protobuf:"varint,1018,opt,name=language_id_null,json=languageIdNull" json:"language_id_null,omitempty"`
	PurchaseOrder                   *dstore_values.BooleanValue   `protobuf:"bytes,19,opt,name=purchase_order,json=purchaseOrder" json:"purchase_order,omitempty"`
	PurchaseOrderNull               bool                          `protobuf:"varint,1019,opt,name=purchase_order_null,json=purchaseOrderNull" json:"purchase_order_null,omitempty"`
}

func (m *Parameters) Reset()                    { *m = Parameters{} }
func (m *Parameters) String() string            { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()               {}
func (*Parameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameters) GetGetACertainOrder() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetACertainOrder
	}
	return nil
}

func (m *Parameters) GetPersonIdentificationValues() *dstore_values.StringValue {
	if m != nil {
		return m.PersonIdentificationValues
	}
	return nil
}

func (m *Parameters) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Parameters) GetDateAndTimeFormat() *dstore_values.IntegerValue {
	if m != nil {
		return m.DateAndTimeFormat
	}
	return nil
}

func (m *Parameters) GetIncludeTime() *dstore_values.BooleanValue {
	if m != nil {
		return m.IncludeTime
	}
	return nil
}

func (m *Parameters) GetFromDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *Parameters) GetToDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.ToDate
	}
	return nil
}

func (m *Parameters) GetOrderStateList() *dstore_values.StringValue {
	if m != nil {
		return m.OrderStateList
	}
	return nil
}

func (m *Parameters) GetSkipOHavingDifferentOStates() *dstore_values.BooleanValue {
	if m != nil {
		return m.SkipOHavingDifferentOStates
	}
	return nil
}

func (m *Parameters) GetOrderId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Parameters) GetRowcount() *dstore_values.IntegerValue {
	if m != nil {
		return m.Rowcount
	}
	return nil
}

func (m *Parameters) GetCaseSensitive() *dstore_values.BooleanValue {
	if m != nil {
		return m.CaseSensitive
	}
	return nil
}

func (m *Parameters) GetIncludeItemNo() *dstore_values.BooleanValue {
	if m != nil {
		return m.IncludeItemNo
	}
	return nil
}

func (m *Parameters) GetOrderDesc() *dstore_values.BooleanValue {
	if m != nil {
		return m.OrderDesc
	}
	return nil
}

func (m *Parameters) GetInformationTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.InformationTypeId
	}
	return nil
}

func (m *Parameters) GetInformation() *dstore_values.StringValue {
	if m != nil {
		return m.Information
	}
	return nil
}

func (m *Parameters) GetNodeCharacteristicId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeCharacteristicId
	}
	return nil
}

func (m *Parameters) GetLanguageId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LanguageId
	}
	return nil
}

func (m *Parameters) GetPurchaseOrder() *dstore_values.BooleanValue {
	if m != nil {
		return m.PurchaseOrder
	}
	return nil
}

type Response struct {
	Error           *dstore_engine_error.Error                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	MetaInformation []*dstore_engine_metainformation.MetaInformation `protobuf:"bytes,2,rep,name=meta_information,json=metaInformation" json:"meta_information,omitempty"`
	Message         []*dstore_engine_message.Message                 `protobuf:"bytes,3,rep,name=message" json:"message,omitempty"`
	Row             []*Response_Row                                  `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_engine_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetMetaInformation() []*dstore_engine_metainformation.MetaInformation {
	if m != nil {
		return m.MetaInformation
	}
	return nil
}

func (m *Response) GetMessage() []*dstore_engine_message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetRow() []*Response_Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type Response_Row struct {
	RowId                        int32                       `protobuf:"varint,10000,opt,name=row_id,json=rowId" json:"row_id,omitempty"`
	OrderDateAndTime             *dstore_values.StringValue  `protobuf:"bytes,10001,opt,name=order_date_and_time,json=orderDateAndTime" json:"order_date_and_time,omitempty"`
	PaymentCost                  *dstore_values.DecimalValue `protobuf:"bytes,10002,opt,name=payment_cost,json=paymentCost" json:"payment_cost,omitempty"`
	DeliveryDateAndTime          *dstore_values.StringValue  `protobuf:"bytes,10003,opt,name=delivery_date_and_time,json=deliveryDateAndTime" json:"delivery_date_and_time,omitempty"`
	NetShippingCost              *dstore_values.DecimalValue `protobuf:"bytes,10004,opt,name=net_shipping_cost,json=netShippingCost" json:"net_shipping_cost,omitempty"`
	OrderNo                      *dstore_values.StringValue  `protobuf:"bytes,10005,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	NettoSum                     *dstore_values.DecimalValue `protobuf:"bytes,10006,opt,name=netto_sum,json=nettoSum" json:"netto_sum,omitempty"`
	LastEditedByUserId           *dstore_values.IntegerValue `protobuf:"bytes,10007,opt,name=last_edited_by_user_id,json=lastEditedByUserId" json:"last_edited_by_user_id,omitempty"`
	OrderId                      *dstore_values.IntegerValue `protobuf:"bytes,10008,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	BruttoSum                    *dstore_values.DecimalValue `protobuf:"bytes,10009,opt,name=brutto_sum,json=bruttoSum" json:"brutto_sum,omitempty"`
	PreciseNetShippingCost       *dstore_values.DecimalValue `protobuf:"bytes,10010,opt,name=precise_net_shipping_cost,json=preciseNetShippingCost" json:"precise_net_shipping_cost,omitempty"`
	CharacVal2RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10011,opt,name=charac_val2_restr_by_pattern,json=characVal2RestrByPattern" json:"charac_val2_restr_by_pattern,omitempty"`
	NetSum                       *dstore_values.DecimalValue `protobuf:"bytes,10012,opt,name=net_sum,json=netSum" json:"net_sum,omitempty"`
	PersonId                     *dstore_values.IntegerValue `protobuf:"bytes,10013,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	PaymentTypeDescription       *dstore_values.StringValue  `protobuf:"bytes,10014,opt,name=payment_type_description,json=paymentTypeDescription" json:"payment_type_description,omitempty"`
	PreciseNetSum                *dstore_values.DecimalValue `protobuf:"bytes,10015,opt,name=precise_net_sum,json=preciseNetSum" json:"precise_net_sum,omitempty"`
	PositionCount                *dstore_values.IntegerValue `protobuf:"bytes,10016,opt,name=position_count,json=positionCount" json:"position_count,omitempty"`
	OrderStateId                 *dstore_values.IntegerValue `protobuf:"bytes,10017,opt,name=order_state_id,json=orderStateId" json:"order_state_id,omitempty"`
	ShippingTypeId               *dstore_values.IntegerValue `protobuf:"bytes,10018,opt,name=shipping_type_id,json=shippingTypeId" json:"shipping_type_id,omitempty"`
	PersonTypeId                 *dstore_values.IntegerValue `protobuf:"bytes,10019,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	GrossPaymentCost             *dstore_values.DecimalValue `protobuf:"bytes,10020,opt,name=gross_payment_cost,json=grossPaymentCost" json:"gross_payment_cost,omitempty"`
	NetPaymentCost               *dstore_values.DecimalValue `protobuf:"bytes,10021,opt,name=net_payment_cost,json=netPaymentCost" json:"net_payment_cost,omitempty"`
	DeliveryPersonId             *dstore_values.IntegerValue `protobuf:"bytes,10022,opt,name=delivery_person_id,json=deliveryPersonId" json:"delivery_person_id,omitempty"`
	ShippingTypeDescription      *dstore_values.StringValue  `protobuf:"bytes,10023,opt,name=shipping_type_description,json=shippingTypeDescription" json:"shipping_type_description,omitempty"`
	GrossShippingCost            *dstore_values.DecimalValue `protobuf:"bytes,10024,opt,name=gross_shipping_cost,json=grossShippingCost" json:"gross_shipping_cost,omitempty"`
	GrossSum                     *dstore_values.DecimalValue `protobuf:"bytes,10025,opt,name=gross_sum,json=grossSum" json:"gross_sum,omitempty"`
	UnitSymbol                   *dstore_values.StringValue  `protobuf:"bytes,10026,opt,name=unit_symbol,json=unitSymbol" json:"unit_symbol,omitempty"`
	PreciseNetPaymentCost        *dstore_values.DecimalValue `protobuf:"bytes,10027,opt,name=precise_net_payment_cost,json=preciseNetPaymentCost" json:"precise_net_payment_cost,omitempty"`
	CustomerCharacteristicValue2 *dstore_values.StringValue  `protobuf:"bytes,10028,opt,name=customer_characteristic_value2,json=customerCharacteristicValue2" json:"customer_characteristic_value2,omitempty"`
	PublicDescription            *dstore_values.StringValue  `protobuf:"bytes,10029,opt,name=public_description,json=publicDescription" json:"public_description,omitempty"`
	CurrencyId                   *dstore_values.IntegerValue `protobuf:"bytes,10030,opt,name=currency_id,json=currencyId" json:"currency_id,omitempty"`
	CustomerCharacteristicValue1 *dstore_values.StringValue  `protobuf:"bytes,10031,opt,name=customer_characteristic_value1,json=customerCharacteristicValue1" json:"customer_characteristic_value1,omitempty"`
	PreciseGrossSum              *dstore_values.DecimalValue `protobuf:"bytes,10032,opt,name=precise_gross_sum,json=preciseGrossSum" json:"precise_gross_sum,omitempty"`
	ShippingCost                 *dstore_values.DecimalValue `protobuf:"bytes,10033,opt,name=shipping_cost,json=shippingCost" json:"shipping_cost,omitempty"`
	CharacVal1RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10034,opt,name=charac_val1_restr_by_pattern,json=characVal1RestrByPattern" json:"charac_val1_restr_by_pattern,omitempty"`
	PaymentTypeId                *dstore_values.IntegerValue `protobuf:"bytes,10035,opt,name=payment_type_id,json=paymentTypeId" json:"payment_type_id,omitempty"`
	OrderState                   *dstore_values.StringValue  `protobuf:"bytes,10036,opt,name=order_state,json=orderState" json:"order_state,omitempty"`
	Description                  *dstore_values.StringValue  `protobuf:"bytes,20004,opt,name=description" json:"description,omitempty"`
	PreciseNetContentSum         *dstore_values.DecimalValue `protobuf:"bytes,20005,opt,name=precise_net_content_sum,json=preciseNetContentSum" json:"precise_net_content_sum,omitempty"`
	OrderContentNo               *dstore_values.StringValue  `protobuf:"bytes,20007,opt,name=order_content_no,json=orderContentNo" json:"order_content_no,omitempty"`
	OrderContentId               *dstore_values.IntegerValue `protobuf:"bytes,20010,opt,name=order_content_id,json=orderContentId" json:"order_content_id,omitempty"`
	CurrencySymbol               *dstore_values.StringValue  `protobuf:"bytes,20012,opt,name=currency_symbol,json=currencySymbol" json:"currency_symbol,omitempty"`
	NettoContentSum              *dstore_values.DecimalValue `protobuf:"bytes,20014,opt,name=netto_content_sum,json=nettoContentSum" json:"netto_content_sum,omitempty"`
	OrderContentPosition         *dstore_values.IntegerValue `protobuf:"bytes,20017,opt,name=order_content_position,json=orderContentPosition" json:"order_content_position,omitempty"`
	NetContentSum                *dstore_values.DecimalValue `protobuf:"bytes,20018,opt,name=net_content_sum,json=netContentSum" json:"net_content_sum,omitempty"`
	NodeId                       *dstore_values.IntegerValue `protobuf:"bytes,20019,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	GrossContentSum              *dstore_values.DecimalValue `protobuf:"bytes,20020,opt,name=gross_content_sum,json=grossContentSum" json:"gross_content_sum,omitempty"`
	PreciseGrossOrderSum         *dstore_values.DecimalValue `protobuf:"bytes,20023,opt,name=precise_gross_order_sum,json=preciseGrossOrderSum" json:"precise_gross_order_sum,omitempty"`
	PreciseGrossContentSum       *dstore_values.DecimalValue `protobuf:"bytes,20024,opt,name=precise_gross_content_sum,json=preciseGrossContentSum" json:"precise_gross_content_sum,omitempty"`
	GrossOrderSum                *dstore_values.DecimalValue `protobuf:"bytes,20026,opt,name=gross_order_sum,json=grossOrderSum" json:"gross_order_sum,omitempty"`
	OrderContentWasModified      *dstore_values.BooleanValue `protobuf:"bytes,20028,opt,name=order_content_was_modified,json=orderContentWasModified" json:"order_content_was_modified,omitempty"`
	ItemProperty                 *dstore_values.StringValue  `protobuf:"bytes,20029,opt,name=item_property,json=itemProperty" json:"item_property,omitempty"`
	Quantity                     *dstore_values.IntegerValue `protobuf:"bytes,20032,opt,name=quantity" json:"quantity,omitempty"`
	NetOrderSum                  *dstore_values.DecimalValue `protobuf:"bytes,20036,opt,name=net_order_sum,json=netOrderSum" json:"net_order_sum,omitempty"`
	BruttoContentSum             *dstore_values.DecimalValue `protobuf:"bytes,20040,opt,name=brutto_content_sum,json=bruttoContentSum" json:"brutto_content_sum,omitempty"`
	NettoOrderSum                *dstore_values.DecimalValue `protobuf:"bytes,20041,opt,name=netto_order_sum,json=nettoOrderSum" json:"netto_order_sum,omitempty"`
	ItemNo                       *dstore_values.StringValue  `protobuf:"bytes,20042,opt,name=item_no,json=itemNo" json:"item_no,omitempty"`
	PreciseNetOrderSum           *dstore_values.DecimalValue `protobuf:"bytes,20046,opt,name=precise_net_order_sum,json=preciseNetOrderSum" json:"precise_net_order_sum,omitempty"`
	BruttoOrderSum               *dstore_values.DecimalValue `protobuf:"bytes,20048,opt,name=brutto_order_sum,json=bruttoOrderSum" json:"brutto_order_sum,omitempty"`
}

func (m *Response_Row) Reset()                    { *m = Response_Row{} }
func (m *Response_Row) String() string            { return proto.CompactTextString(m) }
func (*Response_Row) ProtoMessage()               {}
func (*Response_Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Row) GetOrderDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.OrderDateAndTime
	}
	return nil
}

func (m *Response_Row) GetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.DeliveryDateAndTime
	}
	return nil
}

func (m *Response_Row) GetNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetShippingCost
	}
	return nil
}

func (m *Response_Row) GetOrderNo() *dstore_values.StringValue {
	if m != nil {
		return m.OrderNo
	}
	return nil
}

func (m *Response_Row) GetNettoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoSum
	}
	return nil
}

func (m *Response_Row) GetLastEditedByUserId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LastEditedByUserId
	}
	return nil
}

func (m *Response_Row) GetOrderId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Response_Row) GetBruttoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoSum
	}
	return nil
}

func (m *Response_Row) GetPreciseNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal2RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal2RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetSum
	}
	return nil
}

func (m *Response_Row) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PaymentTypeDescription
	}
	return nil
}

func (m *Response_Row) GetPreciseNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetSum
	}
	return nil
}

func (m *Response_Row) GetPositionCount() *dstore_values.IntegerValue {
	if m != nil {
		return m.PositionCount
	}
	return nil
}

func (m *Response_Row) GetOrderStateId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderStateId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ShippingTypeId
	}
	return nil
}

func (m *Response_Row) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Response_Row) GetGrossPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossPaymentCost
	}
	return nil
}

func (m *Response_Row) GetNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.DeliveryPersonId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ShippingTypeDescription
	}
	return nil
}

func (m *Response_Row) GetGrossShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossShippingCost
	}
	return nil
}

func (m *Response_Row) GetGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossSum
	}
	return nil
}

func (m *Response_Row) GetUnitSymbol() *dstore_values.StringValue {
	if m != nil {
		return m.UnitSymbol
	}
	return nil
}

func (m *Response_Row) GetPreciseNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue2() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue2
	}
	return nil
}

func (m *Response_Row) GetPublicDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PublicDescription
	}
	return nil
}

func (m *Response_Row) GetCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.CurrencyId
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue1() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue1
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossSum
	}
	return nil
}

func (m *Response_Row) GetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.ShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal1RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal1RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PaymentTypeId
	}
	return nil
}

func (m *Response_Row) GetOrderState() *dstore_values.StringValue {
	if m != nil {
		return m.OrderState
	}
	return nil
}

func (m *Response_Row) GetDescription() *dstore_values.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Response_Row) GetPreciseNetContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetContentSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentNo() *dstore_values.StringValue {
	if m != nil {
		return m.OrderContentNo
	}
	return nil
}

func (m *Response_Row) GetOrderContentId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderContentId
	}
	return nil
}

func (m *Response_Row) GetCurrencySymbol() *dstore_values.StringValue {
	if m != nil {
		return m.CurrencySymbol
	}
	return nil
}

func (m *Response_Row) GetNettoContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoContentSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentPosition() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderContentPosition
	}
	return nil
}

func (m *Response_Row) GetNetContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetContentSum
	}
	return nil
}

func (m *Response_Row) GetNodeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *Response_Row) GetGrossContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossContentSum
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossOrderSum
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossContentSum
	}
	return nil
}

func (m *Response_Row) GetGrossOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossOrderSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentWasModified() *dstore_values.BooleanValue {
	if m != nil {
		return m.OrderContentWasModified
	}
	return nil
}

func (m *Response_Row) GetItemProperty() *dstore_values.StringValue {
	if m != nil {
		return m.ItemProperty
	}
	return nil
}

func (m *Response_Row) GetQuantity() *dstore_values.IntegerValue {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Response_Row) GetNetOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetOrderSum
	}
	return nil
}

func (m *Response_Row) GetBruttoContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoContentSum
	}
	return nil
}

func (m *Response_Row) GetNettoOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoOrderSum
	}
	return nil
}

func (m *Response_Row) GetItemNo() *dstore_values.StringValue {
	if m != nil {
		return m.ItemNo
	}
	return nil
}

func (m *Response_Row) GetPreciseNetOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetOrderSum
	}
	return nil
}

func (m *Response_Row) GetBruttoOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoOrderSum
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "dstore.engine.om_GetOrders_Pu.Parameters")
	proto.RegisterType((*Response)(nil), "dstore.engine.om_GetOrders_Pu.Response")
	proto.RegisterType((*Response_Row)(nil), "dstore.engine.om_GetOrders_Pu.Response.Row")
}

var fileDescriptor0 = []byte{
	// 2070 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x59, 0x5b, 0x73, 0x1c, 0x57,
	0x11, 0x2e, 0xc7, 0x58, 0x5a, 0xb5, 0x76, 0x57, 0xab, 0x59, 0x59, 0x1e, 0x4b, 0x8e, 0xb1, 0x63,
	0x52, 0x04, 0x52, 0xb5, 0xc6, 0xa2, 0x88, 0x09, 0x90, 0x50, 0x96, 0x64, 0x3b, 0x4a, 0xec, 0xf5,
	0xb2, 0x72, 0x08, 0x04, 0xaa, 0xa6, 0x46, 0x33, 0x47, 0xeb, 0x29, 0x76, 0x67, 0x96, 0xb9, 0xd8,
	0xb5, 0x6f, 0xfc, 0x04, 0xee, 0x57, 0x73, 0x4f, 0x08, 0x84, 0x10, 0x48, 0x48, 0x15, 0x14, 0x05,
	0x55, 0x54, 0xc1, 0x03, 0xf0, 0x40, 0xf1, 0xc4, 0x7f, 0xe0, 0x7e, 0xbf, 0xbf, 0xd0, 0xe7, 0xf4,
	0x39, 0x3b, 0x67, 0x46, 0xb2, 0xe7, 0xa8, 0xf2, 0x92, 0x78, 0x35, 0xfd, 0x7d, 0xfd, 0x75, 0x9f,
	0xee, 0x3e, 0x3d, 0xbb, 0xd0, 0xf1, 0x93, 0x34, 0x8a, 0xd9, 0x59, 0x16, 0x0e, 0x82, 0x90, 0x9d,
	0x1d, 0xc7, 0x91, 0xc7, 0xfc, 0x2c, 0x66, 0xc9, 0xd9, 0x68, 0xe4, 0x5c, 0x66, 0xe9, 0xb5, 0xd8,
	0x67, 0x71, 0xe2, 0xf4, 0xb2, 0x0e, 0x3e, 0x4a, 0x23, 0xeb, 0x5e, 0xb2, 0xef, 0x90, 0x7d, 0xa7,
	0x64, 0xb4, 0xd2, 0x96, 0x74, 0x37, 0xdd, 0x61, 0xc6, 0x12, 0xc2, 0xac, 0x1c, 0x2f, 0xfa, 0x60,
	0x71, 0x1c, 0xc5, 0xf2, 0xd1, 0x6a, 0xf1, 0xd1, 0x88, 0x25, 0x89, 0x3b, 0x60, 0xf2, 0xe1, 0x99,
	0xf2, 0xc3, 0xd4, 0x0d, 0xc2, 0xdd, 0x28, 0x1e, 0xb9, 0x69, 0x10, 0x85, 0x64, 0x74, 0xdf, 0x87,
	0x2c, 0x80, 0x9e, 0x1b, 0xbb, 0xf8, 0x14, 0x35, 0x58, 0x8f, 0x43, 0x7b, 0xc0, 0x52, 0xc7, 0x75,
	0x3c, 0x16, 0x73, 0x73, 0x27, 0xe2, 0xda, 0xec, 0x43, 0xa7, 0x0e, 0x3d, 0x30, 0xbf, 0xb6, 0x2a,
	0xa3, 0xed, 0x48, 0x79, 0x3b, 0x51, 0x34, 0x64, 0x6e, 0xf8, 0x6e, 0xfe, 0xa9, 0xdf, 0x42, 0xdc,
	0x85, 0x0d, 0x42, 0x89, 0x80, 0xac, 0xf3, 0x60, 0xef, 0xc3, 0xe5, 0x84, 0xd9, 0x70, 0x68, 0xff,
	0x66, 0x16, 0x19, 0x6b, 0xfd, 0xa5, 0x32, 0xa8, 0x8b, 0x0f, 0xad, 0xf7, 0xc3, 0x89, 0x31, 0x8a,
	0x89, 0x42, 0x27, 0xf0, 0x59, 0x98, 0x06, 0xbb, 0x81, 0x27, 0x24, 0x3b, 0xe4, 0xd7, 0xbe, 0x47,
	0xa8, 0x59, 0x29, 0xa9, 0x49, 0xd2, 0x38, 0x08, 0x07, 0x24, 0x66, 0x85, 0xf0, 0x5b, 0x05, 0xb8,
	0x78, 0xc4, 0x43, 0x3c, 0x7d, 0x37, 0x76, 0xd2, 0xf7, 0x5b, 0xd2, 0x77, 0xf2, 0xce, 0x3c, 0x42,
	0xe9, 0x05, 0x68, 0x4a, 0xae, 0x74, 0x32, 0x66, 0x48, 0x68, 0x1f, 0xde, 0x37, 0x53, 0x41, 0x98,
	0xb2, 0x01, 0x8b, 0x49, 0x5c, 0x9d, 0x20, 0xd7, 0x11, 0xb1, 0xe5, 0x5b, 0x1d, 0x68, 0x17, 0x29,
	0x48, 0xc0, 0xef, 0x48, 0x40, 0x4b, 0xb7, 0x15, 0x2e, 0xaf, 0xc0, 0x92, 0xef, 0xa6, 0xcc, 0x71,
	0x43, 0xdf, 0x49, 0x83, 0x11, 0x73, 0xe8, 0x44, 0xed, 0xd7, 0x54, 0x3b, 0x5e, 0xe4, 0xc0, 0x0b,
	0xa1, 0x7f, 0x1d, 0x61, 0x97, 0x04, 0xca, 0x7a, 0x18, 0x8e, 0xef, 0xc7, 0x46, 0x1a, 0x7e, 0x4f,
	0x1a, 0x8e, 0xee, 0x81, 0x09, 0x21, 0x8f, 0x42, 0x3d, 0x08, 0xbd, 0x61, 0xe6, 0x33, 0x81, 0xb4,
	0x8f, 0x54, 0xd7, 0xc8, 0xbc, 0x04, 0x70, 0x26, 0xeb, 0x41, 0x58, 0xd4, 0xf1, 0xe4, 0xf2, 0x0f,
	0xe4, 0x72, 0x41, 0x33, 0x14, 0xce, 0xde, 0x06, 0x73, 0xbb, 0x31, 0x76, 0x0b, 0x97, 0x62, 0xcf,
	0x08, 0x4f, 0xf7, 0x96, 0x3c, 0x71, 0x92, 0x24, 0x75, 0x47, 0x63, 0xf2, 0x55, 0xe3, 0xf6, 0x9b,
	0x68, 0x6e, 0xdd, 0x0f, 0xcd, 0x29, 0x96, 0xbc, 0xfc, 0x91, 0xbc, 0xd4, 0x95, 0x89, 0x70, 0xf1,
	0x10, 0xcc, 0xa6, 0x11, 0x39, 0x98, 0x35, 0x71, 0x30, 0x93, 0x46, 0x82, 0xfe, 0x34, 0xd4, 0x25,
	0x8e, 0xc8, 0xff, 0x44, 0xe4, 0x40, 0x8f, 0x05, 0xf5, 0x26, 0xb4, 0xa8, 0xf6, 0x11, 0x8e, 0x66,
	0xc3, 0x20, 0x49, 0xed, 0x5a, 0x65, 0x11, 0x37, 0x05, 0x66, 0x9b, 0x43, 0xae, 0x20, 0xc2, 0x5a,
	0x83, 0xa3, 0x65, 0x16, 0xf2, 0xf8, 0x67, 0xf2, 0x68, 0x15, 0xed, 0x85, 0xe7, 0x1d, 0x38, 0x95,
	0x7c, 0x20, 0x18, 0x3b, 0x91, 0x73, 0xc3, 0xbd, 0x89, 0xcc, 0x8e, 0x1f, 0xec, 0xee, 0xb2, 0x18,
	0xcb, 0x19, 0xff, 0x24, 0x78, 0x12, 0x7b, 0xae, 0xfa, 0xe0, 0x56, 0x39, 0xc9, 0xb5, 0xc7, 0x04,
	0xc5, 0xa6, 0x62, 0xb8, 0x26, 0x5c, 0x25, 0xd6, 0x35, 0xb8, 0xbf, 0xca, 0x07, 0xe9, 0xfc, 0x0b,
	0xe9, 0x7c, 0xed, 0x5d, 0xc8, 0xe4, 0x49, 0xd4, 0x28, 0x50, 0xec, 0x27, 0xa8, 0x2e, 0xeb, 0x59,
	0x61, 0x8c, 0xad, 0x74, 0x06, 0x1a, 0x0a, 0x47, 0x0e, 0xff, 0x4a, 0x0e, 0xe7, 0xa5, 0x81, 0x20,
	0x3f, 0x0f, 0xb5, 0x38, 0xba, 0xe5, 0x45, 0x59, 0x98, 0xda, 0xf3, 0xd5, 0xe4, 0x53, 0x63, 0xeb,
	0x75, 0xd0, 0x50, 0xff, 0x26, 0xf6, 0xbf, 0xc9, 0x2a, 0x52, 0x7f, 0x15, 0xf4, 0xeb, 0xd0, 0xf4,
	0xdc, 0x84, 0x39, 0x09, 0x0b, 0x93, 0x20, 0x0d, 0x6e, 0x32, 0xbb, 0x5e, 0x9d, 0xde, 0x06, 0x87,
	0x6c, 0x2b, 0x84, 0x75, 0x16, 0xda, 0x45, 0x0e, 0xf2, 0xf7, 0x77, 0xf2, 0xb7, 0x58, 0x30, 0x16,
	0x4e, 0x37, 0x40, 0x35, 0x8c, 0x13, 0xa4, 0x6c, 0xe4, 0x84, 0x91, 0xdd, 0x30, 0xf0, 0x2a, 0x31,
	0x5b, 0x08, 0xe9, 0x46, 0xd6, 0x9b, 0x60, 0xa9, 0x44, 0x42, 0x6e, 0xff, 0x21, 0xdd, 0x16, 0xac,
	0x65, 0x53, 0x02, 0xe5, 0xdb, 0x67, 0x89, 0x67, 0x37, 0xab, 0x3d, 0xce, 0x09, 0xf3, 0x4d, 0xb4,
	0xb6, 0x5e, 0x0f, 0x0b, 0x39, 0x96, 0x1c, 0xfd, 0x93, 0x1c, 0x35, 0xa6, 0x46, 0xc2, 0xc9, 0x13,
	0xd0, 0xd6, 0x6e, 0xad, 0xe9, 0x9c, 0x5d, 0x30, 0x18, 0x77, 0x1a, 0x4e, 0x0e, 0xdb, 0xb7, 0x82,
	0xbd, 0x0f, 0x19, 0xb9, 0xff, 0x97, 0x9c, 0x76, 0x7b, 0x50, 0x42, 0xc6, 0x3b, 0x60, 0x5e, 0x7b,
	0x60, 0xb7, 0x2a, 0xbb, 0x57, 0x37, 0xb7, 0xde, 0x08, 0x2d, 0xdd, 0xaf, 0xf0, 0xf7, 0xef, 0xe9,
	0xa8, 0x9b, 0x3e, 0x10, 0x9e, 0xde, 0x05, 0xcb, 0x61, 0x84, 0x87, 0xe0, 0xdd, 0xc0, 0x6b, 0xd9,
	0xc3, 0x5b, 0x19, 0x7b, 0x39, 0xf0, 0x78, 0xcc, 0x8b, 0xd5, 0x31, 0x2f, 0x71, 0xe8, 0x46, 0x01,
	0x89, 0x61, 0x3f, 0x0a, 0xab, 0xfb, 0x53, 0x92, 0x92, 0xff, 0x90, 0x12, 0x7b, 0x3f, 0xac, 0x0a,
	0x7e, 0xe8, 0x86, 0x83, 0x0c, 0x77, 0x0b, 0xae, 0xc3, 0xaa, 0xd6, 0x01, 0xca, 0x1e, 0xbd, 0xbf,
	0x01, 0x5a, 0x1a, 0x9a, 0x5c, 0xfe, 0x97, 0x5c, 0x36, 0x73, 0x33, 0xd5, 0x3d, 0xe3, 0x2c, 0x46,
	0x99, 0x58, 0xfd, 0xb4, 0x79, 0xb4, 0x0d, 0xea, 0x58, 0x41, 0x68, 0xed, 0xc0, 0xee, 0x29, 0x72,
	0x90, 0xc7, 0xff, 0xc9, 0x32, 0x2e, 0x18, 0x73, 0xa7, 0xf7, 0xfd, 0xfa, 0x0c, 0xd4, 0xfa, 0x2c,
	0x19, 0x47, 0x61, 0xc2, 0xb0, 0x0b, 0x8e, 0x88, 0x05, 0x4b, 0xae, 0x3c, 0xd3, 0x13, 0x96, 0x0b,
	0x1b, 0x2d, 0x5f, 0x17, 0xf9, 0x7f, 0xfb, 0x64, 0x68, 0xbd, 0x17, 0x5a, 0x7c, 0xb5, 0x72, 0xf4,
	0xf2, 0xb8, 0xe7, 0xd4, 0x61, 0x04, 0x77, 0x4a, 0xe0, 0xf2, 0x06, 0x76, 0x15, 0x3f, 0x6f, 0xe5,
	0x9f, 0xfb, 0x0b, 0xa3, 0xe2, 0x1f, 0xb0, 0x5c, 0x67, 0xe5, 0x4a, 0x87, 0x7b, 0x05, 0x67, 0x3c,
	0xb9, 0x87, 0x91, 0x16, 0xbe, 0xab, 0xf4, 0xff, 0xbe, 0x32, 0xb7, 0x1e, 0x81, 0xc3, 0x38, 0x96,
	0x70, 0x29, 0xe0, 0xa8, 0x07, 0x3b, 0x77, 0xdd, 0x3a, 0x3b, 0x2a, 0xf8, 0x4e, 0x3f, 0xba, 0xd5,
	0xe7, 0xb8, 0x95, 0x9f, 0x9c, 0x86, 0xc3, 0xf8, 0xc1, 0x5a, 0x86, 0x19, 0xfc, 0xc8, 0xcf, 0xfc,
	0xc3, 0x5d, 0xcc, 0xc7, 0x91, 0xfe, 0x11, 0xfc, 0x88, 0x47, 0x8a, 0x6b, 0xa2, 0xec, 0x5e, 0x7d,
	0x79, 0xb0, 0x3f, 0xd2, 0xad, 0x6c, 0x0b, 0xba, 0x08, 0x37, 0xf3, 0x8d, 0xc2, 0x7a, 0x27, 0xd4,
	0xc7, 0xee, 0x64, 0xc4, 0xaf, 0x0b, 0x2f, 0xc2, 0x8b, 0xf1, 0xa3, 0xdd, 0x7d, 0x8f, 0xdc, 0x67,
	0x5e, 0x30, 0x72, 0x87, 0xb2, 0xb9, 0x24, 0x62, 0x03, 0x01, 0x56, 0x0f, 0x96, 0x7d, 0x36, 0xc4,
	0x59, 0x18, 0x4f, 0x4a, 0x7a, 0x3e, 0x56, 0xad, 0xa7, 0xad, 0xa0, 0xba, 0xa4, 0xc7, 0x60, 0x31,
	0xc4, 0xcd, 0x35, 0xb9, 0x11, 0x8c, 0xc7, 0xfc, 0x42, 0x13, 0xba, 0x3e, 0x6e, 0xa0, 0x6b, 0x01,
	0x61, 0xdb, 0x12, 0x25, 0xb4, 0x4d, 0xaf, 0x32, 0x1c, 0xc9, 0x9f, 0xa8, 0x56, 0x43, 0x57, 0x19,
	0x0e, 0xe3, 0x87, 0x61, 0x0e, 0xa9, 0x70, 0xaf, 0x48, 0xb2, 0x91, 0xfd, 0x49, 0x03, 0xcf, 0x35,
	0x61, 0xbe, 0x9d, 0x8d, 0x78, 0x3a, 0x86, 0x2e, 0xae, 0x06, 0xcc, 0xc7, 0x31, 0xee, 0x3b, 0x3b,
	0x13, 0x27, 0x4b, 0xe8, 0x2e, 0xfd, 0x54, 0xb7, 0xba, 0x71, 0x2d, 0x8e, 0xbd, 0x28, 0xa0, 0xeb,
	0x93, 0x27, 0x13, 0x71, 0xaf, 0x9e, 0xd7, 0xee, 0xe3, 0x4f, 0x77, 0x0f, 0x70, 0x21, 0xbf, 0x1d,
	0x60, 0x27, 0xce, 0x54, 0x18, 0x9f, 0x31, 0x08, 0x63, 0x8e, 0xec, 0x79, 0x1c, 0x4f, 0xc1, 0xf1,
	0x71, 0x8c, 0xcf, 0xb0, 0x8d, 0xf7, 0x1e, 0xc6, 0x67, 0x0d, 0xb8, 0x96, 0x25, 0xbc, 0x5b, 0x3a,
	0x93, 0xf7, 0xc1, 0x09, 0x1a, 0x84, 0x7c, 0xe3, 0x5f, 0x73, 0xf0, 0x65, 0x2d, 0x8d, 0x79, 0x9a,
	0xc6, 0x6e, 0x8a, 0x73, 0x2f, 0xb4, 0x3f, 0x57, 0x7d, 0x4e, 0x36, 0x11, 0xe0, 0x87, 0xb5, 0x3e,
	0x87, 0xaf, 0x4f, 0x7a, 0x04, 0xb6, 0xde, 0x02, 0xb3, 0x42, 0x2d, 0xc6, 0x7b, 0xdb, 0x40, 0xe3,
	0x0c, 0x2f, 0x18, 0x0c, 0x16, 0xcf, 0x7b, 0xfa, 0x52, 0x62, 0x7f, 0xde, 0x20, 0xc7, 0x35, 0xf5,
	0x66, 0x62, 0x3d, 0x09, 0xb6, 0xea, 0x1f, 0x71, 0x9f, 0xf1, 0x0b, 0x35, 0x0e, 0xc6, 0x62, 0x0e,
	0x7d, 0xa1, 0x3a, 0x94, 0x65, 0x09, 0xe6, 0x77, 0xdd, 0x66, 0x0e, 0xc5, 0x9d, 0x75, 0xa1, 0x90,
	0x7e, 0x0c, 0xe8, 0x8b, 0x06, 0x01, 0x35, 0xb4, 0xa4, 0x63, 0x5c, 0x1b, 0x38, 0xd0, 0x23, 0xbe,
	0xa9, 0x60, 0x64, 0xb4, 0x73, 0x7d, 0xc9, 0x20, 0xb8, 0x86, 0xc2, 0x6c, 0x88, 0xcd, 0x0b, 0x6f,
	0x05, 0x7d, 0xf1, 0xc5, 0x0c, 0x7d, 0xd9, 0x80, 0xa4, 0x9e, 0xaf, 0xc3, 0x98, 0xa5, 0x4b, 0xd0,
	0x9a, 0x56, 0x90, 0xda, 0x21, 0xbe, 0x62, 0xc0, 0xd2, 0x54, 0x28, 0xb9, 0x41, 0xac, 0xef, 0x79,
	0xe3, 0xfb, 0x6a, 0xf7, 0xa0, 0xaf, 0x7c, 0x8f, 0x83, 0x35, 0x88, 0xa3, 0x24, 0x71, 0x0a, 0x73,
	0xef, 0x19, 0x83, 0xec, 0xb6, 0x04, 0xae, 0xa7, 0x0d, 0x3f, 0x8c, 0x8b, 0x1f, 0x4f, 0x81, 0xe9,
	0x59, 0x03, 0xa6, 0x26, 0xa2, 0x74, 0x1e, 0xd4, 0x34, 0x1d, 0xa2, 0x79, 0x25, 0x7e, 0xcd, 0x20,
	0xb6, 0x96, 0xc2, 0xf5, 0x54, 0x45, 0x62, 0xe7, 0x16, 0x73, 0xad, 0x97, 0xe4, 0x73, 0xd5, 0x25,
	0x79, 0x4c, 0xcf, 0xb9, 0x5e, 0x93, 0x57, 0xa0, 0x4d, 0x89, 0x2b, 0x0e, 0x83, 0xaf, 0x1b, 0xc4,
	0xbb, 0x28, 0x80, 0x85, 0x39, 0x80, 0x3d, 0x27, 0xd9, 0xb0, 0xb6, 0xbf, 0x61, 0x32, 0x63, 0x89,
	0x03, 0xcb, 0x1a, 0x17, 0xa2, 0x2c, 0x0c, 0xb0, 0x2b, 0x26, 0xa3, 0x9d, 0x68, 0x68, 0x3f, 0x5f,
	0x1d, 0x13, 0x70, 0xfb, 0x6d, 0x61, 0x2e, 0x3a, 0x56, 0x6b, 0xad, 0xc2, 0xd9, 0x7d, 0xd3, 0x40,
	0xc7, 0xd1, 0xbc, 0xc7, 0xf4, 0x23, 0x74, 0xe1, 0xa4, 0x97, 0x21, 0x6a, 0x84, 0x9d, 0x52, 0xda,
	0xf4, 0x04, 0xcb, 0x9a, 0xfd, 0x42, 0xb5, 0xce, 0x13, 0x8a, 0xa2, 0xb8, 0x08, 0x8a, 0x87, 0x6b,
	0xbc, 0x4a, 0xc6, 0xd9, 0xce, 0x10, 0x19, 0xf5, 0x23, 0xfd, 0x56, 0x35, 0xed, 0x22, 0xc1, 0xf4,
	0xc3, 0x7c, 0x04, 0xe6, 0xbd, 0x2c, 0xc6, 0x77, 0x3f, 0x6f, 0xc2, 0x4b, 0xed, 0x45, 0x83, 0x52,
	0x03, 0x05, 0xc0, 0x22, 0xab, 0x8a, 0xf6, 0x9c, 0xfd, 0xed, 0x57, 0x17, 0xed, 0x39, 0xbe, 0x06,
	0xa8, 0x73, 0xca, 0x0b, 0xe5, 0x3b, 0x26, 0x6b, 0x80, 0x84, 0x5d, 0x56, 0xf5, 0x72, 0x01, 0x1a,
	0xc5, 0x92, 0x7d, 0xc9, 0x80, 0xa5, 0x9e, 0xdc, 0xf1, 0xd6, 0x3a, 0xb7, 0xf7, 0xd6, 0x7a, 0xf9,
	0x20, 0xb7, 0xd6, 0xb9, 0xd2, 0xad, 0xc5, 0x87, 0xbd, 0x7e, 0x87, 0xe0, 0x79, 0x7c, 0xd7, 0x68,
	0x4e, 0xe7, 0x77, 0x07, 0x1e, 0x09, 0x76, 0x85, 0x36, 0xa7, 0xed, 0x57, 0x0c, 0xba, 0x22, 0x9f,
	0xd1, 0xf8, 0x92, 0x32, 0xaf, 0x17, 0xd5, 0x33, 0xb7, 0x0f, 0x55, 0xbf, 0x63, 0x69, 0x00, 0xeb,
	0x3a, 0x1c, 0xd3, 0xbb, 0xca, 0x8b, 0x50, 0x69, 0x48, 0x17, 0xd7, 0xb3, 0xb7, 0x0f, 0x55, 0xa7,
	0x7b, 0x29, 0xef, 0xaa, 0x0d, 0xc2, 0xf2, 0x93, 0xbb, 0xa4, 0xbe, 0xba, 0x51, 0x7c, 0xb8, 0xc8,
	0x3d, 0x67, 0x20, 0x8d, 0x6e, 0x2c, 0x49, 0x84, 0x0b, 0xdd, 0xe5, 0x32, 0x0f, 0xa6, 0xf8, 0xf9,
	0x3b, 0xc8, 0x2a, 0x5e, 0x40, 0x3a, 0x11, 0x26, 0xf9, 0x22, 0x2c, 0x4c, 0xdb, 0x46, 0x8e, 0x9f,
	0x17, 0x4c, 0xf4, 0x28, 0x90, 0x9c, 0x41, 0x5b, 0x62, 0xc5, 0xc5, 0xcd, 0x4c, 0xcf, 0xd3, 0x8b,
	0x26, 0x79, 0x5a, 0x10, 0x38, 0x2d, 0x45, 0xdb, 0xb0, 0x5c, 0x0c, 0x4d, 0xdd, 0xde, 0xf6, 0x4b,
	0x26, 0x01, 0x2e, 0xe9, 0x01, 0xf6, 0x24, 0x94, 0x87, 0x59, 0x3e, 0xc5, 0x97, 0x4d, 0xd4, 0x35,
	0xc2, 0xc2, 0xf1, 0x3d, 0x84, 0xeb, 0x18, 0x7f, 0xf3, 0xe5, 0x05, 0x6d, 0x22, 0x66, 0x86, 0x5b,
	0x63, 0x96, 0x31, 0x3d, 0xd4, 0xf2, 0xba, 0x80, 0x57, 0x8c, 0xd2, 0x23, 0x70, 0x9a, 0x04, 0xad,
	0x2e, 0x89, 0x52, 0xf6, 0x08, 0x12, 0x7e, 0xef, 0x20, 0x75, 0x29, 0x86, 0x89, 0x78, 0x69, 0xe3,
	0xac, 0xef, 0xc9, 0xb7, 0xe3, 0xbd, 0x42, 0xbf, 0x6f, 0xc2, 0xbb, 0xac, 0xf3, 0x6a, 0x7a, 0x31,
	0xf3, 0x65, 0x9d, 0x3f, 0x30, 0xca, 0xfc, 0xa0, 0x20, 0xf0, 0x69, 0x58, 0x29, 0x56, 0xc5, 0x2d,
	0x37, 0x71, 0x46, 0x91, 0x1f, 0xec, 0x06, 0xcc, 0xb7, 0x7f, 0x78, 0xdb, 0xe0, 0x27, 0x85, 0x63,
	0x7a, 0x65, 0x3c, 0xe5, 0x26, 0x57, 0x25, 0x9a, 0x8f, 0x53, 0xf1, 0x15, 0xd5, 0x38, 0x8e, 0x70,
	0x57, 0x49, 0x27, 0xf6, 0x8f, 0x0c, 0x3a, 0xa0, 0xce, 0x21, 0x3d, 0x89, 0xc0, 0xcb, 0xbf, 0xf6,
	0xc1, 0xcc, 0x0d, 0xd3, 0x00, 0xd1, 0x3f, 0x36, 0xa9, 0x8c, 0xa9, 0x39, 0xf7, 0xce, 0x4b, 0x33,
	0x4f, 0xcf, 0x4f, 0x4d, 0xd2, 0x33, 0x1f, 0xca, 0x57, 0x6e, 0x9e, 0x9c, 0x27, 0xc0, 0x92, 0x2f,
	0x46, 0xfa, 0xb1, 0xfd, 0xcc, 0x84, 0xa7, 0x45, 0xc0, 0xe2, 0x81, 0x51, 0x2b, 0xe7, 0x8a, 0x7e,
	0x6e, 0xda, 0x2a, 0x69, 0x34, 0xd5, 0x84, 0x6f, 0x2e, 0xea, 0xcb, 0xc3, 0x5f, 0x18, 0xa4, 0x73,
	0x26, 0xa0, 0xaf, 0x0d, 0x7b, 0x70, 0x54, 0x1f, 0xbb, 0xb9, 0x86, 0x5f, 0x9a, 0x68, 0xb0, 0xf2,
	0xa1, 0x3b, 0x15, 0x82, 0xa3, 0x52, 0x26, 0x27, 0x27, 0xfb, 0x95, 0x09, 0x59, 0x93, 0x60, 0x8a,
	0x68, 0xfd, 0x32, 0xac, 0x06, 0x51, 0xe9, 0xbb, 0x8f, 0xfc, 0x17, 0xba, 0xa7, 0x1f, 0x30, 0xfd,
	0xed, 0x6e, 0x67, 0x46, 0xfc, 0x56, 0xf6, 0xe6, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xcf,
	0xb6, 0x43, 0xee, 0x1b, 0x00, 0x00,
}
