// Code generated by protoc-gen-go.
// source: dstore/elastic/item/facetednavigation.proto
// DO NOT EDIT!

/*
Package faceted_navigation is a generated protocol buffer package.

It is generated from these files:
	dstore/elastic/item/facetednavigation.proto

It has these top-level messages:
	Request
	Response
*/
package faceted_navigation

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_elastic "dstore/elastic/elastic"
import dstore_elastic_item "dstore/elastic/item/elastic_item"
import dstore_elastic_error "dstore/elastic/elastic_error"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	BaseQuery      *dstore_elastic.BoolQuery `protobuf:"bytes,1,opt,name=base_query,json=baseQuery" json:"base_query,omitempty"`
	PostQuery      *dstore_elastic.BoolQuery `protobuf:"bytes,2,opt,name=post_query,json=postQuery" json:"post_query,omitempty"`
	Facet          []*Request_Facet          `protobuf:"bytes,3,rep,name=facet" json:"facet,omitempty"`
	RangeFacet     []*Request_RangeFacet     `protobuf:"bytes,5,rep,name=range_facet,json=rangeFacet" json:"range_facet,omitempty"`
	DateRangeFacet []*Request_RangeFacet     `protobuf:"bytes,6,rep,name=date_range_facet,json=dateRangeFacet" json:"date_range_facet,omitempty"`
	// Paginierung GET /_search?size=5&from=5
	From int32                  `protobuf:"varint,10,opt,name=from" json:"from,omitempty"`
	Size int32                  `protobuf:"varint,11,opt,name=size" json:"size,omitempty"`
	Sort []*dstore_elastic.Sort `protobuf:"bytes,20,rep,name=sort" json:"sort,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetBaseQuery() *dstore_elastic.BoolQuery {
	if m != nil {
		return m.BaseQuery
	}
	return nil
}

func (m *Request) GetPostQuery() *dstore_elastic.BoolQuery {
	if m != nil {
		return m.PostQuery
	}
	return nil
}

func (m *Request) GetFacet() []*Request_Facet {
	if m != nil {
		return m.Facet
	}
	return nil
}

func (m *Request) GetRangeFacet() []*Request_RangeFacet {
	if m != nil {
		return m.RangeFacet
	}
	return nil
}

func (m *Request) GetDateRangeFacet() []*Request_RangeFacet {
	if m != nil {
		return m.DateRangeFacet
	}
	return nil
}

func (m *Request) GetSort() []*dstore_elastic.Sort {
	if m != nil {
		return m.Sort
	}
	return nil
}

type Request_RangeFacet struct {
	FieldName string                  `protobuf:"bytes,1,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	Range     []*dstore_elastic.Range `protobuf:"bytes,2,rep,name=range" json:"range,omitempty"`
}

func (m *Request_RangeFacet) Reset()                    { *m = Request_RangeFacet{} }
func (m *Request_RangeFacet) String() string            { return proto.CompactTextString(m) }
func (*Request_RangeFacet) ProtoMessage()               {}
func (*Request_RangeFacet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Request_RangeFacet) GetRange() []*dstore_elastic.Range {
	if m != nil {
		return m.Range
	}
	return nil
}

type Request_Facet struct {
	FieldName string `protobuf:"bytes,1,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	// Types that are valid to be assigned to SortBy:
	//	*Request_Facet_SortNoSort_
	//	*Request_Facet_FieldSort_
	SortBy isRequest_Facet_SortBy `protobuf_oneof:"sort_by"`
}

func (m *Request_Facet) Reset()                    { *m = Request_Facet{} }
func (m *Request_Facet) String() string            { return proto.CompactTextString(m) }
func (*Request_Facet) ProtoMessage()               {}
func (*Request_Facet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type isRequest_Facet_SortBy interface {
	isRequest_Facet_SortBy()
}

type Request_Facet_SortNoSort_ struct {
	SortNoSort *Request_Facet_SortNoSort `protobuf:"bytes,2,opt,name=sort_no_sort,json=sortNoSort,oneof"`
}
type Request_Facet_FieldSort_ struct {
	FieldSort *Request_Facet_FieldSort `protobuf:"bytes,3,opt,name=field_sort,json=fieldSort,oneof"`
}

func (*Request_Facet_SortNoSort_) isRequest_Facet_SortBy() {}
func (*Request_Facet_FieldSort_) isRequest_Facet_SortBy()  {}

func (m *Request_Facet) GetSortBy() isRequest_Facet_SortBy {
	if m != nil {
		return m.SortBy
	}
	return nil
}

func (m *Request_Facet) GetSortNoSort() *Request_Facet_SortNoSort {
	if x, ok := m.GetSortBy().(*Request_Facet_SortNoSort_); ok {
		return x.SortNoSort
	}
	return nil
}

func (m *Request_Facet) GetFieldSort() *Request_Facet_FieldSort {
	if x, ok := m.GetSortBy().(*Request_Facet_FieldSort_); ok {
		return x.FieldSort
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request_Facet) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_Facet_OneofMarshaler, _Request_Facet_OneofUnmarshaler, _Request_Facet_OneofSizer, []interface{}{
		(*Request_Facet_SortNoSort_)(nil),
		(*Request_Facet_FieldSort_)(nil),
	}
}

func _Request_Facet_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request_Facet)
	// sort_by
	switch x := m.SortBy.(type) {
	case *Request_Facet_SortNoSort_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SortNoSort); err != nil {
			return err
		}
	case *Request_Facet_FieldSort_:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FieldSort); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request_Facet.SortBy has unexpected type %T", x)
	}
	return nil
}

func _Request_Facet_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request_Facet)
	switch tag {
	case 2: // sort_by.sort_no_sort
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_Facet_SortNoSort)
		err := b.DecodeMessage(msg)
		m.SortBy = &Request_Facet_SortNoSort_{msg}
		return true, err
	case 3: // sort_by.field_sort
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Request_Facet_FieldSort)
		err := b.DecodeMessage(msg)
		m.SortBy = &Request_Facet_FieldSort_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_Facet_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request_Facet)
	// sort_by
	switch x := m.SortBy.(type) {
	case *Request_Facet_SortNoSort_:
		s := proto.Size(x.SortNoSort)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_Facet_FieldSort_:
		s := proto.Size(x.FieldSort)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Request_Facet_SortNoSort struct {
	SortOrder dstore_elastic.Sort_Order `protobuf:"varint,1,opt,name=sort_order,json=sortOrder,enum=dstore.elastic.Sort_Order" json:"sort_order,omitempty"`
}

func (m *Request_Facet_SortNoSort) Reset()                    { *m = Request_Facet_SortNoSort{} }
func (m *Request_Facet_SortNoSort) String() string            { return proto.CompactTextString(m) }
func (*Request_Facet_SortNoSort) ProtoMessage()               {}
func (*Request_Facet_SortNoSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 0} }

type Request_Facet_FieldSort struct {
	FieldName string                    `protobuf:"bytes,1,opt,name=field_name,json=fieldName" json:"field_name,omitempty"`
	SortOrder dstore_elastic.Sort_Order `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,enum=dstore.elastic.Sort_Order" json:"sort_order,omitempty"`
	SortMode  dstore_elastic.Sort_Mode  `protobuf:"varint,3,opt,name=sort_mode,json=sortMode,enum=dstore.elastic.Sort_Mode" json:"sort_mode,omitempty"`
}

func (m *Request_Facet_FieldSort) Reset()                    { *m = Request_Facet_FieldSort{} }
func (m *Request_Facet_FieldSort) String() string            { return proto.CompactTextString(m) }
func (*Request_Facet_FieldSort) ProtoMessage()               {}
func (*Request_Facet_FieldSort) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1, 1} }

type Response struct {
	Error              *dstore_elastic_error.Error  `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	TotalHits          int32                        `protobuf:"varint,2,opt,name=total_hits,json=totalHits" json:"total_hits,omitempty"`
	Item               []*dstore_elastic_item.Item  `protobuf:"bytes,3,rep,name=item" json:"item,omitempty"`
	Facet              []*dstore_elastic_item.Facet `protobuf:"bytes,4,rep,name=facet" json:"facet,omitempty"`
	ElasticQueryString string                       `protobuf:"bytes,5,opt,name=elastic_query_string,json=elasticQueryString" json:"elastic_query_string,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_elastic_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetItem() []*dstore_elastic_item.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Response) GetFacet() []*dstore_elastic_item.Facet {
	if m != nil {
		return m.Facet
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "dstore.elastic.facetednavigation.Request")
	proto.RegisterType((*Request_RangeFacet)(nil), "dstore.elastic.facetednavigation.Request.RangeFacet")
	proto.RegisterType((*Request_Facet)(nil), "dstore.elastic.facetednavigation.Request.Facet")
	proto.RegisterType((*Request_Facet_SortNoSort)(nil), "dstore.elastic.facetednavigation.Request.Facet.SortNoSort")
	proto.RegisterType((*Request_Facet_FieldSort)(nil), "dstore.elastic.facetednavigation.Request.Facet.FieldSort")
	proto.RegisterType((*Response)(nil), "dstore.elastic.facetednavigation.Response")
}

var fileDescriptor0 = []byte{
	// 584 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0x26, 0x4d, 0xb7, 0xed, 0x4e, 0x51, 0x04, 0x56, 0x40, 0x61, 0xf9, 0x51, 0xd4, 0x03, 0xaa,
	0x54, 0xb1, 0x29, 0x05, 0x21, 0xca, 0x31, 0x52, 0x43, 0x39, 0x10, 0x84, 0x23, 0x24, 0xd4, 0x43,
	0xad, 0x4d, 0xd7, 0x09, 0x2b, 0x25, 0xeb, 0x60, 0x1b, 0xa4, 0x72, 0xe2, 0x45, 0x78, 0x2d, 0x5e,
	0x83, 0x57, 0xc0, 0x33, 0xde, 0x24, 0xed, 0x26, 0x22, 0x8d, 0xb8, 0x58, 0xe3, 0x99, 0xef, 0xfb,
	0x66, 0x3c, 0xb6, 0x07, 0x0e, 0x52, 0x63, 0x95, 0x96, 0x2d, 0x39, 0x4a, 0x8c, 0xcd, 0x2e, 0x5a,
	0x99, 0x95, 0xe3, 0xd6, 0x20, 0xb9, 0x90, 0x56, 0xa6, 0x79, 0xf2, 0x3d, 0x1b, 0x26, 0x36, 0x53,
	0x79, 0x3c, 0xd1, 0xca, 0x2a, 0xd6, 0xf4, 0xe0, 0xb8, 0x00, 0xc7, 0x0b, 0xb8, 0xe8, 0x51, 0x49,
	0x6e, 0x8a, 0x24, 0x7e, 0xf4, 0x64, 0x59, 0x32, 0x5c, 0x8a, 0x78, 0x54, 0x66, 0x6b, 0xad, 0xb4,
	0x8f, 0xed, 0xfd, 0xdc, 0x81, 0x6d, 0x2e, 0xbf, 0x7e, 0x93, 0xc6, 0xb2, 0xd7, 0x00, 0xfd, 0xc4,
	0x48, 0xe1, 0x76, 0xfa, 0xb2, 0x51, 0x69, 0x56, 0xf6, 0x77, 0x8f, 0x1e, 0xc4, 0xa5, 0xe2, 0xda,
	0x4a, 0x8d, 0x3e, 0x22, 0x80, 0x87, 0x08, 0x26, 0x13, 0x99, 0x13, 0x65, 0x6c, 0xc1, 0xdc, 0x58,
	0xc9, 0x44, 0xb0, 0x67, 0x9e, 0x40, 0x40, 0xc7, 0x6d, 0x54, 0x9b, 0x55, 0x47, 0x6a, 0xc5, 0xab,
	0x7a, 0x11, 0x17, 0xd5, 0xc6, 0x1d, 0x8c, 0x70, 0xcf, 0x66, 0x9f, 0x60, 0x57, 0x27, 0xf9, 0x50,
	0x0a, 0x2f, 0x16, 0x90, 0xd8, 0xcb, 0x9b, 0x8b, 0x71, 0x24, 0x7b, 0x45, 0xd0, 0x33, 0x9b, 0x9d,
	0xc3, 0x9d, 0x34, 0xb1, 0x52, 0x5c, 0xd5, 0xde, 0xfa, 0x0f, 0xed, 0x1a, 0xaa, 0xcd, 0xf7, 0x8c,
	0xc1, 0xe6, 0x40, 0xab, 0x71, 0x03, 0x5c, 0xc7, 0x02, 0x4e, 0x36, 0xfa, 0x4c, 0xf6, 0x43, 0x36,
	0x76, 0xbd, 0x0f, 0x6d, 0xb6, 0xef, 0x7c, 0x4a, 0xdb, 0x46, 0x9d, 0x72, 0xd7, 0xcb, 0xb9, 0x7b,
	0x2e, 0xc6, 0x09, 0x11, 0x7d, 0x06, 0xb8, 0xa2, 0xff, 0x18, 0x60, 0x90, 0xc9, 0x51, 0x2a, 0xf2,
	0x64, 0x2c, 0xe9, 0x46, 0x43, 0x1e, 0x92, 0xa7, 0xeb, 0x1c, 0xec, 0x00, 0x02, 0x3a, 0x99, 0xbb,
	0x31, 0xd4, 0xbd, 0x57, 0xd6, 0x25, 0x25, 0xee, 0x31, 0xd1, 0xef, 0x2a, 0x04, 0x37, 0x52, 0x3d,
	0x87, 0xdb, 0x58, 0x8a, 0xc8, 0x95, 0xa0, 0xa2, 0xfd, 0x73, 0x78, 0xb3, 0xe6, 0xcd, 0xd2, 0xa1,
	0xba, 0x0a, 0xd7, 0xd3, 0x5b, 0x1c, 0xcc, 0x6c, 0xc7, 0xce, 0xa6, 0xe9, 0x49, 0xbd, 0x4a, 0xea,
	0xc7, 0xeb, 0xaa, 0x77, 0x50, 0xa1, 0x10, 0xf7, 0xb5, 0xe3, 0x26, 0x7a, 0x0b, 0x30, 0xcf, 0xcb,
	0x8e, 0x81, 0xf2, 0x0a, 0xa5, 0x53, 0xa9, 0xe9, 0xa0, 0xb5, 0xa3, 0x68, 0x59, 0xf3, 0xe3, 0x0f,
	0x88, 0xe0, 0x21, 0xa2, 0xc9, 0x8c, 0x7e, 0x55, 0x20, 0x9c, 0xe5, 0x58, 0xd5, 0xb1, 0xeb, 0x79,
	0x36, 0xd6, 0xc8, 0xc3, 0x5e, 0x01, 0x6d, 0xc4, 0x58, 0xa5, 0x92, 0x7a, 0x51, 0x5b, 0xfc, 0x78,
	0xc4, 0x7c, 0xef, 0x00, 0x7c, 0x07, 0xb1, 0x68, 0xb5, 0x43, 0xd8, 0x26, 0x5e, 0xff, 0x72, 0xef,
	0x4f, 0x05, 0x76, 0xb8, 0x34, 0x13, 0x95, 0x1b, 0xc9, 0x9e, 0x43, 0x40, 0xe3, 0xa1, 0xf8, 0xfe,
	0x0f, 0xcb, 0x5a, 0x7e, 0x76, 0x9c, 0xe0, 0xca, 0x3d, 0x12, 0x0f, 0x67, 0x95, 0x4d, 0x46, 0xe2,
	0x4b, 0x66, 0x0d, 0x55, 0x1f, 0xf0, 0x90, 0x3c, 0xa7, 0xce, 0xc1, 0x9e, 0xc1, 0x26, 0xce, 0xa2,
	0xe2, 0x83, 0x2f, 0x14, 0x47, 0x73, 0xea, 0x9d, 0x5b, 0x38, 0xc1, 0xd8, 0xe1, 0x74, 0x20, 0x6c,
	0x12, 0x3e, 0x5a, 0x8a, 0xbf, 0xf6, 0xf7, 0x0f, 0xa1, 0x5e, 0x04, 0xfd, 0xfc, 0x11, 0xc6, 0xea,
	0x2c, 0x1f, 0xba, 0x21, 0x80, 0x6d, 0x66, 0x45, 0x8c, 0xc6, 0x4d, 0x8f, 0x22, 0xed, 0x1e, 0xdc,
	0xcf, 0xd4, 0x32, 0xe1, 0xf6, 0xdd, 0x8e, 0x7f, 0x37, 0xdd, 0xd9, 0xbb, 0x39, 0x7b, 0xfa, 0x8f,
	0x51, 0x2e, 0xe6, 0xef, 0xab, 0xbf, 0x45, 0x03, 0xf5, 0xc5, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x44, 0xd1, 0x60, 0x16, 0xfb, 0x05, 0x00, 0x00,
}
