// Code generated by protoc-gen-go.
// source: dstore/engine/procedures/om_GetOrders_Ad.proto
// DO NOT EDIT!

/*
Package om_GetOrders_Ad is a generated protocol buffer package.

It is generated from these files:
	dstore/engine/procedures/om_GetOrders_Ad.proto

It has these top-level messages:
	Parameters
	Response
*/
package om_GetOrders_Ad

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_values "gosdk.dstore.de/values"
import dstore_engine_error "gosdk.dstore.de/engine/error"
import dstore_engine_message "gosdk.dstore.de/engine/message"
import dstore_engine_metainformation "gosdk.dstore.de/engine/metainformation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameters struct {
	FromDate                        *dstore_values.TimestampValue `protobuf:"bytes,1,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	FromDateNull                    bool                          `protobuf:"varint,1001,opt,name=from_date_null,json=fromDateNull" json:"from_date_null,omitempty"`
	ToDate                          *dstore_values.TimestampValue `protobuf:"bytes,2,opt,name=to_date,json=toDate" json:"to_date,omitempty"`
	ToDateNull                      bool                          `protobuf:"varint,1002,opt,name=to_date_null,json=toDateNull" json:"to_date_null,omitempty"`
	PersonTypeId                    *dstore_values.IntegerValue   `protobuf:"bytes,3,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	PersonTypeIdNull                bool                          `protobuf:"varint,1003,opt,name=person_type_id_null,json=personTypeIdNull" json:"person_type_id_null,omitempty"`
	OrderStateList                  *dstore_values.StringValue    `protobuf:"bytes,4,opt,name=order_state_list,json=orderStateList" json:"order_state_list,omitempty"`
	OrderStateListNull              bool                          `protobuf:"varint,1004,opt,name=order_state_list_null,json=orderStateListNull" json:"order_state_list_null,omitempty"`
	SkipOHavingDifferentOStates     *dstore_values.BooleanValue   `protobuf:"bytes,5,opt,name=skip_o_having_different_o_states,json=skipOHavingDifferentOStates" json:"skip_o_having_different_o_states,omitempty"`
	SkipOHavingDifferentOStatesNull bool                          `protobuf:"varint,1005,opt,name=skip_o_having_different_o_states_null,json=skipOHavingDifferentOStatesNull" json:"skip_o_having_different_o_states_null,omitempty"`
	PersonId                        *dstore_values.IntegerValue   `protobuf:"bytes,6,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	PersonIdNull                    bool                          `protobuf:"varint,1006,opt,name=person_id_null,json=personIdNull" json:"person_id_null,omitempty"`
	OrderId                         *dstore_values.IntegerValue   `protobuf:"bytes,7,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	OrderIdNull                     bool                          `protobuf:"varint,1007,opt,name=order_id_null,json=orderIdNull" json:"order_id_null,omitempty"`
	Rowcount                        *dstore_values.IntegerValue   `protobuf:"bytes,8,opt,name=rowcount" json:"rowcount,omitempty"`
	RowcountNull                    bool                          `protobuf:"varint,1008,opt,name=rowcount_null,json=rowcountNull" json:"rowcount_null,omitempty"`
	LanguageId                      *dstore_values.IntegerValue   `protobuf:"bytes,9,opt,name=language_id,json=languageId" json:"language_id,omitempty"`
	LanguageIdNull                  bool                          `protobuf:"varint,1009,opt,name=language_id_null,json=languageIdNull" json:"language_id_null,omitempty"`
	DateAndTimeFormat               *dstore_values.IntegerValue   `protobuf:"bytes,10,opt,name=date_and_time_format,json=dateAndTimeFormat" json:"date_and_time_format,omitempty"`
	DateAndTimeFormatNull           bool                          `protobuf:"varint,1010,opt,name=date_and_time_format_null,json=dateAndTimeFormatNull" json:"date_and_time_format_null,omitempty"`
	IncludeTime                     *dstore_values.BooleanValue   `protobuf:"bytes,11,opt,name=include_time,json=includeTime" json:"include_time,omitempty"`
	IncludeTimeNull                 bool                          `protobuf:"varint,1011,opt,name=include_time_null,json=includeTimeNull" json:"include_time_null,omitempty"`
	IncludeItemNo                   *dstore_values.BooleanValue   `protobuf:"bytes,12,opt,name=include_item_no,json=includeItemNo" json:"include_item_no,omitempty"`
	IncludeItemNoNull               bool                          `protobuf:"varint,1012,opt,name=include_item_no_null,json=includeItemNoNull" json:"include_item_no_null,omitempty"`
	ShowPersonCharacteristics       *dstore_values.BooleanValue   `protobuf:"bytes,13,opt,name=show_person_characteristics,json=showPersonCharacteristics" json:"show_person_characteristics,omitempty"`
	ShowPersonCharacteristicsNull   bool                          `protobuf:"varint,1013,opt,name=show_person_characteristics_null,json=showPersonCharacteristicsNull" json:"show_person_characteristics_null,omitempty"`
	OrderDesc                       *dstore_values.BooleanValue   `protobuf:"bytes,14,opt,name=order_desc,json=orderDesc" json:"order_desc,omitempty"`
	OrderDescNull                   bool                          `protobuf:"varint,1014,opt,name=order_desc_null,json=orderDescNull" json:"order_desc_null,omitempty"`
	NodeCharacteristicId            *dstore_values.IntegerValue   `protobuf:"bytes,15,opt,name=node_characteristic_id,json=nodeCharacteristicId" json:"node_characteristic_id,omitempty"`
	NodeCharacteristicIdNull        bool                          `protobuf:"varint,1015,opt,name=node_characteristic_id_null,json=nodeCharacteristicIdNull" json:"node_characteristic_id_null,omitempty"`
	GetInfoForValidOrderContent     *dstore_values.BooleanValue   `protobuf:"bytes,16,opt,name=get_info_for_valid_order_content,json=getInfoForValidOrderContent" json:"get_info_for_valid_order_content,omitempty"`
	GetInfoForValidOrderContentNull bool                          `protobuf:"varint,1016,opt,name=get_info_for_valid_order_content_null,json=getInfoForValidOrderContentNull" json:"get_info_for_valid_order_content_null,omitempty"`
	ConvertResultToCurrencyId       *dstore_values.IntegerValue   `protobuf:"bytes,17,opt,name=convert_result_to_currency_id,json=convertResultToCurrencyId" json:"convert_result_to_currency_id,omitempty"`
	ConvertResultToCurrencyIdNull   bool                          `protobuf:"varint,1017,opt,name=convert_result_to_currency_id_null,json=convertResultToCurrencyIdNull" json:"convert_result_to_currency_id_null,omitempty"`
	PurchaseOrder                   *dstore_values.BooleanValue   `protobuf:"bytes,18,opt,name=purchase_order,json=purchaseOrder" json:"purchase_order,omitempty"`
	PurchaseOrderNull               bool                          `protobuf:"varint,1018,opt,name=purchase_order_null,json=purchaseOrderNull" json:"purchase_order_null,omitempty"`
	GetComputedSum                  *dstore_values.BooleanValue   `protobuf:"bytes,19,opt,name=get_computed_sum,json=getComputedSum" json:"get_computed_sum,omitempty"`
	GetComputedSumNull              bool                          `protobuf:"varint,1019,opt,name=get_computed_sum_null,json=getComputedSumNull" json:"get_computed_sum_null,omitempty"`
	OnlyValidPosForComputedSum      *dstore_values.BooleanValue   `protobuf:"bytes,20,opt,name=only_valid_pos_for_computed_sum,json=onlyValidPosForComputedSum" json:"only_valid_pos_for_computed_sum,omitempty"`
	OnlyValidPosForComputedSumNull  bool                          `protobuf:"varint,1020,opt,name=only_valid_pos_for_computed_sum_null,json=onlyValidPosForComputedSumNull" json:"only_valid_pos_for_computed_sum_null,omitempty"`
	OrderSurchIdsForComputedSum     *dstore_values.StringValue    `protobuf:"bytes,21,opt,name=order_surch_ids_for_computed_sum,json=orderSurchIdsForComputedSum" json:"order_surch_ids_for_computed_sum,omitempty"`
	OrderSurchIdsForComputedSumNull bool                          `protobuf:"varint,1021,opt,name=order_surch_ids_for_computed_sum_null,json=orderSurchIdsForComputedSumNull" json:"order_surch_ids_for_computed_sum_null,omitempty"`
}

func (m *Parameters) Reset()                    { *m = Parameters{} }
func (m *Parameters) String() string            { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()               {}
func (*Parameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameters) GetFromDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *Parameters) GetToDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.ToDate
	}
	return nil
}

func (m *Parameters) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Parameters) GetOrderStateList() *dstore_values.StringValue {
	if m != nil {
		return m.OrderStateList
	}
	return nil
}

func (m *Parameters) GetSkipOHavingDifferentOStates() *dstore_values.BooleanValue {
	if m != nil {
		return m.SkipOHavingDifferentOStates
	}
	return nil
}

func (m *Parameters) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Parameters) GetOrderId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Parameters) GetRowcount() *dstore_values.IntegerValue {
	if m != nil {
		return m.Rowcount
	}
	return nil
}

func (m *Parameters) GetLanguageId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LanguageId
	}
	return nil
}

func (m *Parameters) GetDateAndTimeFormat() *dstore_values.IntegerValue {
	if m != nil {
		return m.DateAndTimeFormat
	}
	return nil
}

func (m *Parameters) GetIncludeTime() *dstore_values.BooleanValue {
	if m != nil {
		return m.IncludeTime
	}
	return nil
}

func (m *Parameters) GetIncludeItemNo() *dstore_values.BooleanValue {
	if m != nil {
		return m.IncludeItemNo
	}
	return nil
}

func (m *Parameters) GetShowPersonCharacteristics() *dstore_values.BooleanValue {
	if m != nil {
		return m.ShowPersonCharacteristics
	}
	return nil
}

func (m *Parameters) GetOrderDesc() *dstore_values.BooleanValue {
	if m != nil {
		return m.OrderDesc
	}
	return nil
}

func (m *Parameters) GetNodeCharacteristicId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeCharacteristicId
	}
	return nil
}

func (m *Parameters) GetGetInfoForValidOrderContent() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetInfoForValidOrderContent
	}
	return nil
}

func (m *Parameters) GetConvertResultToCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ConvertResultToCurrencyId
	}
	return nil
}

func (m *Parameters) GetPurchaseOrder() *dstore_values.BooleanValue {
	if m != nil {
		return m.PurchaseOrder
	}
	return nil
}

func (m *Parameters) GetGetComputedSum() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetComputedSum
	}
	return nil
}

func (m *Parameters) GetOnlyValidPosForComputedSum() *dstore_values.BooleanValue {
	if m != nil {
		return m.OnlyValidPosForComputedSum
	}
	return nil
}

func (m *Parameters) GetOrderSurchIdsForComputedSum() *dstore_values.StringValue {
	if m != nil {
		return m.OrderSurchIdsForComputedSum
	}
	return nil
}

type Response struct {
	Error           *dstore_engine_error.Error                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	MetaInformation []*dstore_engine_metainformation.MetaInformation `protobuf:"bytes,2,rep,name=meta_information,json=metaInformation" json:"meta_information,omitempty"`
	Message         []*dstore_engine_message.Message                 `protobuf:"bytes,3,rep,name=message" json:"message,omitempty"`
	Row             []*Response_Row                                  `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_engine_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetMetaInformation() []*dstore_engine_metainformation.MetaInformation {
	if m != nil {
		return m.MetaInformation
	}
	return nil
}

func (m *Response) GetMessage() []*dstore_engine_message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetRow() []*Response_Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type Response_Row struct {
	RowId                        int32                       `protobuf:"varint,10000,opt,name=row_id,json=rowId" json:"row_id,omitempty"`
	OrderDateAndTime             *dstore_values.StringValue  `protobuf:"bytes,10001,opt,name=order_date_and_time,json=orderDateAndTime" json:"order_date_and_time,omitempty"`
	PaymentCost                  *dstore_values.DecimalValue `protobuf:"bytes,10002,opt,name=payment_cost,json=paymentCost" json:"payment_cost,omitempty"`
	DeliveryDateAndTime          *dstore_values.StringValue  `protobuf:"bytes,10003,opt,name=delivery_date_and_time,json=deliveryDateAndTime" json:"delivery_date_and_time,omitempty"`
	NetShippingCost              *dstore_values.DecimalValue `protobuf:"bytes,10004,opt,name=net_shipping_cost,json=netShippingCost" json:"net_shipping_cost,omitempty"`
	OrderNo                      *dstore_values.StringValue  `protobuf:"bytes,10005,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	NettoSum                     *dstore_values.DecimalValue `protobuf:"bytes,10006,opt,name=netto_sum,json=nettoSum" json:"netto_sum,omitempty"`
	LastEditedByUserId           *dstore_values.IntegerValue `protobuf:"bytes,10007,opt,name=last_edited_by_user_id,json=lastEditedByUserId" json:"last_edited_by_user_id,omitempty"`
	OrderId                      *dstore_values.IntegerValue `protobuf:"bytes,10008,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	BruttoSum                    *dstore_values.DecimalValue `protobuf:"bytes,10009,opt,name=brutto_sum,json=bruttoSum" json:"brutto_sum,omitempty"`
	PreciseNetShippingCost       *dstore_values.DecimalValue `protobuf:"bytes,10010,opt,name=precise_net_shipping_cost,json=preciseNetShippingCost" json:"precise_net_shipping_cost,omitempty"`
	CharacVal2RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10011,opt,name=charac_val2_restr_by_pattern,json=characVal2RestrByPattern" json:"charac_val2_restr_by_pattern,omitempty"`
	NetSum                       *dstore_values.DecimalValue `protobuf:"bytes,10012,opt,name=net_sum,json=netSum" json:"net_sum,omitempty"`
	PersonId                     *dstore_values.IntegerValue `protobuf:"bytes,10013,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	PaymentTypeDescription       *dstore_values.StringValue  `protobuf:"bytes,10014,opt,name=payment_type_description,json=paymentTypeDescription" json:"payment_type_description,omitempty"`
	PreciseNetSum                *dstore_values.DecimalValue `protobuf:"bytes,10015,opt,name=precise_net_sum,json=preciseNetSum" json:"precise_net_sum,omitempty"`
	PositionCount                *dstore_values.IntegerValue `protobuf:"bytes,10016,opt,name=position_count,json=positionCount" json:"position_count,omitempty"`
	OrderStateId                 *dstore_values.IntegerValue `protobuf:"bytes,10017,opt,name=order_state_id,json=orderStateId" json:"order_state_id,omitempty"`
	ShippingTypeId               *dstore_values.IntegerValue `protobuf:"bytes,10018,opt,name=shipping_type_id,json=shippingTypeId" json:"shipping_type_id,omitempty"`
	PersonTypeId                 *dstore_values.IntegerValue `protobuf:"bytes,10019,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	GrossPaymentCost             *dstore_values.DecimalValue `protobuf:"bytes,10020,opt,name=gross_payment_cost,json=grossPaymentCost" json:"gross_payment_cost,omitempty"`
	NetPaymentCost               *dstore_values.DecimalValue `protobuf:"bytes,10021,opt,name=net_payment_cost,json=netPaymentCost" json:"net_payment_cost,omitempty"`
	DeliveryPersonId             *dstore_values.IntegerValue `protobuf:"bytes,10022,opt,name=delivery_person_id,json=deliveryPersonId" json:"delivery_person_id,omitempty"`
	ShippingTypeDescription      *dstore_values.StringValue  `protobuf:"bytes,10023,opt,name=shipping_type_description,json=shippingTypeDescription" json:"shipping_type_description,omitempty"`
	GrossShippingCost            *dstore_values.DecimalValue `protobuf:"bytes,10024,opt,name=gross_shipping_cost,json=grossShippingCost" json:"gross_shipping_cost,omitempty"`
	GrossSum                     *dstore_values.DecimalValue `protobuf:"bytes,10025,opt,name=gross_sum,json=grossSum" json:"gross_sum,omitempty"`
	UnitSymbol                   *dstore_values.StringValue  `protobuf:"bytes,10026,opt,name=unit_symbol,json=unitSymbol" json:"unit_symbol,omitempty"`
	PreciseNetPaymentCost        *dstore_values.DecimalValue `protobuf:"bytes,10027,opt,name=precise_net_payment_cost,json=preciseNetPaymentCost" json:"precise_net_payment_cost,omitempty"`
	CustomerCharacteristicValue2 *dstore_values.StringValue  `protobuf:"bytes,10028,opt,name=customer_characteristic_value2,json=customerCharacteristicValue2" json:"customer_characteristic_value2,omitempty"`
	PublicDescription            *dstore_values.StringValue  `protobuf:"bytes,10029,opt,name=public_description,json=publicDescription" json:"public_description,omitempty"`
	CurrencyId                   *dstore_values.IntegerValue `protobuf:"bytes,10030,opt,name=currency_id,json=currencyId" json:"currency_id,omitempty"`
	CustomerCharacteristicValue1 *dstore_values.StringValue  `protobuf:"bytes,10031,opt,name=customer_characteristic_value1,json=customerCharacteristicValue1" json:"customer_characteristic_value1,omitempty"`
	PreciseGrossSum              *dstore_values.DecimalValue `protobuf:"bytes,10032,opt,name=precise_gross_sum,json=preciseGrossSum" json:"precise_gross_sum,omitempty"`
	ShippingCost                 *dstore_values.DecimalValue `protobuf:"bytes,10033,opt,name=shipping_cost,json=shippingCost" json:"shipping_cost,omitempty"`
	CharacVal1RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10034,opt,name=charac_val1_restr_by_pattern,json=characVal1RestrByPattern" json:"charac_val1_restr_by_pattern,omitempty"`
	PaymentTypeId                *dstore_values.IntegerValue `protobuf:"bytes,10035,opt,name=payment_type_id,json=paymentTypeId" json:"payment_type_id,omitempty"`
	OrderState                   *dstore_values.StringValue  `protobuf:"bytes,10036,opt,name=order_state,json=orderState" json:"order_state,omitempty"`
	ValidContentNetSum           *dstore_values.DecimalValue `protobuf:"bytes,20013,opt,name=valid_content_net_sum,json=validContentNetSum" json:"valid_content_net_sum,omitempty"`
	PreciseValidContentNetSum    *dstore_values.DecimalValue `protobuf:"bytes,20014,opt,name=precise_valid_content_net_sum,json=preciseValidContentNetSum" json:"precise_valid_content_net_sum,omitempty"`
	ValidContentBruttoSum        *dstore_values.DecimalValue `protobuf:"bytes,20017,opt,name=valid_content_brutto_sum,json=validContentBruttoSum" json:"valid_content_brutto_sum,omitempty"`
	HasValidContents             *dstore_values.BooleanValue `protobuf:"bytes,20024,opt,name=has_valid_contents,json=hasValidContents" json:"has_valid_contents,omitempty"`
	ValidContentNettoSum         *dstore_values.DecimalValue `protobuf:"bytes,20037,opt,name=valid_content_netto_sum,json=validContentNettoSum" json:"valid_content_netto_sum,omitempty"`
	PreciseValidContentGrossSum  *dstore_values.DecimalValue `protobuf:"bytes,20041,opt,name=precise_valid_content_gross_sum,json=preciseValidContentGrossSum" json:"precise_valid_content_gross_sum,omitempty"`
	ValidContentGrossSum         *dstore_values.DecimalValue `protobuf:"bytes,20043,opt,name=valid_content_gross_sum,json=validContentGrossSum" json:"valid_content_gross_sum,omitempty"`
	Description                  *dstore_values.StringValue  `protobuf:"bytes,30004,opt,name=description" json:"description,omitempty"`
	PreciseNetContentSum         *dstore_values.DecimalValue `protobuf:"bytes,30005,opt,name=precise_net_content_sum,json=preciseNetContentSum" json:"precise_net_content_sum,omitempty"`
	OrderContentNo               *dstore_values.StringValue  `protobuf:"bytes,30007,opt,name=order_content_no,json=orderContentNo" json:"order_content_no,omitempty"`
	OrderContentId               *dstore_values.IntegerValue `protobuf:"bytes,30010,opt,name=order_content_id,json=orderContentId" json:"order_content_id,omitempty"`
	CurrencySymbol               *dstore_values.StringValue  `protobuf:"bytes,30012,opt,name=currency_symbol,json=currencySymbol" json:"currency_symbol,omitempty"`
	NettoContentSum              *dstore_values.DecimalValue `protobuf:"bytes,30014,opt,name=netto_content_sum,json=nettoContentSum" json:"netto_content_sum,omitempty"`
	OrderContentPosition         *dstore_values.IntegerValue `protobuf:"bytes,30017,opt,name=order_content_position,json=orderContentPosition" json:"order_content_position,omitempty"`
	NetContentSum                *dstore_values.DecimalValue `protobuf:"bytes,30018,opt,name=net_content_sum,json=netContentSum" json:"net_content_sum,omitempty"`
	NodeId                       *dstore_values.IntegerValue `protobuf:"bytes,30019,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	GrossContentSum              *dstore_values.DecimalValue `protobuf:"bytes,30020,opt,name=gross_content_sum,json=grossContentSum" json:"gross_content_sum,omitempty"`
	PreciseGrossOrderSum         *dstore_values.DecimalValue `protobuf:"bytes,30023,opt,name=precise_gross_order_sum,json=preciseGrossOrderSum" json:"precise_gross_order_sum,omitempty"`
	PreciseGrossContentSum       *dstore_values.DecimalValue `protobuf:"bytes,30024,opt,name=precise_gross_content_sum,json=preciseGrossContentSum" json:"precise_gross_content_sum,omitempty"`
	GrossOrderSum                *dstore_values.DecimalValue `protobuf:"bytes,30026,opt,name=gross_order_sum,json=grossOrderSum" json:"gross_order_sum,omitempty"`
	OrderContentWasModified      *dstore_values.BooleanValue `protobuf:"bytes,30028,opt,name=order_content_was_modified,json=orderContentWasModified" json:"order_content_was_modified,omitempty"`
	ItemProperty                 *dstore_values.StringValue  `protobuf:"bytes,30029,opt,name=item_property,json=itemProperty" json:"item_property,omitempty"`
	Quantity                     *dstore_values.IntegerValue `protobuf:"bytes,30032,opt,name=quantity" json:"quantity,omitempty"`
	NetOrderSum                  *dstore_values.DecimalValue `protobuf:"bytes,30036,opt,name=net_order_sum,json=netOrderSum" json:"net_order_sum,omitempty"`
	BruttoContentSum             *dstore_values.DecimalValue `protobuf:"bytes,30040,opt,name=brutto_content_sum,json=bruttoContentSum" json:"brutto_content_sum,omitempty"`
	NettoOrderSum                *dstore_values.DecimalValue `protobuf:"bytes,30041,opt,name=netto_order_sum,json=nettoOrderSum" json:"netto_order_sum,omitempty"`
	ItemNo                       *dstore_values.StringValue  `protobuf:"bytes,30042,opt,name=item_no,json=itemNo" json:"item_no,omitempty"`
	PreciseNetOrderSum           *dstore_values.DecimalValue `protobuf:"bytes,30046,opt,name=precise_net_order_sum,json=preciseNetOrderSum" json:"precise_net_order_sum,omitempty"`
	BruttoOrderSum               *dstore_values.DecimalValue `protobuf:"bytes,30048,opt,name=brutto_order_sum,json=bruttoOrderSum" json:"brutto_order_sum,omitempty"`
	PreciseComputedGrossSum      *dstore_values.DecimalValue `protobuf:"bytes,40020,opt,name=precise_computed_gross_sum,json=preciseComputedGrossSum" json:"precise_computed_gross_sum,omitempty"`
	ComputedGrossSum             *dstore_values.DecimalValue `protobuf:"bytes,40034,opt,name=computed_gross_sum,json=computedGrossSum" json:"computed_gross_sum,omitempty"`
	PreciseComputedNetSum        *dstore_values.DecimalValue `protobuf:"bytes,40038,opt,name=precise_computed_net_sum,json=preciseComputedNetSum" json:"precise_computed_net_sum,omitempty"`
	ComputedNetSum               *dstore_values.DecimalValue `protobuf:"bytes,40040,opt,name=computed_net_sum,json=computedNetSum" json:"computed_net_sum,omitempty"`
}

func (m *Response_Row) Reset()                    { *m = Response_Row{} }
func (m *Response_Row) String() string            { return proto.CompactTextString(m) }
func (*Response_Row) ProtoMessage()               {}
func (*Response_Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Row) GetOrderDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.OrderDateAndTime
	}
	return nil
}

func (m *Response_Row) GetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.DeliveryDateAndTime
	}
	return nil
}

func (m *Response_Row) GetNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetShippingCost
	}
	return nil
}

func (m *Response_Row) GetOrderNo() *dstore_values.StringValue {
	if m != nil {
		return m.OrderNo
	}
	return nil
}

func (m *Response_Row) GetNettoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoSum
	}
	return nil
}

func (m *Response_Row) GetLastEditedByUserId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LastEditedByUserId
	}
	return nil
}

func (m *Response_Row) GetOrderId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Response_Row) GetBruttoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoSum
	}
	return nil
}

func (m *Response_Row) GetPreciseNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal2RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal2RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetSum
	}
	return nil
}

func (m *Response_Row) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PaymentTypeDescription
	}
	return nil
}

func (m *Response_Row) GetPreciseNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetSum
	}
	return nil
}

func (m *Response_Row) GetPositionCount() *dstore_values.IntegerValue {
	if m != nil {
		return m.PositionCount
	}
	return nil
}

func (m *Response_Row) GetOrderStateId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderStateId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ShippingTypeId
	}
	return nil
}

func (m *Response_Row) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Response_Row) GetGrossPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossPaymentCost
	}
	return nil
}

func (m *Response_Row) GetNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.DeliveryPersonId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ShippingTypeDescription
	}
	return nil
}

func (m *Response_Row) GetGrossShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossShippingCost
	}
	return nil
}

func (m *Response_Row) GetGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossSum
	}
	return nil
}

func (m *Response_Row) GetUnitSymbol() *dstore_values.StringValue {
	if m != nil {
		return m.UnitSymbol
	}
	return nil
}

func (m *Response_Row) GetPreciseNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue2() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue2
	}
	return nil
}

func (m *Response_Row) GetPublicDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PublicDescription
	}
	return nil
}

func (m *Response_Row) GetCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.CurrencyId
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue1() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue1
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossSum
	}
	return nil
}

func (m *Response_Row) GetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.ShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal1RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal1RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PaymentTypeId
	}
	return nil
}

func (m *Response_Row) GetOrderState() *dstore_values.StringValue {
	if m != nil {
		return m.OrderState
	}
	return nil
}

func (m *Response_Row) GetValidContentNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentNetSum
	}
	return nil
}

func (m *Response_Row) GetPreciseValidContentNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseValidContentNetSum
	}
	return nil
}

func (m *Response_Row) GetValidContentBruttoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentBruttoSum
	}
	return nil
}

func (m *Response_Row) GetHasValidContents() *dstore_values.BooleanValue {
	if m != nil {
		return m.HasValidContents
	}
	return nil
}

func (m *Response_Row) GetValidContentNettoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentNettoSum
	}
	return nil
}

func (m *Response_Row) GetPreciseValidContentGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseValidContentGrossSum
	}
	return nil
}

func (m *Response_Row) GetValidContentGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentGrossSum
	}
	return nil
}

func (m *Response_Row) GetDescription() *dstore_values.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Response_Row) GetPreciseNetContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetContentSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentNo() *dstore_values.StringValue {
	if m != nil {
		return m.OrderContentNo
	}
	return nil
}

func (m *Response_Row) GetOrderContentId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderContentId
	}
	return nil
}

func (m *Response_Row) GetCurrencySymbol() *dstore_values.StringValue {
	if m != nil {
		return m.CurrencySymbol
	}
	return nil
}

func (m *Response_Row) GetNettoContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoContentSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentPosition() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderContentPosition
	}
	return nil
}

func (m *Response_Row) GetNetContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetContentSum
	}
	return nil
}

func (m *Response_Row) GetNodeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *Response_Row) GetGrossContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossContentSum
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossOrderSum
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossContentSum
	}
	return nil
}

func (m *Response_Row) GetGrossOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossOrderSum
	}
	return nil
}

func (m *Response_Row) GetOrderContentWasModified() *dstore_values.BooleanValue {
	if m != nil {
		return m.OrderContentWasModified
	}
	return nil
}

func (m *Response_Row) GetItemProperty() *dstore_values.StringValue {
	if m != nil {
		return m.ItemProperty
	}
	return nil
}

func (m *Response_Row) GetQuantity() *dstore_values.IntegerValue {
	if m != nil {
		return m.Quantity
	}
	return nil
}

func (m *Response_Row) GetNetOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetOrderSum
	}
	return nil
}

func (m *Response_Row) GetBruttoContentSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoContentSum
	}
	return nil
}

func (m *Response_Row) GetNettoOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoOrderSum
	}
	return nil
}

func (m *Response_Row) GetItemNo() *dstore_values.StringValue {
	if m != nil {
		return m.ItemNo
	}
	return nil
}

func (m *Response_Row) GetPreciseNetOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetOrderSum
	}
	return nil
}

func (m *Response_Row) GetBruttoOrderSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoOrderSum
	}
	return nil
}

func (m *Response_Row) GetPreciseComputedGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseComputedGrossSum
	}
	return nil
}

func (m *Response_Row) GetComputedGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ComputedGrossSum
	}
	return nil
}

func (m *Response_Row) GetPreciseComputedNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseComputedNetSum
	}
	return nil
}

func (m *Response_Row) GetComputedNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ComputedNetSum
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "dstore.engine.om_GetOrders_Ad.Parameters")
	proto.RegisterType((*Response)(nil), "dstore.engine.om_GetOrders_Ad.Response")
	proto.RegisterType((*Response_Row)(nil), "dstore.engine.om_GetOrders_Ad.Response.Row")
}

func init() { proto.RegisterFile("dstore/engine/procedures/om_GetOrders_Ad.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x5a, 0xd9, 0x6f, 0x24, 0x47,
	0x19, 0xd7, 0x66, 0x59, 0x1f, 0x65, 0x7b, 0x3c, 0x6e, 0x1f, 0xdb, 0xb6, 0xe3, 0xdd, 0x65, 0x93,
	0x15, 0x41, 0x2b, 0xcd, 0x62, 0x23, 0x12, 0x36, 0x90, 0x45, 0x6b, 0x7b, 0x0f, 0x87, 0xdd, 0xf1,
	0x30, 0xde, 0x38, 0x90, 0x08, 0x35, 0xed, 0xee, 0xf6, 0x6c, 0x2b, 0x33, 0x5d, 0x43, 0x1f, 0xbb,
	0x9a, 0x3f, 0x81, 0x37, 0xee, 0x33, 0xdc, 0xf7, 0x91, 0x40, 0x48, 0x10, 0x11, 0x42, 0x48, 0x5c,
	0xe2, 0x96, 0x78, 0xc8, 0x03, 0xf0, 0x80, 0x10, 0x0f, 0x08, 0x96, 0xfb, 0x5a, 0x6e, 0x89, 0xaf,
	0xea, 0xab, 0xea, 0xae, 0xee, 0x19, 0xbb, 0xcb, 0xca, 0x4b, 0xb2, 0x33, 0x5d, 0xbf, 0xdf, 0xf7,
	0xab, 0xef, 0xaa, 0xaf, 0xda, 0x43, 0x6a, 0x6e, 0x14, 0xd3, 0xd0, 0x3b, 0xe3, 0x05, 0x2d, 0x3f,
	0xf0, 0xce, 0x74, 0x43, 0xea, 0x78, 0x6e, 0x12, 0x7a, 0xd1, 0x19, 0xda, 0xb1, 0x2e, 0x79, 0xf1,
	0x66, 0xe8, 0x7a, 0x61, 0x64, 0x9d, 0x77, 0x6b, 0xf0, 0x28, 0xa6, 0xc6, 0x12, 0xae, 0xaf, 0xe1,
	0xfa, 0x5a, 0x61, 0xd1, 0xc2, 0xb4, 0xa0, 0xbb, 0x61, 0xb7, 0x13, 0x2f, 0x42, 0xcc, 0xc2, 0x7c,
	0xde, 0x86, 0x17, 0x86, 0x34, 0x14, 0x8f, 0x16, 0xf3, 0x8f, 0x3a, 0x5e, 0x14, 0xd9, 0x2d, 0x4f,
	0x3c, 0xbc, 0xab, 0xf8, 0x30, 0xb6, 0xfd, 0x60, 0x97, 0x86, 0x1d, 0x3b, 0xf6, 0x69, 0x80, 0x8b,
	0x4e, 0x3e, 0x3d, 0x4b, 0x48, 0xc3, 0x0e, 0x6d, 0x78, 0x0a, 0x1a, 0x8c, 0xfb, 0xc9, 0xe8, 0x6e,
	0x08, 0xaa, 0x5c, 0x3b, 0xf6, 0xcc, 0x43, 0x27, 0x0e, 0xdd, 0x33, 0xb6, 0xb2, 0x24, 0xf6, 0x58,
	0x13, 0xa2, 0x62, 0x1f, 0xcc, 0xc4, 0x76, 0xa7, 0xbb, 0xcd, 0x3e, 0x37, 0x47, 0xd8, 0xfa, 0x75,
	0x58, 0x6e, 0x9c, 0x22, 0x95, 0x14, 0x6b, 0x05, 0x49, 0xbb, 0x6d, 0xfe, 0x66, 0x18, 0x18, 0x46,
	0x9a, 0xe3, 0x72, 0x49, 0x1d, 0xbe, 0x34, 0xee, 0x25, 0xc3, 0x31, 0x45, 0x03, 0x77, 0xe8, 0x18,
	0x18, 0x8a, 0x29, 0xa7, 0x7f, 0x21, 0x19, 0x17, 0x38, 0x24, 0xbf, 0x85, 0xe4, 0x04, 0x1f, 0x73,
	0xea, 0xf3, 0xa4, 0xd2, 0x85, 0x5d, 0xd0, 0xc0, 0x8a, 0x7b, 0x5d, 0xcf, 0xf2, 0x5d, 0xf3, 0x30,
	0xb7, 0xb0, 0x58, 0xb0, 0xe0, 0x07, 0xb1, 0xd7, 0xf2, 0x42, 0xe4, 0x1f, 0x47, 0xc8, 0x35, 0x40,
	0x6c, 0xb8, 0x46, 0x8d, 0x4c, 0xe7, 0x29, 0xd0, 0xd8, 0x6f, 0xd1, 0x58, 0x55, 0x5d, 0xcb, 0x4d,
	0xae, 0x93, 0x2a, 0x65, 0xe1, 0xb3, 0x40, 0x31, 0x28, 0x6b, 0xfb, 0x51, 0x6c, 0xbe, 0x80, 0x1b,
	0x5d, 0x28, 0x18, 0x8d, 0xe2, 0xd0, 0x0f, 0x5a, 0x68, 0xb3, 0xc2, 0x31, 0x5b, 0x0c, 0x72, 0x05,
	0x10, 0xc6, 0x0a, 0x99, 0x2d, 0xb2, 0xa0, 0xdd, 0xdf, 0xa1, 0x5d, 0x23, 0xbf, 0x9e, 0x5b, 0xde,
	0x21, 0x27, 0xa2, 0xc7, 0xfc, 0xae, 0x45, 0xad, 0xeb, 0xf6, 0x0d, 0x60, 0xb6, 0x5c, 0x7f, 0x77,
	0xd7, 0x0b, 0xbd, 0x20, 0x86, 0xaf, 0x38, 0x4f, 0x64, 0x1e, 0x19, 0xb8, 0xfd, 0x1d, 0x4a, 0xdb,
	0x9e, 0x1d, 0xa0, 0x94, 0x45, 0x46, 0xb2, 0x79, 0x99, 0x53, 0xac, 0x4b, 0x86, 0x4d, 0x6e, 0x2a,
	0x32, 0x36, 0xc9, 0xa9, 0x32, 0x1b, 0xa8, 0xf3, 0xf7, 0xa8, 0xf3, 0xf8, 0x3e, 0x64, 0x5c, 0xf4,
	0xcb, 0xc9, 0xa8, 0x70, 0x2f, 0x04, 0x67, 0xa8, 0x3c, 0x38, 0x23, 0xb8, 0x1a, 0x02, 0x73, 0x2a,
	0x8d, 0xad, 0x8c, 0xc9, 0x1f, 0x44, 0x76, 0xc9, 0x25, 0x22, 0xbb, 0x46, 0xd0, 0x93, 0xc0, 0x3f,
	0x5c, 0xce, 0x3f, 0xcc, 0x17, 0x03, 0xfd, 0x5d, 0x64, 0x42, 0xe2, 0x90, 0xfd, 0x8f, 0xc8, 0x3e,
	0x26, 0x16, 0x70, 0xf2, 0xfb, 0xc8, 0x48, 0x48, 0x6f, 0x3a, 0x34, 0x09, 0x62, 0x73, 0x44, 0x43,
	0xbc, 0x5c, 0x6c, 0xdc, 0x4d, 0x26, 0xe4, 0xbf, 0x91, 0xfd, 0x4f, 0x42, 0xbb, 0xfc, 0x96, 0xd3,
	0xbf, 0x92, 0x8c, 0xb5, 0xed, 0xa0, 0x95, 0x40, 0x09, 0x33, 0xf9, 0xa3, 0xe5, 0x16, 0x88, 0x5c,
	0x0f, 0x3b, 0x78, 0x31, 0xa9, 0x2a, 0x68, 0x34, 0xf3, 0x67, 0x34, 0x53, 0xc9, 0x96, 0x71, 0x43,
	0x57, 0xc8, 0x0c, 0xaf, 0x23, 0x3b, 0x70, 0x2d, 0x56, 0x6d, 0x16, 0x76, 0x05, 0x93, 0x94, 0x5b,
	0x9c, 0x62, 0xc0, 0xf3, 0x81, 0x7b, 0x0d, 0x60, 0x17, 0x39, 0xca, 0x38, 0x4b, 0xe6, 0x07, 0xb1,
	0xa1, 0x82, 0xbf, 0xa0, 0x82, 0xd9, 0x3e, 0x18, 0x17, 0x72, 0x8e, 0x8c, 0xfb, 0x81, 0xd3, 0x4e,
	0x5c, 0x8f, 0x23, 0xcd, 0xb1, 0xf2, 0x7c, 0x1d, 0x13, 0x00, 0xc6, 0x64, 0x9c, 0x26, 0x53, 0x2a,
	0x1e, 0x4d, 0xfe, 0x15, 0x4d, 0x4e, 0x2a, 0x0b, 0xb9, 0xb1, 0x35, 0x22, 0xbf, 0xb2, 0xfc, 0xd8,
	0xeb, 0x58, 0x01, 0x35, 0xc7, 0xcb, 0xed, 0x4d, 0x08, 0xcc, 0x06, 0x40, 0xea, 0xd4, 0x78, 0x09,
	0x99, 0x29, 0x90, 0xa0, 0xd1, 0xbf, 0xa1, 0xd1, 0xa9, 0xdc, 0x6a, 0x6e, 0xf6, 0x51, 0xb2, 0x18,
	0x5d, 0xa7, 0x37, 0x2d, 0x91, 0xbd, 0xce, 0x75, 0xe8, 0xb6, 0x0e, 0x34, 0x5b, 0xa8, 0x63, 0xdf,
	0x89, 0xcc, 0x89, 0x72, 0x09, 0xf3, 0x0c, 0xdf, 0xe0, 0xf0, 0xb5, 0x3c, 0xda, 0xb8, 0x0c, 0x4d,
	0x60, 0x6f, 0x72, 0x94, 0xf6, 0x77, 0x94, 0xb6, 0xb4, 0x27, 0x0b, 0x97, 0x79, 0x3f, 0x21, 0x58,
	0x00, 0xae, 0x17, 0x39, 0x66, 0xa5, 0x5c, 0xd5, 0x28, 0x5f, 0xbe, 0x0e, 0xab, 0x8d, 0x17, 0x91,
	0xc9, 0x0c, 0x8b, 0x46, 0x6f, 0xa3, 0xd1, 0x89, 0x74, 0x11, 0x37, 0xf2, 0x1a, 0x32, 0x17, 0x50,
	0x70, 0x5d, 0x5e, 0x27, 0x4b, 0xf6, 0xc9, 0xf2, 0xd4, 0x9b, 0x61, 0xd0, 0xbc, 0x74, 0x48, 0xfb,
	0x73, 0x64, 0x71, 0x30, 0x25, 0xea, 0xf8, 0x07, 0xea, 0x30, 0x07, 0x61, 0x65, 0x1b, 0x6d, 0x79,
	0xb1, 0xc5, 0x4e, 0x46, 0x96, 0xb8, 0x16, 0x58, 0x06, 0x2c, 0x6e, 0xc7, 0xa1, 0x60, 0x1f, 0x6a,
	0xbd, 0xaa, 0xd1, 0x46, 0x81, 0x64, 0x03, 0x38, 0x20, 0xb9, 0xb7, 0x19, 0x03, 0x3f, 0xd3, 0xd7,
	0x10, 0xcf, 0xda, 0x68, 0x99, 0x0d, 0x54, 0xfb, 0x4f, 0xd1, 0x46, 0xf7, 0x21, 0xe3, 0xa2, 0x5f,
	0x4f, 0x96, 0x00, 0x77, 0xc3, 0x0b, 0x63, 0x0b, 0x66, 0x8d, 0xa4, 0x1d, 0x5b, 0x70, 0x34, 0x3a,
	0x49, 0x08, 0xed, 0xd6, 0xe9, 0x31, 0x77, 0x4e, 0x95, 0xbb, 0x73, 0x5e, 0x30, 0x34, 0x39, 0xc1,
	0x35, 0xba, 0x26, 0xe0, 0xe0, 0xd3, 0x07, 0xc9, 0xc9, 0x7d, 0xe9, 0x51, 0xec, 0xbf, 0x44, 0x5e,
	0xed, 0xc9, 0xc3, 0xa5, 0xae, 0x42, 0xdf, 0x4e, 0x42, 0x88, 0x4e, 0xe4, 0xe1, 0x8e, 0x4d, 0x43,
	0xa3, 0xe8, 0x24, 0x84, 0xef, 0xdc, 0x38, 0x03, 0x87, 0x72, 0x8e, 0x03, 0x05, 0xfc, 0x5b, 0xd4,
	0x5c, 0x6e, 0x31, 0x37, 0x7a, 0x81, 0x54, 0x99, 0xc3, 0x1d, 0xda, 0xe9, 0x26, 0xb1, 0xe7, 0x5a,
	0x51, 0xd2, 0x31, 0xa7, 0xcb, 0xcd, 0x56, 0x00, 0xb4, 0x26, 0x30, 0x5b, 0x49, 0x87, 0x1d, 0xcb,
	0x45, 0x1a, 0xb4, 0xfc, 0x1f, 0x71, 0x2c, 0xe7, 0xd7, 0x73, 0xd3, 0x6f, 0x20, 0xc7, 0x69, 0xd0,
	0xee, 0x89, 0x18, 0x77, 0x69, 0xc4, 0x23, 0x9e, 0x53, 0x32, 0x53, 0xae, 0x64, 0x81, 0x71, 0xf0,
	0xd8, 0x37, 0x68, 0x04, 0x69, 0xa0, 0xaa, 0xba, 0x4a, 0xee, 0x2e, 0xb1, 0x80, 0x22, 0xff, 0x8b,
	0x22, 0x8f, 0xed, 0x4d, 0xc5, 0x05, 0xdb, 0xe4, 0x84, 0x98, 0x3d, 0x98, 0x1b, 0x21, 0xba, 0x03,
	0x14, 0xcf, 0x96, 0x4e, 0x34, 0x8b, 0x38, 0xa1, 0x30, 0x8a, 0x0d, 0xb7, 0xa8, 0x18, 0xf2, 0xbf,
	0xcc, 0x04, 0x4a, 0xfe, 0x9f, 0xc8, 0xff, 0x7d, 0xc8, 0x98, 0xe6, 0x93, 0x6f, 0x3a, 0x4d, 0x46,
	0x20, 0xdf, 0xba, 0x34, 0x88, 0x3c, 0x68, 0xc9, 0x47, 0xf8, 0x4c, 0x2c, 0xe6, 0xd5, 0x54, 0xa5,
	0x98, 0xb1, 0x71, 0x5e, 0xbe, 0xc0, 0xfe, 0xdb, 0xc4, 0x85, 0xc6, 0xeb, 0x48, 0x95, 0x4d, 0xc3,
	0x96, 0x32, 0x0e, 0xc3, 0x2c, 0x7a, 0x18, 0xc0, 0xb5, 0x02, 0xb8, 0x38, 0x34, 0x5f, 0x85, 0xcf,
	0x1b, 0xd9, 0xe7, 0xe6, 0x64, 0x27, 0xff, 0x05, 0x0c, 0x38, 0xc3, 0x62, 0x0a, 0x87, 0xd9, 0x93,
	0x31, 0x1e, 0xeb, 0x63, 0xc4, 0x19, 0xfd, 0x2a, 0xfe, 0xbf, 0x29, 0x97, 0x1b, 0x0f, 0x90, 0xc3,
	0x30, 0x0d, 0xc0, 0xf0, 0xc8, 0x50, 0xa7, 0x6b, 0xfb, 0x5e, 0x14, 0x6a, 0x72, 0xf3, 0xb5, 0x26,
	0xbd, 0xd9, 0x64, 0xb8, 0x85, 0xdb, 0xf7, 0x90, 0xc3, 0xf0, 0xc1, 0x98, 0x23, 0x43, 0xf0, 0x91,
	0xf5, 0x80, 0x37, 0xd7, 0xc1, 0x1f, 0x47, 0x9a, 0x47, 0xe0, 0x23, 0xaf, 0xe9, 0x69, 0xd1, 0xa3,
	0xd5, 0xb3, 0xda, 0x7c, 0x4b, 0xbd, 0x34, 0xb4, 0x38, 0xe0, 0xae, 0x67, 0x07, 0xb8, 0xf1, 0x2a,
	0x32, 0xde, 0xb5, 0x7b, 0x1d, 0xd6, 0xb6, 0x1c, 0x0a, 0x03, 0xef, 0x5b, 0xeb, 0x03, 0x33, 0xda,
	0xf5, 0x1c, 0xbf, 0x63, 0xb7, 0xc5, 0xb9, 0x2d, 0x10, 0x6b, 0x00, 0x30, 0x1a, 0x64, 0xce, 0xf5,
	0xda, 0x3e, 0xb4, 0x8d, 0x5e, 0x41, 0xcf, 0xdb, 0xca, 0xf5, 0x4c, 0x4b, 0xa8, 0x2a, 0xe9, 0x32,
	0x99, 0x0a, 0xa0, 0x54, 0xa3, 0xeb, 0x7e, 0xb7, 0xcb, 0x06, 0x55, 0xae, 0xeb, 0xed, 0x1a, 0xba,
	0x26, 0x01, 0xb6, 0x25, 0x50, 0x5c, 0x5b, 0x3a, 0x41, 0xc2, 0x7c, 0xf0, 0x8e, 0x72, 0x35, 0x38,
	0x41, 0xc2, 0x64, 0x70, 0x96, 0x8c, 0x02, 0x15, 0x34, 0x4a, 0x56, 0x30, 0xef, 0xd4, 0xb0, 0x3c,
	0xc2, 0x97, 0xb3, 0xfa, 0x00, 0x77, 0xb4, 0x6d, 0x18, 0xf9, 0x3d, 0xd7, 0x67, 0xe5, 0xb0, 0xd3,
	0xb3, 0x92, 0x08, 0x47, 0xd8, 0x77, 0xd5, 0xcb, 0x1b, 0xb9, 0xc1, 0xb0, 0x17, 0x38, 0x74, 0xb5,
	0xf7, 0x50, 0xc4, 0xc7, 0xd9, 0xfb, 0x94, 0x31, 0xf8, 0xdd, 0xf5, 0x03, 0xcc, 0xc1, 0xaf, 0x20,
	0x64, 0x27, 0x4c, 0xe4, 0x36, 0xde, 0xa3, 0xb1, 0x8d, 0x51, 0x5c, 0xcf, 0xf6, 0xf1, 0x30, 0x99,
	0xef, 0x86, 0xf0, 0x0c, 0xda, 0x74, 0x7f, 0x30, 0xde, 0xab, 0xc1, 0x35, 0x27, 0xe0, 0xf5, 0x42,
	0x4c, 0x1e, 0x25, 0x77, 0xe2, 0xf9, 0xce, 0x9a, 0xde, 0x0a, 0x3b, 0x94, 0xe2, 0x90, 0xb9, 0xa9,
	0x6b, 0xc7, 0x70, 0x9c, 0x07, 0xe6, 0xfb, 0xca, 0xe3, 0x64, 0x22, 0x01, 0x7c, 0x58, 0x69, 0x32,
	0xf8, 0x6a, 0xaf, 0x81, 0x60, 0xe3, 0x65, 0x64, 0x98, 0xab, 0x85, 0xfd, 0x3e, 0xae, 0xa1, 0x71,
	0x88, 0x25, 0x0c, 0x6c, 0xf6, 0xac, 0x7a, 0x95, 0x79, 0x7f, 0xfd, 0x20, 0x77, 0x99, 0x87, 0x88,
	0x29, 0xeb, 0x87, 0xdf, 0x32, 0xd9, 0xd8, 0x14, 0xfa, 0x5d, 0xde, 0x87, 0x3e, 0x50, 0xbe, 0x95,
	0x39, 0x01, 0x66, 0xd7, 0xd0, 0xf5, 0x0c, 0x0a, 0x77, 0xd1, 0xc9, 0x9c, 0xfb, 0x61, 0x43, 0x1f,
	0xd4, 0xd8, 0xd0, 0x84, 0xe2, 0x74, 0xd8, 0xd7, 0x1a, 0x1c, 0xd8, 0x34, 0xf2, 0x19, 0xa3, 0x85,
	0x57, 0x9d, 0x0f, 0x69, 0x6c, 0x6e, 0x42, 0x62, 0xd6, 0xf8, 0x85, 0x07, 0x4e, 0x7d, 0xf5, 0x42,
	0x0b, 0x1e, 0xfa, 0xb0, 0x06, 0xc9, 0x78, 0x76, 0xcd, 0x05, 0x2f, 0x5d, 0x24, 0xd5, 0x34, 0x83,
	0xe4, 0x7d, 0xfe, 0x23, 0x1a, 0x2c, 0x15, 0x89, 0x12, 0x57, 0xfa, 0xd5, 0xbe, 0xb7, 0x02, 0x1f,
	0xad, 0x1f, 0xf4, 0xb5, 0xc0, 0x83, 0xc4, 0x68, 0x85, 0x34, 0x8a, 0xac, 0x5c, 0xdf, 0xfb, 0x98,
	0x86, 0x77, 0xab, 0x1c, 0xd7, 0x50, 0x9a, 0x1f, 0xec, 0x8b, 0x85, 0x27, 0xc7, 0xf4, 0x71, 0x0d,
	0xa6, 0x0a, 0xa0, 0x54, 0x1e, 0xd0, 0x94, 0x36, 0xd1, 0x2c, 0x13, 0x3f, 0xa1, 0xb1, 0xb7, 0xaa,
	0xc4, 0x35, 0x64, 0x46, 0x42, 0xe5, 0xe6, 0x7d, 0xad, 0xa6, 0xe4, 0x27, 0xcb, 0x53, 0xf2, 0xa8,
	0xea, 0x73, 0x35, 0x27, 0xaf, 0x90, 0x69, 0x74, 0x5c, 0xbe, 0x19, 0x7c, 0x4a, 0x63, 0xbf, 0x53,
	0x1c, 0x98, 0xeb, 0x03, 0x50, 0x73, 0x82, 0x0d, 0x72, 0xfb, 0xd3, 0x3a, 0x3d, 0x16, 0x39, 0x20,
	0xad, 0xe1, 0x72, 0x9d, 0x04, 0x3e, 0x54, 0x45, 0xaf, 0xb3, 0x43, 0xdb, 0xe6, 0x67, 0xca, 0xf7,
	0x44, 0xd8, 0xfa, 0x2d, 0xbe, 0x9c, 0x57, 0xac, 0x52, 0x5a, 0xb9, 0xd8, 0x7d, 0x56, 0x43, 0xc7,
	0x6c, 0x56, 0x63, 0x6a, 0x08, 0x6d, 0x72, 0xcc, 0x49, 0x00, 0xd5, 0x61, 0x17, 0x81, 0xfc, 0x05,
	0x86, 0xb3, 0xac, 0x98, 0x9f, 0x2b, 0xd7, 0x79, 0xa7, 0xa4, 0xc8, 0xdf, 0x6f, 0xf8, 0xc3, 0x15,
	0x96, 0x25, 0xdd, 0x64, 0xa7, 0x0d, 0x8c, 0x6a, 0x48, 0x9f, 0x28, 0xa7, 0x9d, 0x42, 0x98, 0x1a,
	0xcc, 0x07, 0xc8, 0x98, 0x7a, 0xc9, 0x78, 0x52, 0x23, 0xd5, 0x88, 0x93, 0x5d, 0x2b, 0xca, 0x76,
	0xbb, 0x6c, 0x7e, 0xfe, 0xf9, 0xed, 0x76, 0x99, 0x8d, 0x01, 0x32, 0x4e, 0x59, 0xa2, 0x7c, 0x41,
	0x67, 0x0c, 0x10, 0xb0, 0x4b, 0x32, 0x5f, 0xce, 0x93, 0x89, 0x7c, 0xca, 0x3e, 0xa5, 0xc1, 0x32,
	0x1e, 0xed, 0x79, 0x6a, 0x2d, 0xf7, 0x9f, 0x5a, 0x5f, 0x3c, 0xc8, 0xa9, 0xb5, 0x5c, 0x38, 0xb5,
	0x58, 0xb3, 0x57, 0xcf, 0x10, 0x88, 0xc7, 0xd3, 0x5a, 0x7d, 0x3a, 0x3b, 0x3b, 0x20, 0x24, 0x50,
	0x15, 0x4a, 0x9f, 0x36, 0x9f, 0xd1, 0xa8, 0x8a, 0xac, 0x47, 0xc3, 0xdc, 0x32, 0x8b, 0x97, 0x90,
	0xf4, 0x12, 0x2b, 0x8e, 0x9d, 0x27, 0x1e, 0x3f, 0x54, 0xee, 0x2c, 0x83, 0x63, 0xe5, 0xb5, 0x16,
	0x0f, 0x1f, 0x8b, 0x2c, 0xc9, 0xf8, 0x0d, 0x66, 0x7e, 0x52, 0x87, 0x59, 0x4e, 0x21, 0xdb, 0xfd,
	0x06, 0xb6, 0x89, 0x99, 0x27, 0x56, 0xa6, 0x9d, 0xa7, 0x74, 0xb8, 0x67, 0x55, 0xd5, 0xab, 0xe9,
	0xe8, 0xf3, 0x6a, 0x62, 0xc0, 0x15, 0x34, 0x2f, 0x3a, 0x32, 0x9f, 0xdd, 0x83, 0x31, 0x77, 0xd7,
	0xab, 0x02, 0x50, 0x55, 0x1a, 0x19, 0xd7, 0xc8, 0xd1, 0xbe, 0xdd, 0x0b, 0x8d, 0xdf, 0xd6, 0xd1,
	0x38, 0x53, 0xf0, 0x2c, 0x4a, 0x74, 0xc8, 0xf1, 0xc1, 0xbe, 0xcd, 0x2a, 0xe5, 0x7b, 0x3a, 0xec,
	0x8b, 0x03, 0xbc, 0x9b, 0x96, 0x4d, 0x9f, 0xf4, 0x8c, 0xfc, 0x07, 0x07, 0x96, 0x9e, 0xb2, 0x9e,
	0x23, 0x63, 0x6a, 0xf7, 0x7a, 0xe6, 0xd6, 0xa1, 0xd2, 0x3c, 0x55, 0x01, 0x4c, 0x95, 0xda, 0xbe,
	0xa5, 0x36, 0xa6, 0xea, 0x4b, 0xb7, 0x74, 0x54, 0x65, 0xed, 0x5b, 0x48, 0x63, 0xaa, 0x2e, 0xca,
	0x77, 0xff, 0x69, 0x98, 0xa8, 0xf9, 0x65, 0x0d, 0x69, 0x38, 0x1a, 0xc9, 0xf0, 0x50, 0xe3, 0x52,
	0x91, 0x07, 0x6a, 0xf9, 0x2b, 0x7b, 0xc8, 0xca, 0x4f, 0x3a, 0x2a, 0x11, 0x54, 0xf3, 0x05, 0x32,
	0x99, 0xf6, 0x67, 0x71, 0xce, 0x7d, 0x55, 0x47, 0x8f, 0x04, 0x89, 0xc3, 0x6e, 0x83, 0xdf, 0xa5,
	0xd8, 0x2b, 0x1f, 0xc5, 0x4f, 0x5f, 0xd3, 0xf1, 0xd3, 0x24, 0xc7, 0x29, 0x2e, 0xda, 0x22, 0x73,
	0xf9, 0xad, 0xc9, 0x31, 0xd1, 0xfc, 0xba, 0xce, 0x06, 0x67, 0xd4, 0x0d, 0x36, 0x04, 0x94, 0x6d,
	0xb3, 0x18, 0xc5, 0x6f, 0xe8, 0xa8, 0x9b, 0x08, 0x72, 0xe1, 0xbb, 0x17, 0xe6, 0x7e, 0xf6, 0xe6,
	0x10, 0xbc, 0xfd, 0x4d, 0x1d, 0x31, 0x43, 0x6c, 0x35, 0x78, 0x19, 0xdc, 0x83, 0x49, 0xad, 0x0a,
	0xf8, 0x96, 0x96, 0x7b, 0x38, 0x4e, 0x91, 0xa0, 0xe4, 0x25, 0x52, 0xca, 0xd7, 0x24, 0x1d, 0xf3,
	0x3b, 0x07, 0xc9, 0x4b, 0x5e, 0x28, 0x9b, 0xf8, 0xd2, 0xa4, 0x63, 0xbc, 0x36, 0xbb, 0x86, 0xf5,
	0x0b, 0xfd, 0xae, 0x0e, 0xef, 0x9c, 0xca, 0xab, 0xe8, 0x05, 0xcf, 0x17, 0x75, 0x7e, 0x5f, 0xcb,
	0xf3, 0xad, 0x9c, 0xc0, 0x47, 0xc8, 0x42, 0x3e, 0x2b, 0x6e, 0x42, 0xeb, 0xec, 0x50, 0xd7, 0xdf,
	0xf5, 0x3d, 0xd7, 0xfc, 0xe1, 0x2d, 0x8d, 0xa6, 0x79, 0x54, 0xcd, 0x8c, 0x87, 0xed, 0xe8, 0xaa,
	0x40, 0xb3, 0x73, 0x9b, 0xbf, 0x98, 0xef, 0x86, 0x14, 0x86, 0xe2, 0xb8, 0x67, 0xfe, 0x48, 0xa3,
	0x02, 0xc6, 0x19, 0xa4, 0x21, 0x10, 0x30, 0x65, 0x8e, 0xbc, 0x31, 0xb1, 0x83, 0xd8, 0x07, 0xf4,
	0x8f, 0x75, 0x32, 0x23, 0x5d, 0xce, 0xac, 0xb3, 0xd4, 0xcc, 0xdc, 0xf3, 0x9c, 0x8e, 0x7b, 0xc6,
	0x02, 0xf1, 0x6e, 0x47, 0x9c, 0x24, 0xe2, 0x4c, 0x52, 0xc3, 0xf6, 0x13, 0x1d, 0x9e, 0x2a, 0x02,
	0xf3, 0x01, 0xc3, 0x52, 0xce, 0x14, 0xfd, 0x54, 0xb7, 0x54, 0x62, 0x9a, 0x6a, 0x82, 0x2b, 0xb2,
	0xfc, 0x93, 0xc9, 0xcf, 0x34, 0xdc, 0x39, 0xe4, 0xe3, 0x1f, 0x4b, 0x60, 0x3e, 0x50, 0xdb, 0x6e,
	0xa6, 0xe1, 0xe7, 0x3a, 0x1a, 0x8c, 0xac, 0xe9, 0xa6, 0x42, 0xa0, 0x55, 0x0a, 0xe7, 0x64, 0x64,
	0xbf, 0xd0, 0x21, 0xab, 0x20, 0x4c, 0x4d, 0x41, 0x29, 0x2d, 0x7d, 0x0d, 0x99, 0x1d, 0x55, 0xcf,
	0x3d, 0x7b, 0x47, 0x39, 0xa5, 0x2c, 0x5d, 0xf9, 0x72, 0x32, 0x3d, 0xad, 0x20, 0x82, 0x03, 0x38,
	0x7f, 0xa9, 0xc3, 0x59, 0x75, 0x8a, 0x64, 0xdb, 0xd9, 0xcd, 0x23, 0x25, 0x95, 0xc3, 0xd0, 0xaf,
	0x74, 0x28, 0x67, 0x0b, 0x32, 0xc5, 0x20, 0x04, 0x9e, 0xec, 0xe3, 0xfb, 0xb5, 0x0e, 0x5f, 0xc5,
	0xc9, 0x11, 0xad, 0x36, 0xc8, 0xa2, 0x4f, 0x0b, 0xaf, 0x2b, 0xb3, 0xdf, 0x41, 0x3c, 0xb2, 0xdc,
	0xa2, 0x91, 0xfb, 0x98, 0x7c, 0xee, 0x6a, 0xfc, 0x54, 0x62, 0x67, 0x88, 0xff, 0x34, 0xe1, 0xa5,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x36, 0xa8, 0xdc, 0x5d, 0x21, 0x00, 0x00,
}
