// Code generated by protoc-gen-go.
// source: dstore/engine/procedures/om_GetOrders_Conditions_Ad.proto
// DO NOT EDIT!

/*
Package om_GetOrders_Conditions_Ad is a generated protocol buffer package.

It is generated from these files:
	dstore/engine/procedures/om_GetOrders_Conditions_Ad.proto

It has these top-level messages:
	Parameters
	Response
*/
package om_GetOrders_Conditions_Ad

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_values "gosdk.dstore.de/values"
import dstore_engine_error "gosdk.dstore.de/engine/error"
import dstore_engine_message "gosdk.dstore.de/engine/message"
import dstore_engine_metainformation "gosdk.dstore.de/engine/metainformation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameters struct {
	OrderByColumn                     *dstore_values.IntegerValue   `protobuf:"bytes,1,opt,name=order_by_column,json=orderByColumn" json:"order_by_column,omitempty"`
	OrderByColumnNull                 bool                          `protobuf:"varint,1001,opt,name=order_by_column_null,json=orderByColumnNull" json:"order_by_column_null,omitempty"`
	CreateValidOrderInfos             *dstore_values.BooleanValue   `protobuf:"bytes,2,opt,name=create_valid_order_infos,json=createValidOrderInfos" json:"create_valid_order_infos,omitempty"`
	CreateValidOrderInfosNull         bool                          `protobuf:"varint,1002,opt,name=create_valid_order_infos_null,json=createValidOrderInfosNull" json:"create_valid_order_infos_null,omitempty"`
	BruttoSum                         *dstore_values.StringValue    `protobuf:"bytes,3,opt,name=brutto_sum,json=bruttoSum" json:"brutto_sum,omitempty"`
	BruttoSumNull                     bool                          `protobuf:"varint,1003,opt,name=brutto_sum_null,json=bruttoSumNull" json:"brutto_sum_null,omitempty"`
	CurrencyId                        *dstore_values.IntegerValue   `protobuf:"bytes,4,opt,name=currency_id,json=currencyId" json:"currency_id,omitempty"`
	CurrencyIdNull                    bool                          `protobuf:"varint,1004,opt,name=currency_id_null,json=currencyIdNull" json:"currency_id_null,omitempty"`
	QuantityForOneOrderContent        *dstore_values.StringValue    `protobuf:"bytes,5,opt,name=quantity_for_one_order_content,json=quantityForOneOrderContent" json:"quantity_for_one_order_content,omitempty"`
	QuantityForOneOrderContentNull    bool                          `protobuf:"varint,1005,opt,name=quantity_for_one_order_content_null,json=quantityForOneOrderContentNull" json:"quantity_for_one_order_content_null,omitempty"`
	Combination                       *dstore_values.StringValue    `protobuf:"bytes,6,opt,name=combination" json:"combination,omitempty"`
	CombinationNull                   bool                          `protobuf:"varint,1006,opt,name=combination_null,json=combinationNull" json:"combination_null,omitempty"`
	FromDate                          *dstore_values.TimestampValue `protobuf:"bytes,7,opt,name=from_date,json=fromDate" json:"from_date,omitempty"`
	FromDateNull                      bool                          `protobuf:"varint,1007,opt,name=from_date_null,json=fromDateNull" json:"from_date_null,omitempty"`
	ToDate                            *dstore_values.TimestampValue `protobuf:"bytes,8,opt,name=to_date,json=toDate" json:"to_date,omitempty"`
	ToDateNull                        bool                          `protobuf:"varint,1008,opt,name=to_date_null,json=toDateNull" json:"to_date_null,omitempty"`
	OrderDesc                         *dstore_values.BooleanValue   `protobuf:"bytes,9,opt,name=order_desc,json=orderDesc" json:"order_desc,omitempty"`
	OrderDescNull                     bool                          `protobuf:"varint,1009,opt,name=order_desc_null,json=orderDescNull" json:"order_desc_null,omitempty"`
	DateAndTimeFormat                 *dstore_values.IntegerValue   `protobuf:"bytes,10,opt,name=date_and_time_format,json=dateAndTimeFormat" json:"date_and_time_format,omitempty"`
	DateAndTimeFormatNull             bool                          `protobuf:"varint,1010,opt,name=date_and_time_format_null,json=dateAndTimeFormatNull" json:"date_and_time_format_null,omitempty"`
	IncludeTime                       *dstore_values.BooleanValue   `protobuf:"bytes,11,opt,name=include_time,json=includeTime" json:"include_time,omitempty"`
	IncludeTimeNull                   bool                          `protobuf:"varint,1011,opt,name=include_time_null,json=includeTimeNull" json:"include_time_null,omitempty"`
	GetInfoForValidOrderContent       *dstore_values.BooleanValue   `protobuf:"bytes,12,opt,name=get_info_for_valid_order_content,json=getInfoForValidOrderContent" json:"get_info_for_valid_order_content,omitempty"`
	GetInfoForValidOrderContentNull   bool                          `protobuf:"varint,1012,opt,name=get_info_for_valid_order_content_null,json=getInfoForValidOrderContentNull" json:"get_info_for_valid_order_content_null,omitempty"`
	OrderStateList                    *dstore_values.StringValue    `protobuf:"bytes,13,opt,name=order_state_list,json=orderStateList" json:"order_state_list,omitempty"`
	OrderStateListNull                bool                          `protobuf:"varint,1013,opt,name=order_state_list_null,json=orderStateListNull" json:"order_state_list_null,omitempty"`
	SkipOHavingDifferentOStates       *dstore_values.BooleanValue   `protobuf:"bytes,14,opt,name=skip_o_having_different_o_states,json=skipOHavingDifferentOStates" json:"skip_o_having_different_o_states,omitempty"`
	SkipOHavingDifferentOStatesNull   bool                          `protobuf:"varint,1014,opt,name=skip_o_having_different_o_states_null,json=skipOHavingDifferentOStatesNull" json:"skip_o_having_different_o_states_null,omitempty"`
	PaymentTypeIdList                 *dstore_values.StringValue    `protobuf:"bytes,15,opt,name=payment_type_id_list,json=paymentTypeIdList" json:"payment_type_id_list,omitempty"`
	PaymentTypeIdListNull             bool                          `protobuf:"varint,1015,opt,name=payment_type_id_list_null,json=paymentTypeIdListNull" json:"payment_type_id_list_null,omitempty"`
	ShippingTypeIdList                *dstore_values.StringValue    `protobuf:"bytes,16,opt,name=shipping_type_id_list,json=shippingTypeIdList" json:"shipping_type_id_list,omitempty"`
	ShippingTypeIdListNull            bool                          `protobuf:"varint,1016,opt,name=shipping_type_id_list_null,json=shippingTypeIdListNull" json:"shipping_type_id_list_null,omitempty"`
	ShowPersonCharacteristics         *dstore_values.BooleanValue   `protobuf:"bytes,17,opt,name=show_person_characteristics,json=showPersonCharacteristics" json:"show_person_characteristics,omitempty"`
	ShowPersonCharacteristicsNull     bool                          `protobuf:"varint,1017,opt,name=show_person_characteristics_null,json=showPersonCharacteristicsNull" json:"show_person_characteristics_null,omitempty"`
	ConvertResultToCurrencyId         *dstore_values.IntegerValue   `protobuf:"bytes,18,opt,name=convert_result_to_currency_id,json=convertResultToCurrencyId" json:"convert_result_to_currency_id,omitempty"`
	ConvertResultToCurrencyIdNull     bool                          `protobuf:"varint,1018,opt,name=convert_result_to_currency_id_null,json=convertResultToCurrencyIdNull" json:"convert_result_to_currency_id_null,omitempty"`
	ConvertResultToGivenCurrency      *dstore_values.BooleanValue   `protobuf:"bytes,19,opt,name=convert_result_to_given_currency,json=convertResultToGivenCurrency" json:"convert_result_to_given_currency,omitempty"`
	ConvertResultToGivenCurrencyNull  bool                          `protobuf:"varint,1019,opt,name=convert_result_to_given_currency_null,json=convertResultToGivenCurrencyNull" json:"convert_result_to_given_currency_null,omitempty"`
	PurchaseOrder                     *dstore_values.BooleanValue   `protobuf:"bytes,20,opt,name=purchase_order,json=purchaseOrder" json:"purchase_order,omitempty"`
	PurchaseOrderNull                 bool                          `protobuf:"varint,1020,opt,name=purchase_order_null,json=purchaseOrderNull" json:"purchase_order_null,omitempty"`
	InputNestLevelOInfoConds          *dstore_values.IntegerValue   `protobuf:"bytes,21,opt,name=input_nest_level_o_info_conds,json=inputNestLevelOInfoConds" json:"input_nest_level_o_info_conds,omitempty"`
	InputNestLevelOInfoCondsNull      bool                          `protobuf:"varint,1021,opt,name=input_nest_level_o_info_conds_null,json=inputNestLevelOInfoCondsNull" json:"input_nest_level_o_info_conds_null,omitempty"`
	ValueSeparatorINOperator          *dstore_values.StringValue    `protobuf:"bytes,22,opt,name=value_separator_i_n_operator,json=valueSeparatorINOperator" json:"value_separator_i_n_operator,omitempty"`
	ValueSeparatorINOperatorNull      bool                          `protobuf:"varint,1022,opt,name=value_separator_i_n_operator_null,json=valueSeparatorINOperatorNull" json:"value_separator_i_n_operator_null,omitempty"`
	Country                           *dstore_values.StringValue    `protobuf:"bytes,23,opt,name=country" json:"country,omitempty"`
	CountryNull                       bool                          `protobuf:"varint,1023,opt,name=country_null,json=countryNull" json:"country_null,omitempty"`
	LanguageId                        *dstore_values.IntegerValue   `protobuf:"bytes,24,opt,name=language_id,json=languageId" json:"language_id,omitempty"`
	LanguageIdNull                    bool                          `protobuf:"varint,1024,opt,name=language_id_null,json=languageIdNull" json:"language_id_null,omitempty"`
	InputNestLevelOConInfoConds       *dstore_values.IntegerValue   `protobuf:"bytes,25,opt,name=input_nest_level_o_con_info_conds,json=inputNestLevelOConInfoConds" json:"input_nest_level_o_con_info_conds,omitempty"`
	InputNestLevelOConInfoCondsNull   bool                          `protobuf:"varint,1025,opt,name=input_nest_level_o_con_info_conds_null,json=inputNestLevelOConInfoCondsNull" json:"input_nest_level_o_con_info_conds_null,omitempty"`
	CondsMustBeFulfilledForOConId     *dstore_values.BooleanValue   `protobuf:"bytes,26,opt,name=conds_must_be_fulfilled_for_o_con_id,json=condsMustBeFulfilledForOConId" json:"conds_must_be_fulfilled_for_o_con_id,omitempty"`
	CondsMustBeFulfilledForOConIdNull bool                          `protobuf:"varint,1026,opt,name=conds_must_be_fulfilled_for_o_con_id_null,json=condsMustBeFulfilledForOConIdNull" json:"conds_must_be_fulfilled_for_o_con_id_null,omitempty"`
	FilterByNodeIdsInOneId            *dstore_values.IntegerValue   `protobuf:"bytes,27,opt,name=filter_by_node_ids_in_one_id,json=filterByNodeIdsInOneId" json:"filter_by_node_ids_in_one_id,omitempty"`
	FilterByNodeIdsInOneIdNull        bool                          `protobuf:"varint,1027,opt,name=filter_by_node_ids_in_one_id_null,json=filterByNodeIdsInOneIdNull" json:"filter_by_node_ids_in_one_id_null,omitempty"`
	GetComputedSum                    *dstore_values.BooleanValue   `protobuf:"bytes,28,opt,name=get_computed_sum,json=getComputedSum" json:"get_computed_sum,omitempty"`
	GetComputedSumNull                bool                          `protobuf:"varint,1028,opt,name=get_computed_sum_null,json=getComputedSumNull" json:"get_computed_sum_null,omitempty"`
	OnlyValidPosForComputedSum        *dstore_values.BooleanValue   `protobuf:"bytes,29,opt,name=only_valid_pos_for_computed_sum,json=onlyValidPosForComputedSum" json:"only_valid_pos_for_computed_sum,omitempty"`
	OnlyValidPosForComputedSumNull    bool                          `protobuf:"varint,1029,opt,name=only_valid_pos_for_computed_sum_null,json=onlyValidPosForComputedSumNull" json:"only_valid_pos_for_computed_sum_null,omitempty"`
	OrderSurchIdsForComputedSum       *dstore_values.StringValue    `protobuf:"bytes,30,opt,name=order_surch_ids_for_computed_sum,json=orderSurchIdsForComputedSum" json:"order_surch_ids_for_computed_sum,omitempty"`
	OrderSurchIdsForComputedSumNull   bool                          `protobuf:"varint,1030,opt,name=order_surch_ids_for_computed_sum_null,json=orderSurchIdsForComputedSumNull" json:"order_surch_ids_for_computed_sum_null,omitempty"`
}

func (m *Parameters) Reset()                    { *m = Parameters{} }
func (m *Parameters) String() string            { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()               {}
func (*Parameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameters) GetOrderByColumn() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderByColumn
	}
	return nil
}

func (m *Parameters) GetCreateValidOrderInfos() *dstore_values.BooleanValue {
	if m != nil {
		return m.CreateValidOrderInfos
	}
	return nil
}

func (m *Parameters) GetBruttoSum() *dstore_values.StringValue {
	if m != nil {
		return m.BruttoSum
	}
	return nil
}

func (m *Parameters) GetCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.CurrencyId
	}
	return nil
}

func (m *Parameters) GetQuantityForOneOrderContent() *dstore_values.StringValue {
	if m != nil {
		return m.QuantityForOneOrderContent
	}
	return nil
}

func (m *Parameters) GetCombination() *dstore_values.StringValue {
	if m != nil {
		return m.Combination
	}
	return nil
}

func (m *Parameters) GetFromDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.FromDate
	}
	return nil
}

func (m *Parameters) GetToDate() *dstore_values.TimestampValue {
	if m != nil {
		return m.ToDate
	}
	return nil
}

func (m *Parameters) GetOrderDesc() *dstore_values.BooleanValue {
	if m != nil {
		return m.OrderDesc
	}
	return nil
}

func (m *Parameters) GetDateAndTimeFormat() *dstore_values.IntegerValue {
	if m != nil {
		return m.DateAndTimeFormat
	}
	return nil
}

func (m *Parameters) GetIncludeTime() *dstore_values.BooleanValue {
	if m != nil {
		return m.IncludeTime
	}
	return nil
}

func (m *Parameters) GetGetInfoForValidOrderContent() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetInfoForValidOrderContent
	}
	return nil
}

func (m *Parameters) GetOrderStateList() *dstore_values.StringValue {
	if m != nil {
		return m.OrderStateList
	}
	return nil
}

func (m *Parameters) GetSkipOHavingDifferentOStates() *dstore_values.BooleanValue {
	if m != nil {
		return m.SkipOHavingDifferentOStates
	}
	return nil
}

func (m *Parameters) GetPaymentTypeIdList() *dstore_values.StringValue {
	if m != nil {
		return m.PaymentTypeIdList
	}
	return nil
}

func (m *Parameters) GetShippingTypeIdList() *dstore_values.StringValue {
	if m != nil {
		return m.ShippingTypeIdList
	}
	return nil
}

func (m *Parameters) GetShowPersonCharacteristics() *dstore_values.BooleanValue {
	if m != nil {
		return m.ShowPersonCharacteristics
	}
	return nil
}

func (m *Parameters) GetConvertResultToCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ConvertResultToCurrencyId
	}
	return nil
}

func (m *Parameters) GetConvertResultToGivenCurrency() *dstore_values.BooleanValue {
	if m != nil {
		return m.ConvertResultToGivenCurrency
	}
	return nil
}

func (m *Parameters) GetPurchaseOrder() *dstore_values.BooleanValue {
	if m != nil {
		return m.PurchaseOrder
	}
	return nil
}

func (m *Parameters) GetInputNestLevelOInfoConds() *dstore_values.IntegerValue {
	if m != nil {
		return m.InputNestLevelOInfoConds
	}
	return nil
}

func (m *Parameters) GetValueSeparatorINOperator() *dstore_values.StringValue {
	if m != nil {
		return m.ValueSeparatorINOperator
	}
	return nil
}

func (m *Parameters) GetCountry() *dstore_values.StringValue {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *Parameters) GetLanguageId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LanguageId
	}
	return nil
}

func (m *Parameters) GetInputNestLevelOConInfoConds() *dstore_values.IntegerValue {
	if m != nil {
		return m.InputNestLevelOConInfoConds
	}
	return nil
}

func (m *Parameters) GetCondsMustBeFulfilledForOConId() *dstore_values.BooleanValue {
	if m != nil {
		return m.CondsMustBeFulfilledForOConId
	}
	return nil
}

func (m *Parameters) GetFilterByNodeIdsInOneId() *dstore_values.IntegerValue {
	if m != nil {
		return m.FilterByNodeIdsInOneId
	}
	return nil
}

func (m *Parameters) GetGetComputedSum() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetComputedSum
	}
	return nil
}

func (m *Parameters) GetOnlyValidPosForComputedSum() *dstore_values.BooleanValue {
	if m != nil {
		return m.OnlyValidPosForComputedSum
	}
	return nil
}

func (m *Parameters) GetOrderSurchIdsForComputedSum() *dstore_values.StringValue {
	if m != nil {
		return m.OrderSurchIdsForComputedSum
	}
	return nil
}

type Response struct {
	Error           *dstore_engine_error.Error                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	MetaInformation []*dstore_engine_metainformation.MetaInformation `protobuf:"bytes,2,rep,name=meta_information,json=metaInformation" json:"meta_information,omitempty"`
	Message         []*dstore_engine_message.Message                 `protobuf:"bytes,3,rep,name=message" json:"message,omitempty"`
	Row             []*Response_Row                                  `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_engine_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetMetaInformation() []*dstore_engine_metainformation.MetaInformation {
	if m != nil {
		return m.MetaInformation
	}
	return nil
}

func (m *Response) GetMessage() []*dstore_engine_message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetRow() []*Response_Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type Response_Row struct {
	RowId                        int32                       `protobuf:"varint,10000,opt,name=row_id,json=rowId" json:"row_id,omitempty"`
	OrderDateAndTime             *dstore_values.StringValue  `protobuf:"bytes,10001,opt,name=order_date_and_time,json=orderDateAndTime" json:"order_date_and_time,omitempty"`
	PaymentCost                  *dstore_values.DecimalValue `protobuf:"bytes,10002,opt,name=payment_cost,json=paymentCost" json:"payment_cost,omitempty"`
	DeliveryDateAndTime          *dstore_values.StringValue  `protobuf:"bytes,10003,opt,name=delivery_date_and_time,json=deliveryDateAndTime" json:"delivery_date_and_time,omitempty"`
	NetShippingCost              *dstore_values.DecimalValue `protobuf:"bytes,10004,opt,name=net_shipping_cost,json=netShippingCost" json:"net_shipping_cost,omitempty"`
	OrderNo                      *dstore_values.StringValue  `protobuf:"bytes,10005,opt,name=order_no,json=orderNo" json:"order_no,omitempty"`
	NettoSum                     *dstore_values.DecimalValue `protobuf:"bytes,10006,opt,name=netto_sum,json=nettoSum" json:"netto_sum,omitempty"`
	LastEditedByUserId           *dstore_values.IntegerValue `protobuf:"bytes,10007,opt,name=last_edited_by_user_id,json=lastEditedByUserId" json:"last_edited_by_user_id,omitempty"`
	OrderId                      *dstore_values.IntegerValue `protobuf:"bytes,10008,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	BruttoSum                    *dstore_values.DecimalValue `protobuf:"bytes,10009,opt,name=brutto_sum,json=bruttoSum" json:"brutto_sum,omitempty"`
	PreciseNetShippingCost       *dstore_values.DecimalValue `protobuf:"bytes,10010,opt,name=precise_net_shipping_cost,json=preciseNetShippingCost" json:"precise_net_shipping_cost,omitempty"`
	CharacVal2RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10011,opt,name=charac_val2_restr_by_pattern,json=characVal2RestrByPattern" json:"charac_val2_restr_by_pattern,omitempty"`
	NetSum                       *dstore_values.DecimalValue `protobuf:"bytes,10012,opt,name=net_sum,json=netSum" json:"net_sum,omitempty"`
	ValidContentNetSum           *dstore_values.DecimalValue `protobuf:"bytes,10013,opt,name=valid_content_net_sum,json=validContentNetSum" json:"valid_content_net_sum,omitempty"`
	PreciseValidContentNetSum    *dstore_values.DecimalValue `protobuf:"bytes,10014,opt,name=precise_valid_content_net_sum,json=preciseValidContentNetSum" json:"precise_valid_content_net_sum,omitempty"`
	PersonId                     *dstore_values.IntegerValue `protobuf:"bytes,10015,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	PaymentTypeDescription       *dstore_values.StringValue  `protobuf:"bytes,10016,opt,name=payment_type_description,json=paymentTypeDescription" json:"payment_type_description,omitempty"`
	ValidContentBruttoSum        *dstore_values.DecimalValue `protobuf:"bytes,10017,opt,name=valid_content_brutto_sum,json=validContentBruttoSum" json:"valid_content_brutto_sum,omitempty"`
	PreciseNetSum                *dstore_values.DecimalValue `protobuf:"bytes,10018,opt,name=precise_net_sum,json=preciseNetSum" json:"precise_net_sum,omitempty"`
	PositionCount                *dstore_values.IntegerValue `protobuf:"bytes,10019,opt,name=position_count,json=positionCount" json:"position_count,omitempty"`
	OrderStateId                 *dstore_values.IntegerValue `protobuf:"bytes,10020,opt,name=order_state_id,json=orderStateId" json:"order_state_id,omitempty"`
	ShippingTypeId               *dstore_values.IntegerValue `protobuf:"bytes,10021,opt,name=shipping_type_id,json=shippingTypeId" json:"shipping_type_id,omitempty"`
	PersonTypeId                 *dstore_values.IntegerValue `protobuf:"bytes,10022,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	PreciseComputedGrossSum      *dstore_values.DecimalValue `protobuf:"bytes,10023,opt,name=precise_computed_gross_sum,json=preciseComputedGrossSum" json:"precise_computed_gross_sum,omitempty"`
	HasValidContents             *dstore_values.BooleanValue `protobuf:"bytes,10024,opt,name=has_valid_contents,json=hasValidContents" json:"has_valid_contents,omitempty"`
	NetPaymentCost               *dstore_values.DecimalValue `protobuf:"bytes,10025,opt,name=net_payment_cost,json=netPaymentCost" json:"net_payment_cost,omitempty"`
	DeliveryPersonId             *dstore_values.IntegerValue `protobuf:"bytes,10026,opt,name=delivery_person_id,json=deliveryPersonId" json:"delivery_person_id,omitempty"`
	ShippingTypeDescription      *dstore_values.StringValue  `protobuf:"bytes,10027,opt,name=shipping_type_description,json=shippingTypeDescription" json:"shipping_type_description,omitempty"`
	GrossSum                     *dstore_values.DecimalValue `protobuf:"bytes,10028,opt,name=gross_sum,json=grossSum" json:"gross_sum,omitempty"`
	UnitSymbol                   *dstore_values.StringValue  `protobuf:"bytes,10029,opt,name=unit_symbol,json=unitSymbol" json:"unit_symbol,omitempty"`
	PreciseNetPaymentCost        *dstore_values.DecimalValue `protobuf:"bytes,10030,opt,name=precise_net_payment_cost,json=preciseNetPaymentCost" json:"precise_net_payment_cost,omitempty"`
	CustomerCharacteristicValue2 *dstore_values.StringValue  `protobuf:"bytes,10031,opt,name=customer_characteristic_value2,json=customerCharacteristicValue2" json:"customer_characteristic_value2,omitempty"`
	PublicDescription            *dstore_values.StringValue  `protobuf:"bytes,10032,opt,name=public_description,json=publicDescription" json:"public_description,omitempty"`
	CurrencyId                   *dstore_values.IntegerValue `protobuf:"bytes,10033,opt,name=currency_id,json=currencyId" json:"currency_id,omitempty"`
	CustomerCharacteristicValue1 *dstore_values.StringValue  `protobuf:"bytes,10034,opt,name=customer_characteristic_value1,json=customerCharacteristicValue1" json:"customer_characteristic_value1,omitempty"`
	PreciseGrossSum              *dstore_values.DecimalValue `protobuf:"bytes,10035,opt,name=precise_gross_sum,json=preciseGrossSum" json:"precise_gross_sum,omitempty"`
	ComputedGrossSum             *dstore_values.DecimalValue `protobuf:"bytes,10036,opt,name=computed_gross_sum,json=computedGrossSum" json:"computed_gross_sum,omitempty"`
	ValidContentNettoSum         *dstore_values.DecimalValue `protobuf:"bytes,10037,opt,name=valid_content_netto_sum,json=validContentNettoSum" json:"valid_content_netto_sum,omitempty"`
	ShippingCost                 *dstore_values.DecimalValue `protobuf:"bytes,10038,opt,name=shipping_cost,json=shippingCost" json:"shipping_cost,omitempty"`
	CharacVal1RestrByPattern     *dstore_values.StringValue  `protobuf:"bytes,10039,opt,name=charac_val1_restr_by_pattern,json=characVal1RestrByPattern" json:"charac_val1_restr_by_pattern,omitempty"`
	PaymentTypeId                *dstore_values.IntegerValue `protobuf:"bytes,10040,opt,name=payment_type_id,json=paymentTypeId" json:"payment_type_id,omitempty"`
	PreciseValidContentGrossSum  *dstore_values.DecimalValue `protobuf:"bytes,10041,opt,name=precise_valid_content_gross_sum,json=preciseValidContentGrossSum" json:"precise_valid_content_gross_sum,omitempty"`
	PreciseComputedNetSum        *dstore_values.DecimalValue `protobuf:"bytes,10042,opt,name=precise_computed_net_sum,json=preciseComputedNetSum" json:"precise_computed_net_sum,omitempty"`
	OrderState                   *dstore_values.StringValue  `protobuf:"bytes,10043,opt,name=order_state,json=orderState" json:"order_state,omitempty"`
	ComputedNetSum               *dstore_values.DecimalValue `protobuf:"bytes,10044,opt,name=computed_net_sum,json=computedNetSum" json:"computed_net_sum,omitempty"`
	ValidContentGrossSum         *dstore_values.DecimalValue `protobuf:"bytes,10045,opt,name=valid_content_gross_sum,json=validContentGrossSum" json:"valid_content_gross_sum,omitempty"`
}

func (m *Response_Row) Reset()                    { *m = Response_Row{} }
func (m *Response_Row) String() string            { return proto.CompactTextString(m) }
func (*Response_Row) ProtoMessage()               {}
func (*Response_Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Row) GetOrderDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.OrderDateAndTime
	}
	return nil
}

func (m *Response_Row) GetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryDateAndTime() *dstore_values.StringValue {
	if m != nil {
		return m.DeliveryDateAndTime
	}
	return nil
}

func (m *Response_Row) GetNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetShippingCost
	}
	return nil
}

func (m *Response_Row) GetOrderNo() *dstore_values.StringValue {
	if m != nil {
		return m.OrderNo
	}
	return nil
}

func (m *Response_Row) GetNettoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NettoSum
	}
	return nil
}

func (m *Response_Row) GetLastEditedByUserId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LastEditedByUserId
	}
	return nil
}

func (m *Response_Row) GetOrderId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderId
	}
	return nil
}

func (m *Response_Row) GetBruttoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.BruttoSum
	}
	return nil
}

func (m *Response_Row) GetPreciseNetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal2RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal2RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetSum
	}
	return nil
}

func (m *Response_Row) GetValidContentNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentNetSum
	}
	return nil
}

func (m *Response_Row) GetPreciseValidContentNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseValidContentNetSum
	}
	return nil
}

func (m *Response_Row) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PaymentTypeDescription
	}
	return nil
}

func (m *Response_Row) GetValidContentBruttoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentBruttoSum
	}
	return nil
}

func (m *Response_Row) GetPreciseNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetSum
	}
	return nil
}

func (m *Response_Row) GetPositionCount() *dstore_values.IntegerValue {
	if m != nil {
		return m.PositionCount
	}
	return nil
}

func (m *Response_Row) GetOrderStateId() *dstore_values.IntegerValue {
	if m != nil {
		return m.OrderStateId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ShippingTypeId
	}
	return nil
}

func (m *Response_Row) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Response_Row) GetPreciseComputedGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseComputedGrossSum
	}
	return nil
}

func (m *Response_Row) GetHasValidContents() *dstore_values.BooleanValue {
	if m != nil {
		return m.HasValidContents
	}
	return nil
}

func (m *Response_Row) GetNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.NetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetDeliveryPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.DeliveryPersonId
	}
	return nil
}

func (m *Response_Row) GetShippingTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ShippingTypeDescription
	}
	return nil
}

func (m *Response_Row) GetGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.GrossSum
	}
	return nil
}

func (m *Response_Row) GetUnitSymbol() *dstore_values.StringValue {
	if m != nil {
		return m.UnitSymbol
	}
	return nil
}

func (m *Response_Row) GetPreciseNetPaymentCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseNetPaymentCost
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue2() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue2
	}
	return nil
}

func (m *Response_Row) GetPublicDescription() *dstore_values.StringValue {
	if m != nil {
		return m.PublicDescription
	}
	return nil
}

func (m *Response_Row) GetCurrencyId() *dstore_values.IntegerValue {
	if m != nil {
		return m.CurrencyId
	}
	return nil
}

func (m *Response_Row) GetCustomerCharacteristicValue1() *dstore_values.StringValue {
	if m != nil {
		return m.CustomerCharacteristicValue1
	}
	return nil
}

func (m *Response_Row) GetPreciseGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseGrossSum
	}
	return nil
}

func (m *Response_Row) GetComputedGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ComputedGrossSum
	}
	return nil
}

func (m *Response_Row) GetValidContentNettoSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentNettoSum
	}
	return nil
}

func (m *Response_Row) GetShippingCost() *dstore_values.DecimalValue {
	if m != nil {
		return m.ShippingCost
	}
	return nil
}

func (m *Response_Row) GetCharacVal1RestrByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.CharacVal1RestrByPattern
	}
	return nil
}

func (m *Response_Row) GetPaymentTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PaymentTypeId
	}
	return nil
}

func (m *Response_Row) GetPreciseValidContentGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseValidContentGrossSum
	}
	return nil
}

func (m *Response_Row) GetPreciseComputedNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.PreciseComputedNetSum
	}
	return nil
}

func (m *Response_Row) GetOrderState() *dstore_values.StringValue {
	if m != nil {
		return m.OrderState
	}
	return nil
}

func (m *Response_Row) GetComputedNetSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ComputedNetSum
	}
	return nil
}

func (m *Response_Row) GetValidContentGrossSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ValidContentGrossSum
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "dstore.engine.om_GetOrders_Conditions_Ad.Parameters")
	proto.RegisterType((*Response)(nil), "dstore.engine.om_GetOrders_Conditions_Ad.Response")
	proto.RegisterType((*Response_Row)(nil), "dstore.engine.om_GetOrders_Conditions_Ad.Response.Row")
}

func init() {
	proto.RegisterFile("dstore/engine/procedures/om_GetOrders_Conditions_Ad.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 2369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x5a, 0x57, 0x73, 0xe4, 0xc6,
	0x11, 0x2e, 0x89, 0x3e, 0x86, 0x61, 0x06, 0xc3, 0x0d, 0x97, 0xe1, 0x48, 0x4a, 0xb2, 0x25, 0xbb,
	0x8a, 0xa7, 0xa3, 0xed, 0xb3, 0x65, 0xc9, 0x76, 0x1d, 0x97, 0x17, 0x28, 0x1f, 0x97, 0xac, 0xe5,
	0xe9, 0x5c, 0xd2, 0xd9, 0x82, 0x77, 0x17, 0xe0, 0x12, 0x25, 0x2c, 0x66, 0x8d, 0xc0, 0xab, 0x7d,
	0x73, 0x7e, 0x76, 0xce, 0xe7, 0x9c, 0x73, 0xce, 0xfe, 0x41, 0xce, 0x39, 0x07, 0xb9, 0xa7, 0x7b,
	0xb0, 0x00, 0x36, 0x0d, 0x58, 0x7e, 0x91, 0x0e, 0x44, 0x7f, 0x5f, 0x7f, 0xe8, 0xe9, 0xee, 0xe9,
	0x19, 0x92, 0x3d, 0x66, 0x05, 0xa1, 0xf0, 0xed, 0x8b, 0xb6, 0x57, 0x77, 0x3c, 0xfb, 0x62, 0xd3,
	0x17, 0x35, 0xdb, 0x8a, 0x7c, 0x3b, 0xb8, 0x28, 0x1a, 0xe6, 0x75, 0x3b, 0x3c, 0xf0, 0x2d, 0xdb,
	0x0f, 0xcc, 0xa2, 0xf0, 0x2c, 0x27, 0x74, 0x84, 0x17, 0x98, 0x57, 0xac, 0x2d, 0xb0, 0x0a, 0x85,
	0xf1, 0x30, 0x41, 0xb7, 0x08, 0xba, 0xd5, 0xdf, 0xbe, 0x30, 0xa7, 0x9c, 0x9c, 0x56, 0xdc, 0xc8,
	0x0e, 0x08, 0x5e, 0x58, 0xca, 0x7a, 0xb6, 0x7d, 0x5f, 0xf8, 0xea, 0xd5, 0x72, 0xf6, 0x55, 0xc3,
	0x0e, 0x82, 0x4a, 0xdd, 0x56, 0x2f, 0x1f, 0xe8, 0x7c, 0x19, 0x56, 0x1c, 0xef, 0x58, 0xf8, 0x8d,
	0x8a, 0xf4, 0x47, 0x46, 0x9b, 0xf7, 0x36, 0x18, 0x3b, 0xac, 0xf8, 0x15, 0x78, 0x0b, 0x72, 0x8c,
	0x22, 0x9b, 0x16, 0x52, 0x98, 0x59, 0x6d, 0x99, 0x35, 0xe1, 0x46, 0x0d, 0x8f, 0xdf, 0xb7, 0x7e,
	0xdf, 0xc3, 0xe3, 0xdb, 0xcb, 0x5b, 0xea, 0x23, 0x94, 0x34, 0xc7, 0x0b, 0xed, 0xba, 0xed, 0xdf,
	0x96, 0x4f, 0xe5, 0x49, 0xc4, 0xec, 0xb4, 0x8a, 0x88, 0x30, 0x1e, 0x65, 0xf3, 0x1d, 0x24, 0xa6,
	0x17, 0xb9, 0x2e, 0xff, 0xc5, 0x08, 0x50, 0x8d, 0x96, 0x67, 0x33, 0xd6, 0x25, 0x78, 0x63, 0xdc,
	0x62, 0xbc, 0xe6, 0xdb, 0x95, 0xd0, 0x36, 0x81, 0xde, 0xb1, 0x4c, 0x82, 0x4b, 0xb5, 0x01, 0xbf,
	0xbf, 0xa7, 0xff, 0xaa, 0x10, 0xae, 0x5d, 0xf1, 0xc8, 0xff, 0x02, 0x81, 0x6f, 0x4b, 0x2c, 0xc6,
	0x75, 0x4f, 0x22, 0x8d, 0x2b, 0x6c, 0xb5, 0x1f, 0x2b, 0x09, 0xfa, 0x25, 0x09, 0x5a, 0xea, 0x09,
	0x47, 0x61, 0x8f, 0x31, 0x56, 0xf5, 0xa3, 0x30, 0x14, 0x66, 0x10, 0x35, 0xf8, 0x10, 0x4a, 0x29,
	0x74, 0x48, 0x09, 0x42, 0xdf, 0xf1, 0xea, 0xa4, 0x64, 0x8c, 0xac, 0x8f, 0xa2, 0x86, 0xf1, 0x22,
	0x36, 0x9d, 0x40, 0xc9, 0xdf, 0xaf, 0xc8, 0xdf, 0x64, 0xdb, 0x08, 0x7d, 0x3c, 0xc1, 0xc6, 0x6b,
	0x91, 0xef, 0xdb, 0x5e, 0xad, 0x65, 0x3a, 0x16, 0x7f, 0x81, 0x3e, 0xde, 0x2c, 0xb6, 0xdf, 0xb3,
	0x8c, 0x47, 0xd8, 0x4c, 0x0a, 0x4d, 0x7e, 0x7e, 0x4d, 0x7e, 0xa6, 0x12, 0x33, 0x74, 0xf4, 0x2c,
	0x5b, 0x7b, 0x73, 0x54, 0xf1, 0x42, 0x27, 0x6c, 0x99, 0x90, 0x07, 0xa6, 0xf0, 0x6c, 0x15, 0x93,
	0x9a, 0x00, 0x7a, 0x2f, 0xe4, 0xe7, 0xb4, 0x1f, 0x58, 0x88, 0x19, 0xae, 0x09, 0xff, 0xc0, 0xb3,
	0x31, 0x5c, 0x45, 0x42, 0x1b, 0x37, 0xd9, 0x03, 0x83, 0xf9, 0x49, 0xdd, 0x6f, 0x48, 0xdd, 0x5a,
	0x7f, 0xa6, 0x76, 0x58, 0x44, 0xa3, 0xea, 0x78, 0x98, 0xae, 0x7c, 0x58, 0x2b, 0x2d, 0x6d, 0x6e,
	0xbc, 0x18, 0xc2, 0x92, 0x3c, 0x92, 0xe3, 0xdf, 0x92, 0xe3, 0xe9, 0xd4, 0x0b, 0xf4, 0xf4, 0x2a,
	0x36, 0x76, 0xec, 0x43, 0x55, 0x5a, 0x90, 0x04, 0x7c, 0x04, 0xfd, 0xac, 0x76, 0xf8, 0x09, 0x1d,
	0xa8, 0xad, 0xb0, 0xd2, 0x68, 0x92, 0xab, 0x51, 0x69, 0xbf, 0x0b, 0xe6, 0xc6, 0x43, 0x6c, 0xaa,
	0x8d, 0x25, 0x2f, 0xbf, 0x23, 0x2f, 0x13, 0xb1, 0x09, 0xba, 0xb8, 0xcc, 0x46, 0x20, 0x11, 0xd0,
	0xc1, 0x68, 0x1e, 0x07, 0xc3, 0xa1, 0x40, 0xfa, 0x0d, 0x36, 0xa1, 0x70, 0x44, 0xfe, 0x7b, 0x22,
	0x67, 0xf4, 0x5a, 0xa9, 0x67, 0x14, 0x64, 0xcb, 0x0e, 0x6a, 0x7c, 0x4c, 0x5f, 0x2d, 0x63, 0x68,
	0xbe, 0x0b, 0xd6, 0x32, 0x47, 0x13, 0x2c, 0x79, 0xf8, 0x83, 0xca, 0xd1, 0xb6, 0x11, 0x3a, 0xb9,
	0xc9, 0xe6, 0x51, 0x44, 0xc5, 0xb3, 0x4c, 0x29, 0xd5, 0xa4, 0x3e, 0xc2, 0x99, 0x3e, 0x59, 0x67,
	0x25, 0xf0, 0x8a, 0x67, 0xdd, 0x02, 0xd8, 0x35, 0x44, 0x41, 0x55, 0x2d, 0xf5, 0x62, 0x23, 0x01,
	0x7f, 0x24, 0x01, 0x0b, 0x5d, 0x30, 0x14, 0xf2, 0x1a, 0x36, 0xe1, 0x78, 0x35, 0x37, 0xb2, 0x6c,
	0x44, 0xf2, 0x71, 0xfd, 0xf7, 0x8e, 0x2b, 0x80, 0x64, 0x32, 0x5e, 0xc2, 0x66, 0xd3, 0x78, 0x72,
	0xf9, 0x27, 0x95, 0x18, 0x29, 0x43, 0x74, 0x56, 0x65, 0xeb, 0x75, 0x3b, 0xc4, 0x8e, 0x81, 0x09,
	0x9d, 0x6e, 0x23, 0x71, 0xc9, 0x4c, 0xe8, 0x05, 0x2c, 0x03, 0x89, 0x6c, 0x29, 0xf0, 0x19, 0x49,
	0x8f, 0x89, 0x8b, 0xe6, 0x80, 0x3d, 0xa4, 0xf3, 0x41, 0x22, 0xff, 0x4c, 0x22, 0x2f, 0x0c, 0x20,
	0x43, 0xd1, 0xbb, 0x6c, 0x86, 0xd0, 0x90, 0x4e, 0x10, 0x63, 0xd7, 0x09, 0x42, 0x3e, 0xa9, 0x2d,
	0x9e, 0x29, 0xc4, 0x1c, 0x49, 0xc8, 0x4d, 0x40, 0x18, 0xdb, 0x6c, 0xa1, 0x93, 0x85, 0x64, 0xfc,
	0x85, 0x64, 0x18, 0x59, 0xfb, 0x38, 0x5c, 0xc1, 0x73, 0x4e, 0xd3, 0x14, 0xe6, 0x49, 0xe5, 0x14,
	0x98, 0x4d, 0xcb, 0x39, 0x3e, 0xb6, 0x7d, 0xf9, 0x05, 0x82, 0x78, 0x02, 0x3e, 0x95, 0x23, 0x5c,
	0x92, 0xe4, 0xe0, 0x06, 0x52, 0xec, 0xc6, 0x0c, 0x07, 0xe8, 0x2a, 0x90, 0xe1, 0xd2, 0xf9, 0x20,
	0x9d, 0x7f, 0x55, 0xe1, 0x1a, 0x40, 0x86, 0xa2, 0x5f, 0xc7, 0xe6, 0x9b, 0x95, 0x56, 0x43, 0x12,
	0x84, 0xad, 0xa6, 0x2d, 0x7b, 0x28, 0x86, 0x6c, 0x5a, 0x1b, 0xb2, 0x59, 0x85, 0xbb, 0x05, 0xb0,
	0x3d, 0x0b, 0xa3, 0x06, 0x89, 0xdd, 0x8b, 0x8c, 0x14, 0xfd, 0x4d, 0x25, 0x76, 0x17, 0x0c, 0x75,
	0xec, 0xb3, 0x85, 0xe0, 0xc4, 0x69, 0x36, 0xe5, 0x37, 0x65, 0x84, 0xcc, 0x68, 0x85, 0x18, 0x31,
	0x30, 0xa5, 0xe4, 0x71, 0x56, 0xe8, 0x49, 0x47, 0x52, 0xfe, 0x4e, 0x52, 0x16, 0xbb, 0x81, 0xa8,
	0xe5, 0x0e, 0x5b, 0x0e, 0x4e, 0xc4, 0x5d, 0xb3, 0x09, 0x23, 0x01, 0x34, 0xcf, 0xda, 0x09, 0x0c,
	0x08, 0x35, 0x98, 0x0f, 0xe0, 0xbd, 0x53, 0x0b, 0xf8, 0xac, 0x7e, 0x0d, 0x97, 0x24, 0xfe, 0x10,
	0xe1, 0xc5, 0x2c, 0xda, 0xb8, 0x01, 0x59, 0xd2, 0x9f, 0x9c, 0xf4, 0xfd, 0x83, 0xf4, 0xad, 0xf6,
	0x65, 0x41, 0x99, 0x6f, 0x84, 0xfd, 0x5d, 0x78, 0xa7, 0xb6, 0x1f, 0x9a, 0x30, 0x87, 0x45, 0x2e,
	0x04, 0x5d, 0x98, 0xe9, 0xad, 0xd4, 0xd0, 0x77, 0xa7, 0x25, 0xc5, 0x50, 0x46, 0x82, 0x5b, 0xa2,
	0x98, 0xec, 0xac, 0x4f, 0xb2, 0xcd, 0x81, 0xf4, 0x24, 0xf5, 0x9f, 0x4a, 0x6a, 0x5f, 0x1e, 0x94,
	0x5a, 0x63, 0xeb, 0xdd, 0x5c, 0x75, 0xe7, 0xd4, 0xf6, 0xda, 0x8c, 0x7c, 0x4e, 0x1f, 0xd6, 0x95,
	0x0e, 0x2f, 0xd7, 0x25, 0x43, 0xec, 0xca, 0x38, 0x64, 0x0f, 0xe9, 0x9c, 0x90, 0xe6, 0x7f, 0x91,
	0xe6, 0xf5, 0x41, 0x6c, 0x28, 0x7b, 0x87, 0x4d, 0x35, 0x23, 0x1f, 0x96, 0x28, 0x50, 0x3b, 0x39,
	0x9f, 0xd7, 0x8b, 0x9c, 0x8c, 0x21, 0xd8, 0x9a, 0x8c, 0x8b, 0x6c, 0x2e, 0xcb, 0x41, 0x1a, 0xfe,
	0xad, 0x86, 0xc1, 0x8c, 0x31, 0x3a, 0x7d, 0x03, 0x5b, 0x75, 0xbc, 0x66, 0x04, 0xa9, 0x0a, 0x3b,
	0xa2, 0xe9, 0xda, 0xa7, 0xb6, 0x0b, 0xb5, 0x8d, 0x0d, 0x12, 0x04, 0x5b, 0x01, 0x5f, 0xd0, 0x2f,
	0x2b, 0x47, 0x86, 0x12, 0x10, 0xdc, 0x94, 0xf8, 0x03, 0xd9, 0x31, 0xe5, 0xa8, 0x1d, 0x18, 0x7b,
	0x6c, 0x73, 0x20, 0x3b, 0xa9, 0xfb, 0x0f, 0xa9, 0x5b, 0xe9, 0x47, 0x83, 0x42, 0x9f, 0x61, 0x2b,
	0xe8, 0xdb, 0x0c, 0xec, 0x26, 0x64, 0x27, 0x88, 0x31, 0x1d, 0xd3, 0x33, 0x05, 0x64, 0xb6, 0x7c,
	0xe0, 0x8b, 0xda, 0xca, 0xe5, 0xf8, 0xb3, 0xa3, 0x18, 0xbe, 0x57, 0x3a, 0x50, 0x58, 0xa8, 0x92,
	0x8d, 0x41, 0xdc, 0xa4, 0xf2, 0xbf, 0x4a, 0x65, 0x3f, 0x16, 0x54, 0xf9, 0x32, 0x36, 0x52, 0x13,
	0x91, 0x17, 0xfa, 0x2d, 0x7e, 0x5e, 0x2b, 0x28, 0x36, 0x35, 0x36, 0xd9, 0x84, 0xfa, 0x27, 0xb9,
	0x7a, 0x9e, 0x5c, 0x8d, 0xab, 0x1f, 0xc6, 0x13, 0x9a, 0x5b, 0xf1, 0xea, 0x11, 0x1c, 0x39, 0x64,
	0xb5, 0xf1, 0x1c, 0x83, 0x6b, 0x6c, 0x4f, 0x83, 0x6b, 0x0a, 0x4d, 0x5e, 0xde, 0x32, 0x4a, 0x83,
	0x6b, 0x62, 0xa6, 0xaa, 0x67, 0xa3, 0xc7, 0x9a, 0xc1, 0x72, 0xa5, 0xb3, 0x62, 0x49, 0xef, 0x7e,
	0xb9, 0x63, 0x39, 0x61, 0x29, 0x93, 0xc4, 0x38, 0x64, 0x2f, 0xd4, 0x3a, 0x21, 0x95, 0x6f, 0x25,
	0x95, 0x17, 0x06, 0xb0, 0xa1, 0xec, 0x13, 0xf6, 0x20, 0xa1, 0x1a, 0x11, 0x30, 0x56, 0x61, 0xcc,
	0x89, 0xdc, 0x63, 0xc7, 0x75, 0x6d, 0x8b, 0xc6, 0x63, 0x22, 0xb7, 0x78, 0x41, 0x5f, 0x53, 0xab,
	0x48, 0xb4, 0x0f, 0x3c, 0x3b, 0xf6, 0xb5, 0x98, 0x45, 0x0e, 0xce, 0xd2, 0xa9, 0x65, 0x3c, 0xc5,
	0x1e, 0xc9, 0xe3, 0x89, 0xe4, 0xbf, 0x8d, 0xe4, 0x6f, 0x0c, 0xa4, 0xc4, 0x0f, 0x78, 0x9a, 0xad,
	0xc0, 0x8f, 0x43, 0x3a, 0xc9, 0x79, 0xc2, 0x92, 0x0b, 0x15, 0x40, 0x38, 0x70, 0xb2, 0x07, 0xe1,
	0xcb, 0xfa, 0x90, 0x2f, 0x12, 0xc1, 0x4e, 0xab, 0x04, 0xf0, 0x3d, 0x2b, 0xd8, 0xf3, 0x60, 0xd6,
	0x07, 0xc5, 0xd7, 0xd8, 0xc6, 0x20, 0x6a, 0x52, 0xfa, 0x76, 0x52, 0x5a, 0xe8, 0xcd, 0x81, 0x12,
	0xaf, 0xb2, 0x19, 0x39, 0x3e, 0xc1, 0x48, 0x0f, 0x6b, 0x01, 0x9f, 0x2b, 0x8f, 0x69, 0x2b, 0xfa,
	0x78, 0x4e, 0x01, 0xa8, 0xa8, 0x30, 0xf2, 0xb0, 0x06, 0xe3, 0x4e, 0x27, 0x0d, 0x49, 0x78, 0x07,
	0x49, 0x30, 0xb2, 0xf6, 0xe8, 0xfa, 0x4d, 0xec, 0x82, 0xf0, 0xdc, 0x96, 0x9a, 0xd8, 0x9a, 0x70,
	0xa8, 0x94, 0xb1, 0xce, 0x28, 0x59, 0xd5, 0x2b, 0x29, 0x48, 0x0e, 0x9c, 0xe4, 0x0e, 0x45, 0x00,
	0xe1, 0x4f, 0xab, 0xda, 0x67, 0x0f, 0x6a, 0x3c, 0x90, 0xc8, 0x77, 0x92, 0xc8, 0xb5, 0xfe, 0x54,
	0x28, 0xb8, 0xc2, 0xd6, 0xd5, 0x4c, 0x27, 0x7b, 0x2e, 0x06, 0xbc, 0x4b, 0xf1, 0x9a, 0xb6, 0x45,
	0x2c, 0xd3, 0xe4, 0x27, 0x29, 0x60, 0x2d, 0x3a, 0x14, 0xc3, 0x78, 0xa6, 0x73, 0x41, 0x92, 0xdf,
	0xa5, 0x6a, 0x68, 0x00, 0x99, 0xd4, 0xbc, 0x79, 0x6f, 0x95, 0x8d, 0xc2, 0xfe, 0xd4, 0x14, 0x5e,
	0x60, 0x1b, 0x8f, 0xb2, 0x73, 0x78, 0xfb, 0xa1, 0xee, 0x24, 0xda, 0x2a, 0xd5, 0xc5, 0x0a, 0xdd,
	0x8c, 0x5c, 0x95, 0xff, 0x2d, 0x93, 0x21, 0x64, 0xf0, 0x8c, 0xbc, 0xf7, 0x30, 0x53, 0x17, 0x1f,
	0xfc, 0xfe, 0xf5, 0x21, 0x00, 0x6f, 0x75, 0x80, 0x3b, 0xaf, 0x47, 0xf6, 0xe1, 0x79, 0x2f, 0x79,
	0x2e, 0x4f, 0x37, 0xb2, 0x3f, 0x30, 0x5e, 0xc9, 0x46, 0xd4, 0x7d, 0x0b, 0x1f, 0x42, 0xc6, 0xb5,
	0x2e, 0x46, 0xba, 0x8d, 0xd9, 0xa7, 0xff, 0x97, 0x63, 0x73, 0xe8, 0xed, 0x43, 0xbe, 0xb8, 0x0b,
	0x07, 0x7d, 0x89, 0xba, 0xbc, 0x95, 0xf7, 0x76, 0x68, 0x2b, 0x8e, 0xc3, 0x56, 0x59, 0xdc, 0x2d,
	0x4b, 0x8a, 0xc2, 0xf3, 0x05, 0x36, 0x04, 0x0f, 0xc6, 0x22, 0x1b, 0x86, 0x47, 0x59, 0x92, 0xef,
	0x2e, 0x41, 0x68, 0xce, 0x95, 0xcf, 0xc1, 0x23, 0x8e, 0x30, 0x73, 0xea, 0x7c, 0x97, 0x3e, 0x6e,
	0xf1, 0xf7, 0x94, 0xb4, 0xab, 0x4c, 0x67, 0x88, 0xdd, 0xe4, 0x0c, 0x66, 0xbc, 0x96, 0x4d, 0xc4,
	0xb3, 0x6d, 0x4d, 0xc0, 0x5c, 0xfa, 0xde, 0x52, 0xcf, 0xe4, 0xb6, 0xec, 0x9a, 0xd3, 0xa8, 0xb8,
	0xea, 0xe8, 0xa5, 0x10, 0x45, 0x00, 0x40, 0x83, 0x5d, 0xb4, 0x6c, 0x17, 0x66, 0x0c, 0xd8, 0x53,
	0xb2, 0x7a, 0xde, 0xa7, 0xd7, 0x33, 0x17, 0x43, 0xd3, 0x92, 0x6e, 0xb0, 0x59, 0x0f, 0xaa, 0xb6,
	0x3d, 0xe8, 0xa2, 0xae, 0xf7, 0xe7, 0xd0, 0x35, 0x0d, 0xb0, 0x23, 0x85, 0x42, 0x6d, 0x97, 0xd9,
	0xa8, 0x9a, 0x4d, 0x04, 0xff, 0x80, 0x5e, 0xcd, 0x08, 0x1a, 0x97, 0x04, 0x0c, 0xfc, 0x63, 0x40,
	0xa5, 0xae, 0x87, 0x3e, 0x98, 0xc3, 0xf3, 0x28, 0x9a, 0xcb, 0x52, 0x81, 0x70, 0xb8, 0x15, 0xe8,
	0xd6, 0x36, 0xac, 0x30, 0x54, 0x06, 0xb4, 0xc1, 0x28, 0x90, 0xd7, 0x53, 0x16, 0xff, 0x50, 0x49,
	0xdf, 0x57, 0x0d, 0x89, 0xbd, 0x8a, 0xd0, 0x9d, 0xd6, 0x53, 0x00, 0x84, 0xd5, 0x7e, 0x45, 0xfc,
	0x11, 0xc0, 0xf1, 0xe1, 0x1c, 0x1c, 0xf4, 0x15, 0x00, 0x7c, 0x3c, 0x73, 0xcb, 0xf5, 0x91, 0x1c,
	0x9f, 0x91, 0xba, 0xe7, 0x7a, 0x3d, 0x9c, 0x79, 0x7c, 0x78, 0x07, 0xe3, 0x5d, 0xf7, 0x62, 0x7c,
	0x34, 0x07, 0xd7, 0xa2, 0x82, 0x97, 0x3a, 0xd6, 0xe4, 0x0e, 0x5b, 0xa1, 0xc3, 0x81, 0xec, 0x7f,
	0xdb, 0x72, 0xa4, 0x0d, 0x71, 0xb7, 0x68, 0x56, 0x42, 0xd8, 0x0d, 0x3c, 0xfe, 0x31, 0xfd, 0x3a,
	0x71, 0x22, 0x80, 0x87, 0xed, 0xb2, 0x84, 0xef, 0xb4, 0x0e, 0x09, 0x6c, 0xbc, 0x9c, 0x8d, 0xa0,
	0x5a, 0xf8, 0xde, 0x8f, 0xe7, 0xd0, 0x38, 0x2c, 0x13, 0x06, 0xfb, 0xdb, 0x02, 0x35, 0xe3, 0xf6,
	0xd1, 0x5c, 0x91, 0xdc, 0xcb, 0x41, 0x62, 0x20, 0x34, 0x3e, 0xab, 0x13, 0xe1, 0xb3, 0x6c, 0x35,
	0x8e, 0x5e, 0x6f, 0xe2, 0x4f, 0xe4, 0x20, 0x8e, 0x17, 0xe0, 0x76, 0x37, 0x3f, 0x24, 0xa8, 0x3a,
	0x68, 0x41, 0x52, 0x7c, 0x32, 0x47, 0x52, 0x8c, 0x92, 0x39, 0x0e, 0x15, 0x3c, 0x73, 0x98, 0x95,
	0x77, 0x44, 0xbe, 0xd3, 0xc4, 0x1e, 0xfa, 0x29, 0x7d, 0xec, 0x17, 0x53, 0xe7, 0xdc, 0xdd, 0x04,
	0x2a, 0x69, 0xb3, 0x5f, 0x9a, 0x4a, 0xbd, 0x4f, 0xe7, 0xf8, 0xd8, 0x85, 0x74, 0x14, 0x77, 0xda,
	0x69, 0xb8, 0xcb, 0xa6, 0x33, 0x69, 0x08, 0x6c, 0x9f, 0xc9, 0xc1, 0x36, 0x99, 0x4a, 0x3e, 0x60,
	0x29, 0xc2, 0x81, 0x47, 0x04, 0xd8, 0x72, 0x4d, 0x1c, 0x75, 0xf9, 0x67, 0x73, 0xc4, 0x6c, 0x32,
	0xc6, 0x14, 0x25, 0x44, 0x9e, 0x9a, 0xd2, 0x77, 0x27, 0x10, 0xf8, 0xcf, 0xe5, 0x20, 0x99, 0x48,
	0x6e, 0x54, 0x70, 0x3e, 0x9a, 0xe9, 0x3c, 0xbf, 0xf3, 0xcf, 0xe7, 0x60, 0x99, 0xca, 0x1e, 0xe9,
	0xf1, 0x04, 0x47, 0xeb, 0x1f, 0xb3, 0x7c, 0x21, 0x8f, 0x16, 0xc2, 0x28, 0x8e, 0xa7, 0x59, 0x21,
	0x0e, 0x6d, 0x7b, 0x23, 0xaf, 0xfb, 0x22, 0x08, 0x30, 0xca, 0x5f, 0xcc, 0x11, 0xe5, 0xf3, 0x0a,
	0x1f, 0xef, 0xee, 0xd7, 0x25, 0x5a, 0xc6, 0xfb, 0x49, 0x66, 0xc0, 0xe1, 0x2f, 0x9b, 0xfa, 0x01,
	0xff, 0x52, 0x49, 0x3f, 0x37, 0xcd, 0x00, 0x2e, 0x9d, 0xef, 0x81, 0x0c, 0x99, 0x5c, 0xf9, 0xcc,
	0x26, 0xf5, 0xe5, 0x1c, 0xe2, 0xa6, 0x00, 0x75, 0x98, 0xda, 0xa7, 0x40, 0x53, 0x7b, 0x9f, 0x4a,
	0x6a, 0xe7, 0x2b, 0x39, 0xc2, 0x36, 0x13, 0xe3, 0x0e, 0xe3, 0x1a, 0x82, 0xe6, 0x98, 0x5d, 0xc6,
	0x74, 0x11, 0x7d, 0x55, 0x5f, 0x44, 0xe7, 0xd3, 0xcb, 0x99, 0xae, 0x22, 0xa8, 0xeb, 0x64, 0x09,
	0xbe, 0x96, 0x67, 0xe3, 0xa9, 0xc7, 0x31, 0x87, 0x63, 0x5b, 0xe4, 0x39, 0x50, 0x22, 0xad, 0x46,
	0x55, 0xb8, 0xfc, 0xeb, 0x7a, 0x15, 0x4c, 0xda, 0x1f, 0xa1, 0x39, 0x76, 0x85, 0x54, 0x9d, 0x65,
	0xa2, 0xfd, 0x8d, 0x3c, 0xe5, 0x9b, 0x14, 0x5c, 0x3a, 0xe8, 0x15, 0xb6, 0x56, 0x83, 0xa3, 0x88,
	0x68, 0xc8, 0x6b, 0xcf, 0xcc, 0x5d, 0x8f, 0x89, 0x2c, 0xdb, 0xfc, 0x9b, 0x7a, 0x9d, 0x2b, 0x31,
	0x45, 0xf6, 0xb6, 0x08, 0x5f, 0x6e, 0xcb, 0x75, 0x6d, 0x46, 0x55, 0x17, 0x18, 0xd3, 0x8b, 0xf0,
	0xad, 0x52, 0x8e, 0x8b, 0x3e, 0x84, 0xa5, 0xc3, 0xff, 0xea, 0xec, 0xef, 0x6c, 0xbe, 0x5d, 0x3a,
	0xdb, 0x2f, 0x6d, 0x74, 0x5f, 0x7b, 0x89, 0x7f, 0xe7, 0xff, 0xfb, 0xda, 0x4b, 0x72, 0x36, 0x8a,
	0xd7, 0x29, 0x49, 0x94, 0xef, 0xe6, 0x99, 0x8d, 0x14, 0x2c, 0x5d, 0xa3, 0x3d, 0xca, 0xfe, 0x7b,
	0x39, 0xa8, 0x66, 0x6a, 0x9d, 0xf5, 0x7e, 0xc4, 0xce, 0x77, 0x6d, 0x73, 0xaa, 0xf7, 0x7f, 0x3f,
	0x07, 0xe1, 0x7c, 0xc7, 0x0e, 0x4a, 0xad, 0xff, 0x0a, 0x9b, 0xcc, 0x4e, 0x1d, 0x3f, 0xc8, 0x41,
	0x35, 0x11, 0xf4, 0x9d, 0x35, 0x2e, 0x75, 0xcf, 0x1a, 0x3f, 0x3c, 0xcb, 0xac, 0x71, 0xa9, 0x63,
	0xd6, 0x90, 0x5b, 0x53, 0xf6, 0x56, 0x98, 0xff, 0x28, 0xd7, 0xae, 0x92, 0xbe, 0x28, 0x36, 0xaa,
	0xec, 0x42, 0xef, 0x49, 0x21, 0x59, 0x93, 0x1f, 0xe7, 0xf8, 0xee, 0xe5, 0x1e, 0xb3, 0x42, 0x7b,
	0x79, 0x52, 0xc5, 0xdd, 0x5e, 0xf2, 0x78, 0x37, 0xfd, 0xc9, 0x19, 0x8a, 0x3b, 0xee, 0xf3, 0x6a,
	0x57, 0x85, 0x8e, 0x93, 0xda, 0x10, 0xf9, 0x4f, 0x73, 0x74, 0x9c, 0x64, 0x33, 0x94, 0x7d, 0xbd,
	0x4b, 0xcc, 0xcf, 0xf2, 0xf4, 0xf5, 0x5a, 0x56, 0x45, 0x57, 0xee, 0x25, 0x81, 0xfb, 0xf9, 0x59,
	0x73, 0x2f, 0x8e, 0xd8, 0xce, 0x1d, 0xb6, 0xec, 0x88, 0x8e, 0x23, 0x5c, 0xf2, 0xb7, 0x01, 0xcf,
	0x3c, 0x51, 0x17, 0x81, 0xf5, 0x5c, 0xfc, 0xde, 0x3a, 0xdb, 0x9f, 0x0f, 0x54, 0x87, 0xf1, 0x77,
	0xf4, 0x2f, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x84, 0x6f, 0x7d, 0x8f, 0x7c, 0x20, 0x00,
	0x00,
}
