// Code generated by protoc-gen-go.
// source: dstore/engine/procedures/om_GetCampaignItemConds_Ad.proto
// DO NOT EDIT!

/*
Package om_GetCampaignItemConds_Ad is a generated protocol buffer package.

It is generated from these files:
	dstore/engine/procedures/om_GetCampaignItemConds_Ad.proto

It has these top-level messages:
	Parameters
	Response
*/
package om_GetCampaignItemConds_Ad

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_values "gosdk.dstore.de/values"
import dstore_engine_error "gosdk.dstore.de/engine/error"
import dstore_engine_message "gosdk.dstore.de/engine/message"
import dstore_engine_metainformation "gosdk.dstore.de/engine/metainformation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameters struct {
	ConditionId             *dstore_values.IntegerValue `protobuf:"bytes,1,opt,name=condition_id,json=conditionId" json:"condition_id,omitempty"`
	ConditionIdNull         bool                        `protobuf:"varint,1001,opt,name=condition_id_null,json=conditionIdNull" json:"condition_id_null,omitempty"`
	ItemConditionId         *dstore_values.IntegerValue `protobuf:"bytes,2,opt,name=item_condition_id,json=itemConditionId" json:"item_condition_id,omitempty"`
	ItemConditionIdNull     bool                        `protobuf:"varint,1002,opt,name=item_condition_id_null,json=itemConditionIdNull" json:"item_condition_id_null,omitempty"`
	GetUnusedConditions     *dstore_values.BooleanValue `protobuf:"bytes,3,opt,name=get_unused_conditions,json=getUnusedConditions" json:"get_unused_conditions,omitempty"`
	GetUnusedConditionsNull bool                        `protobuf:"varint,1003,opt,name=get_unused_conditions_null,json=getUnusedConditionsNull" json:"get_unused_conditions_null,omitempty"`
}

func (m *Parameters) Reset()                    { *m = Parameters{} }
func (m *Parameters) String() string            { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()               {}
func (*Parameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameters) GetConditionId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ConditionId
	}
	return nil
}

func (m *Parameters) GetItemConditionId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemConditionId
	}
	return nil
}

func (m *Parameters) GetGetUnusedConditions() *dstore_values.BooleanValue {
	if m != nil {
		return m.GetUnusedConditions
	}
	return nil
}

type Response struct {
	Error           *dstore_engine_error.Error                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	MetaInformation []*dstore_engine_metainformation.MetaInformation `protobuf:"bytes,2,rep,name=meta_information,json=metaInformation" json:"meta_information,omitempty"`
	Message         []*dstore_engine_message.Message                 `protobuf:"bytes,3,rep,name=message" json:"message,omitempty"`
	Row             []*Response_Row                                  `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_engine_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetMetaInformation() []*dstore_engine_metainformation.MetaInformation {
	if m != nil {
		return m.MetaInformation
	}
	return nil
}

func (m *Response) GetMessage() []*dstore_engine_message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetRow() []*Response_Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type Response_Row struct {
	RowId                         int32                       `protobuf:"varint,10000,opt,name=row_id,json=rowId" json:"row_id,omitempty"`
	ConditionDescription          *dstore_values.StringValue  `protobuf:"bytes,10001,opt,name=condition_description,json=conditionDescription" json:"condition_description,omitempty"`
	Condition1                    *dstore_values.StringValue  `protobuf:"bytes,10002,opt,name=condition1" json:"condition1,omitempty"`
	Condition2                    *dstore_values.StringValue  `protobuf:"bytes,10003,opt,name=condition2" json:"condition2,omitempty"`
	ToBasicPriceSumGroup          *dstore_values.DecimalValue `protobuf:"bytes,10004,opt,name=to_basic_price_sum_group,json=toBasicPriceSumGroup" json:"to_basic_price_sum_group,omitempty"`
	RecursiveEvaluation           *dstore_values.IntegerValue `protobuf:"bytes,10005,opt,name=recursive_evaluation,json=recursiveEvaluation" json:"recursive_evaluation,omitempty"`
	ToBasicPriceSumPart           *dstore_values.DecimalValue `protobuf:"bytes,10006,opt,name=to_basic_price_sum_part,json=toBasicPriceSumPart" json:"to_basic_price_sum_part,omitempty"`
	MaxNumberOfItemsGroup         *dstore_values.IntegerValue `protobuf:"bytes,10007,opt,name=max_number_of_items_group,json=maxNumberOfItemsGroup" json:"max_number_of_items_group,omitempty"`
	DomainTreeNodeIds             *dstore_values.StringValue  `protobuf:"bytes,10008,opt,name=domain_tree_node_ids,json=domainTreeNodeIds" json:"domain_tree_node_ids,omitempty"`
	NodeCharacteristicId          *dstore_values.IntegerValue `protobuf:"bytes,10009,opt,name=node_characteristic_id,json=nodeCharacteristicId" json:"node_characteristic_id,omitempty"`
	ItemConditionPartId           *dstore_values.IntegerValue `protobuf:"bytes,10010,opt,name=item_condition_part_id,json=itemConditionPartId" json:"item_condition_part_id,omitempty"`
	FromBasicPriceSumPart         *dstore_values.DecimalValue `protobuf:"bytes,10011,opt,name=from_basic_price_sum_part,json=fromBasicPriceSumPart" json:"from_basic_price_sum_part,omitempty"`
	ToQuantity                    *dstore_values.IntegerValue `protobuf:"bytes,10012,opt,name=to_quantity,json=toQuantity" json:"to_quantity,omitempty"`
	FromQuantityGroup             *dstore_values.IntegerValue `protobuf:"bytes,10013,opt,name=from_quantity_group,json=fromQuantityGroup" json:"from_quantity_group,omitempty"`
	ItemConditionId               *dstore_values.IntegerValue `protobuf:"bytes,10014,opt,name=item_condition_id,json=itemConditionId" json:"item_condition_id,omitempty"`
	MaxNumberOfItems              *dstore_values.IntegerValue `protobuf:"bytes,10015,opt,name=max_number_of_items,json=maxNumberOfItems" json:"max_number_of_items,omitempty"`
	CombineGroupsWithANDOperator  *dstore_values.BooleanValue `protobuf:"bytes,10016,opt,name=combine_groups_with_a_n_d_operator,json=combineGroupsWithANDOperator" json:"combine_groups_with_a_n_d_operator,omitempty"`
	FromBasicPriceSumGroup        *dstore_values.DecimalValue `protobuf:"bytes,10017,opt,name=from_basic_price_sum_group,json=fromBasicPriceSumGroup" json:"from_basic_price_sum_group,omitempty"`
	ToItemBasicPricePart          *dstore_values.DecimalValue `protobuf:"bytes,10018,opt,name=to_item_basic_price_part,json=toItemBasicPricePart" json:"to_item_basic_price_part,omitempty"`
	ItemConditionPartDescription  *dstore_values.StringValue  `protobuf:"bytes,10019,opt,name=item_condition_part_description,json=itemConditionPartDescription" json:"item_condition_part_description,omitempty"`
	LevelIds                      *dstore_values.StringValue  `protobuf:"bytes,10020,opt,name=level_ids,json=levelIds" json:"level_ids,omitempty"`
	ItemConditionGroupId          *dstore_values.IntegerValue `protobuf:"bytes,10021,opt,name=item_condition_group_id,json=itemConditionGroupId" json:"item_condition_group_id,omitempty"`
	ExtendedItemCondGroupDescr    *dstore_values.StringValue  `protobuf:"bytes,10022,opt,name=extended_item_cond_group_descr,json=extendedItemCondGroupDescr" json:"extended_item_cond_group_descr,omitempty"`
	FromQuantity                  *dstore_values.IntegerValue `protobuf:"bytes,10023,opt,name=from_quantity,json=fromQuantity" json:"from_quantity,omitempty"`
	FromItemBasicPrice            *dstore_values.DecimalValue `protobuf:"bytes,10024,opt,name=from_item_basic_price,json=fromItemBasicPrice" json:"from_item_basic_price,omitempty"`
	ItemGroupSortNo               *dstore_values.IntegerValue `protobuf:"bytes,10025,opt,name=item_group_sort_no,json=itemGroupSortNo" json:"item_group_sort_no,omitempty"`
	Operator1                     *dstore_values.StringValue  `protobuf:"bytes,10026,opt,name=operator1" json:"operator1,omitempty"`
	Operator2                     *dstore_values.StringValue  `protobuf:"bytes,10027,opt,name=operator2" json:"operator2,omitempty"`
	ItemConditionGroupDescription *dstore_values.StringValue  `protobuf:"bytes,10028,opt,name=item_condition_group_description,json=itemConditionGroupDescription" json:"item_condition_group_description,omitempty"`
	CombinePartsWithANDOperator   *dstore_values.BooleanValue `protobuf:"bytes,10029,opt,name=combine_parts_with_a_n_d_operator,json=combinePartsWithANDOperator" json:"combine_parts_with_a_n_d_operator,omitempty"`
	MinNumberOfItemsPart          *dstore_values.IntegerValue `protobuf:"bytes,10030,opt,name=min_number_of_items_part,json=minNumberOfItemsPart" json:"min_number_of_items_part,omitempty"`
	ItemPartSortNo                *dstore_values.IntegerValue `protobuf:"bytes,10031,opt,name=item_part_sort_no,json=itemPartSortNo" json:"item_part_sort_no,omitempty"`
	ToItemBasicPriceGroup         *dstore_values.DecimalValue `protobuf:"bytes,10032,opt,name=to_item_basic_price_group,json=toItemBasicPriceGroup" json:"to_item_basic_price_group,omitempty"`
	ExtendedItemCondPartDescr     *dstore_values.StringValue  `protobuf:"bytes,10033,opt,name=extended_item_cond_part_descr,json=extendedItemCondPartDescr" json:"extended_item_cond_part_descr,omitempty"`
	MaxNumberOfItemsPart          *dstore_values.IntegerValue `protobuf:"bytes,10034,opt,name=max_number_of_items_part,json=maxNumberOfItemsPart" json:"max_number_of_items_part,omitempty"`
	FromItemBasicPricePart        *dstore_values.DecimalValue `protobuf:"bytes,10035,opt,name=from_item_basic_price_part,json=fromItemBasicPricePart" json:"from_item_basic_price_part,omitempty"`
	MinNumberOfItems              *dstore_values.IntegerValue `protobuf:"bytes,10036,opt,name=min_number_of_items,json=minNumberOfItems" json:"min_number_of_items,omitempty"`
	FromBasicPriceSum             *dstore_values.DecimalValue `protobuf:"bytes,10037,opt,name=from_basic_price_sum,json=fromBasicPriceSum" json:"from_basic_price_sum,omitempty"`
	ToBasicPriceSum               *dstore_values.DecimalValue `protobuf:"bytes,10038,opt,name=to_basic_price_sum,json=toBasicPriceSum" json:"to_basic_price_sum,omitempty"`
	ToQuantityGroup               *dstore_values.IntegerValue `protobuf:"bytes,10039,opt,name=to_quantity_group,json=toQuantityGroup" json:"to_quantity_group,omitempty"`
	FromItemBasicPriceGroup       *dstore_values.DecimalValue `protobuf:"bytes,10040,opt,name=from_item_basic_price_group,json=fromItemBasicPriceGroup" json:"from_item_basic_price_group,omitempty"`
	ConditionId                   *dstore_values.IntegerValue `protobuf:"bytes,10041,opt,name=condition_id,json=conditionId" json:"condition_id,omitempty"`
	ItemConditionDescription      *dstore_values.StringValue  `protobuf:"bytes,10042,opt,name=item_condition_description,json=itemConditionDescription" json:"item_condition_description,omitempty"`
	ToItemBasicPrice              *dstore_values.DecimalValue `protobuf:"bytes,10043,opt,name=to_item_basic_price,json=toItemBasicPrice" json:"to_item_basic_price,omitempty"`
	ToQuantityPart                *dstore_values.IntegerValue `protobuf:"bytes,10044,opt,name=to_quantity_part,json=toQuantityPart" json:"to_quantity_part,omitempty"`
	FromQuantityPart              *dstore_values.IntegerValue `protobuf:"bytes,10045,opt,name=from_quantity_part,json=fromQuantityPart" json:"from_quantity_part,omitempty"`
	MinNumberOfItemsGroup         *dstore_values.IntegerValue `protobuf:"bytes,10046,opt,name=min_number_of_items_group,json=minNumberOfItemsGroup" json:"min_number_of_items_group,omitempty"`
	InheritDepth                  *dstore_values.IntegerValue `protobuf:"bytes,10047,opt,name=inherit_depth,json=inheritDepth" json:"inherit_depth,omitempty"`
}

func (m *Response_Row) Reset()                    { *m = Response_Row{} }
func (m *Response_Row) String() string            { return proto.CompactTextString(m) }
func (*Response_Row) ProtoMessage()               {}
func (*Response_Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Row) GetConditionDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ConditionDescription
	}
	return nil
}

func (m *Response_Row) GetCondition1() *dstore_values.StringValue {
	if m != nil {
		return m.Condition1
	}
	return nil
}

func (m *Response_Row) GetCondition2() *dstore_values.StringValue {
	if m != nil {
		return m.Condition2
	}
	return nil
}

func (m *Response_Row) GetToBasicPriceSumGroup() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToBasicPriceSumGroup
	}
	return nil
}

func (m *Response_Row) GetRecursiveEvaluation() *dstore_values.IntegerValue {
	if m != nil {
		return m.RecursiveEvaluation
	}
	return nil
}

func (m *Response_Row) GetToBasicPriceSumPart() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToBasicPriceSumPart
	}
	return nil
}

func (m *Response_Row) GetMaxNumberOfItemsGroup() *dstore_values.IntegerValue {
	if m != nil {
		return m.MaxNumberOfItemsGroup
	}
	return nil
}

func (m *Response_Row) GetDomainTreeNodeIds() *dstore_values.StringValue {
	if m != nil {
		return m.DomainTreeNodeIds
	}
	return nil
}

func (m *Response_Row) GetNodeCharacteristicId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeCharacteristicId
	}
	return nil
}

func (m *Response_Row) GetItemConditionPartId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemConditionPartId
	}
	return nil
}

func (m *Response_Row) GetFromBasicPriceSumPart() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromBasicPriceSumPart
	}
	return nil
}

func (m *Response_Row) GetToQuantity() *dstore_values.IntegerValue {
	if m != nil {
		return m.ToQuantity
	}
	return nil
}

func (m *Response_Row) GetFromQuantityGroup() *dstore_values.IntegerValue {
	if m != nil {
		return m.FromQuantityGroup
	}
	return nil
}

func (m *Response_Row) GetItemConditionId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemConditionId
	}
	return nil
}

func (m *Response_Row) GetMaxNumberOfItems() *dstore_values.IntegerValue {
	if m != nil {
		return m.MaxNumberOfItems
	}
	return nil
}

func (m *Response_Row) GetCombineGroupsWithANDOperator() *dstore_values.BooleanValue {
	if m != nil {
		return m.CombineGroupsWithANDOperator
	}
	return nil
}

func (m *Response_Row) GetFromBasicPriceSumGroup() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromBasicPriceSumGroup
	}
	return nil
}

func (m *Response_Row) GetToItemBasicPricePart() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToItemBasicPricePart
	}
	return nil
}

func (m *Response_Row) GetItemConditionPartDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ItemConditionPartDescription
	}
	return nil
}

func (m *Response_Row) GetLevelIds() *dstore_values.StringValue {
	if m != nil {
		return m.LevelIds
	}
	return nil
}

func (m *Response_Row) GetItemConditionGroupId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemConditionGroupId
	}
	return nil
}

func (m *Response_Row) GetExtendedItemCondGroupDescr() *dstore_values.StringValue {
	if m != nil {
		return m.ExtendedItemCondGroupDescr
	}
	return nil
}

func (m *Response_Row) GetFromQuantity() *dstore_values.IntegerValue {
	if m != nil {
		return m.FromQuantity
	}
	return nil
}

func (m *Response_Row) GetFromItemBasicPrice() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromItemBasicPrice
	}
	return nil
}

func (m *Response_Row) GetItemGroupSortNo() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemGroupSortNo
	}
	return nil
}

func (m *Response_Row) GetOperator1() *dstore_values.StringValue {
	if m != nil {
		return m.Operator1
	}
	return nil
}

func (m *Response_Row) GetOperator2() *dstore_values.StringValue {
	if m != nil {
		return m.Operator2
	}
	return nil
}

func (m *Response_Row) GetItemConditionGroupDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ItemConditionGroupDescription
	}
	return nil
}

func (m *Response_Row) GetCombinePartsWithANDOperator() *dstore_values.BooleanValue {
	if m != nil {
		return m.CombinePartsWithANDOperator
	}
	return nil
}

func (m *Response_Row) GetMinNumberOfItemsPart() *dstore_values.IntegerValue {
	if m != nil {
		return m.MinNumberOfItemsPart
	}
	return nil
}

func (m *Response_Row) GetItemPartSortNo() *dstore_values.IntegerValue {
	if m != nil {
		return m.ItemPartSortNo
	}
	return nil
}

func (m *Response_Row) GetToItemBasicPriceGroup() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToItemBasicPriceGroup
	}
	return nil
}

func (m *Response_Row) GetExtendedItemCondPartDescr() *dstore_values.StringValue {
	if m != nil {
		return m.ExtendedItemCondPartDescr
	}
	return nil
}

func (m *Response_Row) GetMaxNumberOfItemsPart() *dstore_values.IntegerValue {
	if m != nil {
		return m.MaxNumberOfItemsPart
	}
	return nil
}

func (m *Response_Row) GetFromItemBasicPricePart() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromItemBasicPricePart
	}
	return nil
}

func (m *Response_Row) GetMinNumberOfItems() *dstore_values.IntegerValue {
	if m != nil {
		return m.MinNumberOfItems
	}
	return nil
}

func (m *Response_Row) GetFromBasicPriceSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromBasicPriceSum
	}
	return nil
}

func (m *Response_Row) GetToBasicPriceSum() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToBasicPriceSum
	}
	return nil
}

func (m *Response_Row) GetToQuantityGroup() *dstore_values.IntegerValue {
	if m != nil {
		return m.ToQuantityGroup
	}
	return nil
}

func (m *Response_Row) GetFromItemBasicPriceGroup() *dstore_values.DecimalValue {
	if m != nil {
		return m.FromItemBasicPriceGroup
	}
	return nil
}

func (m *Response_Row) GetConditionId() *dstore_values.IntegerValue {
	if m != nil {
		return m.ConditionId
	}
	return nil
}

func (m *Response_Row) GetItemConditionDescription() *dstore_values.StringValue {
	if m != nil {
		return m.ItemConditionDescription
	}
	return nil
}

func (m *Response_Row) GetToItemBasicPrice() *dstore_values.DecimalValue {
	if m != nil {
		return m.ToItemBasicPrice
	}
	return nil
}

func (m *Response_Row) GetToQuantityPart() *dstore_values.IntegerValue {
	if m != nil {
		return m.ToQuantityPart
	}
	return nil
}

func (m *Response_Row) GetFromQuantityPart() *dstore_values.IntegerValue {
	if m != nil {
		return m.FromQuantityPart
	}
	return nil
}

func (m *Response_Row) GetMinNumberOfItemsGroup() *dstore_values.IntegerValue {
	if m != nil {
		return m.MinNumberOfItemsGroup
	}
	return nil
}

func (m *Response_Row) GetInheritDepth() *dstore_values.IntegerValue {
	if m != nil {
		return m.InheritDepth
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "dstore.engine.om_GetCampaignItemConds_Ad.Parameters")
	proto.RegisterType((*Response)(nil), "dstore.engine.om_GetCampaignItemConds_Ad.Response")
	proto.RegisterType((*Response_Row)(nil), "dstore.engine.om_GetCampaignItemConds_Ad.Response.Row")
}

func init() {
	proto.RegisterFile("dstore/engine/procedures/om_GetCampaignItemConds_Ad.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x58, 0x49, 0x73, 0xdc, 0x44,
	0x14, 0xae, 0x60, 0x9c, 0x38, 0xed, 0x80, 0xed, 0x1e, 0x2f, 0xed, 0x71, 0x1c, 0x8c, 0xb9, 0xa4,
	0x8a, 0xaa, 0x31, 0x31, 0x14, 0x95, 0x14, 0x01, 0xca, 0xb1, 0x83, 0x63, 0xc0, 0xb2, 0x33, 0x0e,
	0x81, 0x84, 0xa2, 0x54, 0x9a, 0x51, 0x7b, 0xac, 0x62, 0xa4, 0x1e, 0xba, 0x35, 0x76, 0x38, 0x73,
	0xe0, 0xca, 0xbe, 0xef, 0xfb, 0xbe, 0xef, 0xeb, 0xaf, 0xe1, 0x00, 0xfc, 0x09, 0x5e, 0x77, 0x4b,
	0x33, 0xda, 0x28, 0xb5, 0x73, 0x49, 0x4a, 0x56, 0x7f, 0x5f, 0xbf, 0x7e, 0xef, 0x7b, 0xdf, 0x6b,
	0x0d, 0x3a, 0xe5, 0x8a, 0x90, 0x71, 0xba, 0x40, 0x83, 0x96, 0x17, 0xd0, 0x85, 0x0e, 0x67, 0x4d,
	0xea, 0x76, 0x39, 0x15, 0x0b, 0xcc, 0xb7, 0x57, 0x69, 0xb8, 0xec, 0xf8, 0x1d, 0xc7, 0x6b, 0x05,
	0x6b, 0x21, 0xf5, 0x97, 0x59, 0xe0, 0x0a, 0x7b, 0xc9, 0xad, 0xc1, 0xaa, 0x90, 0xe1, 0xe3, 0x1a,
	0x5a, 0xd3, 0xd0, 0xda, 0xff, 0xaf, 0xaf, 0x56, 0xa2, 0x4d, 0x76, 0x9d, 0x76, 0x97, 0x0a, 0x0d,
	0xaf, 0x4e, 0xa7, 0x77, 0xa6, 0x9c, 0x33, 0x1e, 0xbd, 0x9a, 0x49, 0xbf, 0xf2, 0xa9, 0x10, 0x4e,
	0x8b, 0x46, 0x2f, 0x6f, 0xca, 0xbe, 0x0c, 0x1d, 0x2f, 0xd8, 0x66, 0xdc, 0x77, 0x42, 0x8f, 0x05,
	0x7a, 0xd1, 0xfc, 0x93, 0x03, 0x08, 0x6d, 0x3a, 0xdc, 0x81, 0xb7, 0x94, 0x0b, 0x7c, 0x17, 0x3a,
	0xd2, 0x84, 0x60, 0x3c, 0xb9, 0xc2, 0xf6, 0x5c, 0x72, 0x60, 0xee, 0xc0, 0xf1, 0xe1, 0xc5, 0x99,
	0x5a, 0x74, 0x82, 0x28, 0x2e, 0x2f, 0x08, 0x69, 0x8b, 0xf2, 0x8b, 0xf2, 0xa9, 0x3e, 0xdc, 0x03,
	0xac, 0xb9, 0xf8, 0x66, 0x34, 0x96, 0xc4, 0xdb, 0x41, 0xb7, 0xdd, 0x26, 0x7f, 0x1f, 0x02, 0x96,
	0xa1, 0xfa, 0x48, 0x62, 0xa1, 0x05, 0x7f, 0xc7, 0xab, 0x68, 0xcc, 0x83, 0xd3, 0xdb, 0xa9, 0x1d,
	0xaf, 0x29, 0xdf, 0x71, 0xc4, 0x8b, 0x72, 0x16, 0xef, 0x7a, 0x1b, 0x9a, 0xcc, 0x11, 0xe9, 0xad,
	0xff, 0xd1, 0x5b, 0x57, 0x32, 0x08, 0xb5, 0xfd, 0x06, 0x9a, 0x68, 0xd1, 0xd0, 0xee, 0x06, 0x5d,
	0x41, 0xdd, 0x3e, 0x56, 0x90, 0x81, 0xc2, 0x10, 0x1a, 0x8c, 0xb5, 0xa9, 0x13, 0xe8, 0x10, 0x2a,
	0x80, 0x7c, 0x40, 0x01, 0x7b, 0xac, 0x02, 0x9f, 0x46, 0xd5, 0x42, 0x42, 0x1d, 0xca, 0xbf, 0x3a,
	0x94, 0xa9, 0x02, 0xa4, 0x0c, 0x67, 0xfe, 0x89, 0x39, 0x34, 0x54, 0xa7, 0xa2, 0x03, 0xcf, 0x14,
	0xdf, 0x82, 0x06, 0x55, 0x9d, 0xa3, 0x02, 0x54, 0x6b, 0x69, 0x09, 0x69, 0x0d, 0x9c, 0x95, 0xff,
	0xd6, 0xf5, 0x42, 0x7c, 0x09, 0x8d, 0xca, 0x0a, 0xdb, 0x89, 0x12, 0x43, 0x2e, 0x07, 0x00, 0x5c,
	0xcb, 0x80, 0xb3, 0x42, 0x58, 0x87, 0xe7, 0xb5, 0xfe, 0x73, 0x7d, 0xc4, 0x4f, 0xff, 0x01, 0x9f,
	0x44, 0x87, 0x22, 0x65, 0x41, 0x6a, 0x24, 0xe3, 0xb1, 0x1c, 0xa3, 0xd6, 0xdd, 0xba, 0xfe, 0xbf,
	0x1e, 0x2f, 0xc7, 0xe7, 0xd0, 0x00, 0x67, 0x7b, 0xe4, 0x5a, 0x85, 0xba, 0xbd, 0x66, 0xda, 0x07,
	0xb5, 0x38, 0x0f, 0xb5, 0x3a, 0xdb, 0xab, 0x4b, 0x8a, 0xea, 0x5f, 0xb3, 0x68, 0x00, 0x1e, 0xf0,
	0x24, 0x3a, 0x08, 0x8f, 0x52, 0x28, 0x4f, 0x59, 0x90, 0x9a, 0xc1, 0xfa, 0x20, 0x3c, 0x82, 0x04,
	0x36, 0xd1, 0x44, 0xbf, 0xfa, 0x2e, 0x15, 0x4d, 0xee, 0x75, 0x54, 0x0e, 0x9e, 0xb6, 0xd2, 0x19,
	0x8c, 0xaa, 0x29, 0x42, 0xee, 0x05, 0x2d, 0x5d, 0xcc, 0xf1, 0x1e, 0x72, 0xa5, 0x0f, 0xc4, 0x77,
	0x20, 0xd4, 0xfb, 0xfb, 0x09, 0xf2, 0x4c, 0x39, 0x4d, 0x62, 0x79, 0x0a, 0xbc, 0x48, 0x9e, 0xdd,
	0x0f, 0x78, 0x11, 0x5f, 0x40, 0x24, 0x64, 0x76, 0xc3, 0x11, 0x5e, 0xd3, 0xee, 0x70, 0xaf, 0x49,
	0x6d, 0xd1, 0xf5, 0xed, 0x16, 0x67, 0xdd, 0x0e, 0x79, 0xce, 0x2a, 0x14, 0xa7, 0x4b, 0x9b, 0x9e,
	0xef, 0xb4, 0xa3, 0xf3, 0x84, 0xec, 0x8c, 0x04, 0x6f, 0x4a, 0xec, 0x56, 0xd7, 0x5f, 0x95, 0x48,
	0x90, 0xfb, 0x38, 0xa7, 0xcd, 0x2e, 0x17, 0xde, 0x2e, 0xb5, 0xa9, 0xc4, 0x69, 0x91, 0x3c, 0x6f,
	0x95, 0x77, 0x5c, 0xa5, 0x87, 0x3c, 0xdb, 0x03, 0xe2, 0x3a, 0x9a, 0x2a, 0x08, 0xb3, 0xe3, 0xf0,
	0x90, 0xbc, 0x60, 0x10, 0x65, 0x25, 0x13, 0x25, 0xb8, 0x50, 0x88, 0x2f, 0xa2, 0x69, 0xdf, 0xb9,
	0x02, 0x0d, 0xe3, 0x37, 0x28, 0xb7, 0xd9, 0xb6, 0x2d, 0x1b, 0x57, 0x44, 0x67, 0x7f, 0xd1, 0x20,
	0xd2, 0x09, 0x80, 0x5b, 0x0a, 0xbd, 0xb1, 0x2d, 0x25, 0x25, 0xf4, 0xe1, 0xef, 0x47, 0xe3, 0x2e,
	0xf3, 0x41, 0xf6, 0x76, 0xc8, 0x29, 0xb5, 0x03, 0xe6, 0x52, 0xd0, 0x90, 0x20, 0x2f, 0x95, 0x57,
	0x66, 0x4c, 0x03, 0x2f, 0x00, 0xce, 0x02, 0xd8, 0x9a, 0x2b, 0xe0, 0xe4, 0x93, 0x8a, 0xa1, 0xb9,
	0x03, 0xce, 0xd9, 0x04, 0xe3, 0xf4, 0x44, 0x08, 0x49, 0x00, 0x51, 0xbe, 0x6c, 0x10, 0xe2, 0xb8,
	0xc4, 0x2e, 0xa7, 0xa0, 0x20, 0xe0, 0xf3, 0x39, 0x0f, 0x93, 0x99, 0x94, 0x9c, 0xaf, 0x98, 0x14,
	0x28, 0x65, 0x70, 0x32, 0x95, 0x40, 0x09, 0xc9, 0xdc, 0xe6, 0xd0, 0x65, 0x85, 0x25, 0x7a, 0xd5,
	0xa0, 0x44, 0x13, 0x12, 0x9e, 0x2f, 0xd2, 0x9d, 0x68, 0x18, 0x0a, 0xff, 0x58, 0xd7, 0x09, 0x42,
	0x2f, 0x7c, 0x9c, 0xbc, 0x66, 0x10, 0x1f, 0x0a, 0xd9, 0xf9, 0x68, 0x3d, 0xd4, 0xa2, 0xa2, 0xc2,
	0x8a, 0x09, 0xa2, 0xea, 0xbe, 0x6e, 0x40, 0x33, 0x26, 0x81, 0x31, 0x91, 0xae, 0xec, 0xb9, 0xa2,
	0x21, 0xf2, 0x86, 0x75, 0x15, 0x53, 0xe4, 0x3e, 0x54, 0x29, 0xd0, 0x1e, 0x79, 0xd3, 0x80, 0x6b,
	0x34, 0xab, 0x3a, 0xbc, 0x8d, 0xe6, 0x9b, 0xcc, 0x6f, 0x80, 0xcf, 0xe9, 0xe3, 0x09, 0x7b, 0xcf,
	0x0b, 0x77, 0x6c, 0xc7, 0x06, 0x77, 0xb2, 0x59, 0x87, 0x72, 0x07, 0xc8, 0xc8, 0x5b, 0x56, 0xf9,
	0xa8, 0x39, 0x1a, 0xf1, 0xa8, 0xe3, 0x8a, 0x07, 0x81, 0x65, 0xc9, 0x5a, 0xd9, 0x88, 0x18, 0xf0,
	0x43, 0xa8, 0x5a, 0x58, 0x63, 0x9d, 0xd3, 0xb7, 0x0d, 0x8a, 0x3c, 0x99, 0x2b, 0xb2, 0x4e, 0xac,
	0x76, 0x21, 0x95, 0xdb, 0x24, 0xb9, 0x12, 0xcf, 0x3b, 0x66, 0x2e, 0x24, 0x53, 0xd1, 0x67, 0x56,
	0xda, 0x69, 0xa0, 0x1b, 0x8a, 0x64, 0x9e, 0x74, 0xec, 0x77, 0xcb, 0x7b, 0xf2, 0x68, 0x4e, 0xee,
	0x49, 0xe7, 0x3e, 0x89, 0x0e, 0xb7, 0xe9, 0x2e, 0x6d, 0xab, 0x0e, 0x7f, 0xaf, 0x9c, 0x6d, 0x48,
	0xad, 0x96, 0x8d, 0xbd, 0x85, 0xa6, 0x32, 0xd1, 0xa9, 0x3c, 0x4a, 0x49, 0xbd, 0x6f, 0xd2, 0xd9,
	0xa9, 0xb0, 0x54, 0x1a, 0x41, 0x57, 0x36, 0x3a, 0x46, 0xaf, 0x84, 0x34, 0x70, 0xe1, 0x52, 0xd0,
	0x63, 0x8f, 0x88, 0xd5, 0xb9, 0xc9, 0x07, 0xe5, 0x31, 0x56, 0x63, 0x8a, 0x78, 0x4e, 0x2a, 0x76,
	0x75, 0x6a, 0xbc, 0x84, 0xae, 0x4b, 0x35, 0x14, 0xf9, 0xd0, 0x20, 0xd6, 0x23, 0xc9, 0x56, 0x92,
	0x77, 0x21, 0x45, 0x91, 0x2d, 0x37, 0xf9, 0xc8, 0xa0, 0xd2, 0x58, 0x42, 0xd3, 0xb5, 0xc6, 0x6b,
	0x08, 0x2b, 0x2e, 0x7d, 0x4c, 0xc1, 0xa0, 0xc6, 0x01, 0x23, 0x1f, 0x9b, 0xf6, 0xa5, 0x3a, 0xdd,
	0x16, 0xa0, 0x2c, 0x86, 0x4f, 0xa1, 0xc3, 0x71, 0xc3, 0x9c, 0x20, 0x9f, 0x94, 0xa7, 0xaa, 0xbf,
	0x3a, 0x09, 0x5d, 0x24, 0x9f, 0xee, 0x03, 0xba, 0x88, 0x5d, 0x34, 0x57, 0x28, 0x85, 0xa4, 0x52,
	0x3f, 0x2b, 0x67, 0x9c, 0xcd, 0x4b, 0x22, 0x29, 0x55, 0x17, 0xdd, 0x18, 0xdb, 0x84, 0xec, 0x83,
	0x62, 0x97, 0xf8, 0xdc, 0xc0, 0x25, 0x66, 0x22, 0x1a, 0xd9, 0x0b, 0x39, 0x93, 0x80, 0x56, 0xf6,
	0x61, 0xf4, 0x65, 0xa7, 0xaa, 0x6a, 0xe5, 0x2f, 0x4c, 0x74, 0x0d, 0xe8, 0x94, 0xbd, 0xa9, 0x56,
	0x8e, 0xaf, 0xef, 0xaa, 0x81, 0xe3, 0x0a, 0x7f, 0x69, 0x40, 0x77, 0xbd, 0x84, 0x49, 0x8a, 0xa8,
	0xc0, 0x30, 0xa7, 0x8a, 0x9c, 0x46, 0x5b, 0xd8, 0x57, 0x26, 0x73, 0x2a, 0x6b, 0x35, 0xda, 0xc1,
	0x1e, 0x41, 0xb3, 0x05, 0x8d, 0xd7, 0xf7, 0x1b, 0xf2, 0x75, 0x79, 0xfd, 0xa6, 0xb3, 0x7d, 0xd7,
	0x33, 0x1b, 0x95, 0xd5, 0x82, 0xbb, 0x8a, 0xca, 0xea, 0x37, 0x46, 0x59, 0xcd, 0x0c, 0x0d, 0x95,
	0xd5, 0xd8, 0xd0, 0x8b, 0x8d, 0xf7, 0x5b, 0x53, 0x43, 0x2f, 0xb0, 0x5e, 0x39, 0xdf, 0xf2, 0x2a,
	0x20, 0xdf, 0x19, 0xcd, 0xb7, 0x8c, 0x00, 0xf0, 0x3a, 0x1a, 0x2f, 0x9a, 0x3b, 0xe4, 0x7b, 0x83,
	0x00, 0xc7, 0x72, 0x13, 0x47, 0xda, 0x45, 0xfe, 0x2e, 0x49, 0x7e, 0x30, 0x20, 0x1b, 0xc9, 0x5c,
	0x23, 0xe5, 0x85, 0x20, 0x71, 0x3b, 0x89, 0x54, 0xf4, 0xa3, 0x89, 0xf1, 0xf4, 0xef, 0x28, 0x5a,
	0x3f, 0x97, 0xd1, 0x4c, 0x71, 0x29, 0x34, 0xe7, 0x4f, 0x06, 0xd1, 0x4d, 0xe5, 0x6b, 0xa1, 0xb9,
	0xef, 0xce, 0x7c, 0x68, 0xff, 0x6c, 0xed, 0xf3, 0x4b, 0xfb, 0x12, 0xaa, 0x66, 0xfc, 0x29, 0xe9,
	0x4c, 0xbf, 0x94, 0x2b, 0x9b, 0xa4, 0x9c, 0x29, 0x69, 0x4a, 0x20, 0x94, 0x82, 0x7e, 0x24, 0xbf,
	0x1a, 0x9c, 0x77, 0x34, 0xdb, 0x89, 0xf8, 0x1e, 0x34, 0x9a, 0x2c, 0x87, 0x52, 0xf1, 0x6f, 0x26,
	0x26, 0xd1, 0xaf, 0x86, 0x52, 0xef, 0xbd, 0x08, 0xa7, 0x6f, 0x8d, 0x8a, 0xe9, 0x77, 0x13, 0xf1,
	0x26, 0x27, 0x5d, 0xef, 0x2b, 0xa3, 0xc0, 0x0f, 0x75, 0x59, 0xff, 0x30, 0xfa, 0xca, 0xc8, 0xf4,
	0x83, 0x2e, 0x2a, 0x0c, 0x62, 0x2f, 0xd8, 0x81, 0x3b, 0xbd, 0x34, 0x98, 0x4e, 0xb8, 0x43, 0xfe,
	0x34, 0x19, 0xc4, 0x11, 0x64, 0x45, 0x22, 0xce, 0x3c, 0x8c, 0x66, 0x3c, 0x96, 0xf9, 0x50, 0xee,
	0xff, 0xd6, 0x74, 0xf9, 0x74, 0x8b, 0x09, 0xf7, 0xd1, 0xf8, 0xbd, 0xbb, 0xbf, 0x9f, 0xa3, 0x1a,
	0x07, 0xd5, 0x6f, 0x3e, 0xb7, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x81, 0x2a, 0x67, 0xcc,
	0x12, 0x00, 0x00,
}
