// Code generated by protoc-gen-go.
// source: dstore/engine/procedures/om_GetPersonSurcharges_Ad.proto
// DO NOT EDIT!

/*
Package om_GetPersonSurcharges_Ad is a generated protocol buffer package.

It is generated from these files:
	dstore/engine/procedures/om_GetPersonSurcharges_Ad.proto

It has these top-level messages:
	Parameters
	Response
*/
package om_GetPersonSurcharges_Ad

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import dstore_values "gosdk.dstore.de/values"
import dstore_engine_error "gosdk.dstore.de/engine/error"
import dstore_engine_message "gosdk.dstore.de/engine/message"
import dstore_engine_metainformation "gosdk.dstore.de/engine/metainformation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameters struct {
	PersonTypeId                *dstore_values.IntegerValue `protobuf:"bytes,1,opt,name=person_type_id,json=personTypeId" json:"person_type_id,omitempty"`
	PersonTypeIdNull            bool                        `protobuf:"varint,1001,opt,name=person_type_id_null,json=personTypeIdNull" json:"person_type_id_null,omitempty"`
	PersonId                    *dstore_values.IntegerValue `protobuf:"bytes,2,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	PersonIdNull                bool                        `protobuf:"varint,1002,opt,name=person_id_null,json=personIdNull" json:"person_id_null,omitempty"`
	TreeNodeId                  *dstore_values.IntegerValue `protobuf:"bytes,3,opt,name=tree_node_id,json=treeNodeId" json:"tree_node_id,omitempty"`
	TreeNodeIdNull              bool                        `protobuf:"varint,1003,opt,name=tree_node_id_null,json=treeNodeIdNull" json:"tree_node_id_null,omitempty"`
	OutputCharacteristicId1     *dstore_values.IntegerValue `protobuf:"bytes,4,opt,name=output_characteristic_id1,json=outputCharacteristicId1" json:"output_characteristic_id1,omitempty"`
	OutputCharacteristicId1Null bool                        `protobuf:"varint,1004,opt,name=output_characteristic_id1_null,json=outputCharacteristicId1Null" json:"output_characteristic_id1_null,omitempty"`
	OutputCharacteristicId2     *dstore_values.IntegerValue `protobuf:"bytes,5,opt,name=output_characteristic_id2,json=outputCharacteristicId2" json:"output_characteristic_id2,omitempty"`
	OutputCharacteristicId2Null bool                        `protobuf:"varint,1005,opt,name=output_characteristic_id2_null,json=outputCharacteristicId2Null" json:"output_characteristic_id2_null,omitempty"`
	OutputCharacteristicId3     *dstore_values.IntegerValue `protobuf:"bytes,6,opt,name=output_characteristic_id3,json=outputCharacteristicId3" json:"output_characteristic_id3,omitempty"`
	OutputCharacteristicId3Null bool                        `protobuf:"varint,1006,opt,name=output_characteristic_id3_null,json=outputCharacteristicId3Null" json:"output_characteristic_id3_null,omitempty"`
}

func (m *Parameters) Reset()                    { *m = Parameters{} }
func (m *Parameters) String() string            { return proto.CompactTextString(m) }
func (*Parameters) ProtoMessage()               {}
func (*Parameters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameters) GetPersonTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonTypeId
	}
	return nil
}

func (m *Parameters) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Parameters) GetTreeNodeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.TreeNodeId
	}
	return nil
}

func (m *Parameters) GetOutputCharacteristicId1() *dstore_values.IntegerValue {
	if m != nil {
		return m.OutputCharacteristicId1
	}
	return nil
}

func (m *Parameters) GetOutputCharacteristicId2() *dstore_values.IntegerValue {
	if m != nil {
		return m.OutputCharacteristicId2
	}
	return nil
}

func (m *Parameters) GetOutputCharacteristicId3() *dstore_values.IntegerValue {
	if m != nil {
		return m.OutputCharacteristicId3
	}
	return nil
}

type Response struct {
	Error           *dstore_engine_error.Error                       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	MetaInformation []*dstore_engine_metainformation.MetaInformation `protobuf:"bytes,2,rep,name=meta_information,json=metaInformation" json:"meta_information,omitempty"`
	Message         []*dstore_engine_message.Message                 `protobuf:"bytes,3,rep,name=message" json:"message,omitempty"`
	Row             []*Response_Row                                  `protobuf:"bytes,4,rep,name=row" json:"row,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *dstore_engine_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetMetaInformation() []*dstore_engine_metainformation.MetaInformation {
	if m != nil {
		return m.MetaInformation
	}
	return nil
}

func (m *Response) GetMessage() []*dstore_engine_message.Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Response) GetRow() []*Response_Row {
	if m != nil {
		return m.Row
	}
	return nil
}

type Response_Row struct {
	RowId                     int32                       `protobuf:"varint,10000,opt,name=row_id,json=rowId" json:"row_id,omitempty"`
	Value1RestrictedByPattern *dstore_values.StringValue  `protobuf:"bytes,10001,opt,name=value1_restricted_by_pattern,json=value1RestrictedByPattern" json:"value1_restricted_by_pattern,omitempty"`
	Value2RestrictedByPattern *dstore_values.StringValue  `protobuf:"bytes,10002,opt,name=value2_restricted_by_pattern,json=value2RestrictedByPattern" json:"value2_restricted_by_pattern,omitempty"`
	Relative                  *dstore_values.BooleanValue `protobuf:"bytes,10003,opt,name=relative" json:"relative,omitempty"`
	Value3                    *dstore_values.StringValue  `protobuf:"bytes,10004,opt,name=value3" json:"value3,omitempty"`
	Value1                    *dstore_values.StringValue  `protobuf:"bytes,10005,opt,name=value1" json:"value1,omitempty"`
	UnitSymbol                *dstore_values.StringValue  `protobuf:"bytes,10006,opt,name=unit_symbol,json=unitSymbol" json:"unit_symbol,omitempty"`
	Value2                    *dstore_values.StringValue  `protobuf:"bytes,10007,opt,name=value2" json:"value2,omitempty"`
	SurchargeValue            *dstore_values.DecimalValue `protobuf:"bytes,10008,opt,name=surcharge_value,json=surchargeValue" json:"surcharge_value,omitempty"`
	NodeDescription           *dstore_values.StringValue  `protobuf:"bytes,10009,opt,name=node_description,json=nodeDescription" json:"node_description,omitempty"`
	Active                    *dstore_values.BooleanValue `protobuf:"bytes,10010,opt,name=active" json:"active,omitempty"`
	PersonId                  *dstore_values.IntegerValue `protobuf:"bytes,10011,opt,name=person_id,json=personId" json:"person_id,omitempty"`
	UnitId                    *dstore_values.IntegerValue `protobuf:"bytes,10012,opt,name=unit_id,json=unitId" json:"unit_id,omitempty"`
	Brutto                    *dstore_values.BooleanValue `protobuf:"bytes,10013,opt,name=brutto" json:"brutto,omitempty"`
	TreeNodeId                *dstore_values.IntegerValue `protobuf:"bytes,10014,opt,name=tree_node_id,json=treeNodeId" json:"tree_node_id,omitempty"`
	NodeId                    *dstore_values.IntegerValue `protobuf:"bytes,10015,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	SurchargeTypeDescription  *dstore_values.StringValue  `protobuf:"bytes,10016,opt,name=surcharge_type_description,json=surchargeTypeDescription" json:"surcharge_type_description,omitempty"`
	SurchargeTypeId           *dstore_values.IntegerValue `protobuf:"bytes,10017,opt,name=surcharge_type_id,json=surchargeTypeId" json:"surcharge_type_id,omitempty"`
	Value3RestrictedByPattern *dstore_values.StringValue  `protobuf:"bytes,10018,opt,name=value3_restricted_by_pattern,json=value3RestrictedByPattern" json:"value3_restricted_by_pattern,omitempty"`
	LevelId                   *dstore_values.IntegerValue `protobuf:"bytes,10019,opt,name=level_id,json=levelId" json:"level_id,omitempty"`
}

func (m *Response_Row) Reset()                    { *m = Response_Row{} }
func (m *Response_Row) String() string            { return proto.CompactTextString(m) }
func (*Response_Row) ProtoMessage()               {}
func (*Response_Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *Response_Row) GetValue1RestrictedByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.Value1RestrictedByPattern
	}
	return nil
}

func (m *Response_Row) GetValue2RestrictedByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.Value2RestrictedByPattern
	}
	return nil
}

func (m *Response_Row) GetRelative() *dstore_values.BooleanValue {
	if m != nil {
		return m.Relative
	}
	return nil
}

func (m *Response_Row) GetValue3() *dstore_values.StringValue {
	if m != nil {
		return m.Value3
	}
	return nil
}

func (m *Response_Row) GetValue1() *dstore_values.StringValue {
	if m != nil {
		return m.Value1
	}
	return nil
}

func (m *Response_Row) GetUnitSymbol() *dstore_values.StringValue {
	if m != nil {
		return m.UnitSymbol
	}
	return nil
}

func (m *Response_Row) GetValue2() *dstore_values.StringValue {
	if m != nil {
		return m.Value2
	}
	return nil
}

func (m *Response_Row) GetSurchargeValue() *dstore_values.DecimalValue {
	if m != nil {
		return m.SurchargeValue
	}
	return nil
}

func (m *Response_Row) GetNodeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.NodeDescription
	}
	return nil
}

func (m *Response_Row) GetActive() *dstore_values.BooleanValue {
	if m != nil {
		return m.Active
	}
	return nil
}

func (m *Response_Row) GetPersonId() *dstore_values.IntegerValue {
	if m != nil {
		return m.PersonId
	}
	return nil
}

func (m *Response_Row) GetUnitId() *dstore_values.IntegerValue {
	if m != nil {
		return m.UnitId
	}
	return nil
}

func (m *Response_Row) GetBrutto() *dstore_values.BooleanValue {
	if m != nil {
		return m.Brutto
	}
	return nil
}

func (m *Response_Row) GetTreeNodeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.TreeNodeId
	}
	return nil
}

func (m *Response_Row) GetNodeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *Response_Row) GetSurchargeTypeDescription() *dstore_values.StringValue {
	if m != nil {
		return m.SurchargeTypeDescription
	}
	return nil
}

func (m *Response_Row) GetSurchargeTypeId() *dstore_values.IntegerValue {
	if m != nil {
		return m.SurchargeTypeId
	}
	return nil
}

func (m *Response_Row) GetValue3RestrictedByPattern() *dstore_values.StringValue {
	if m != nil {
		return m.Value3RestrictedByPattern
	}
	return nil
}

func (m *Response_Row) GetLevelId() *dstore_values.IntegerValue {
	if m != nil {
		return m.LevelId
	}
	return nil
}

func init() {
	proto.RegisterType((*Parameters)(nil), "dstore.engine.om_GetPersonSurcharges_Ad.Parameters")
	proto.RegisterType((*Response)(nil), "dstore.engine.om_GetPersonSurcharges_Ad.Response")
	proto.RegisterType((*Response_Row)(nil), "dstore.engine.om_GetPersonSurcharges_Ad.Response.Row")
}

func init() {
	proto.RegisterFile("dstore/engine/procedures/om_GetPersonSurcharges_Ad.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x4e, 0xeb, 0x46,
	0x14, 0x15, 0x4d, 0x73, 0xe9, 0x10, 0x11, 0x18, 0xa4, 0xd6, 0x24, 0x15, 0xaa, 0xa8, 0xaa, 0x56,
	0x7d, 0x30, 0x8d, 0x5d, 0x54, 0xaa, 0x5e, 0x24, 0x28, 0x94, 0xe6, 0x81, 0x08, 0x99, 0xaa, 0x15,
	0xa8, 0x92, 0xe5, 0xc4, 0xd3, 0xd4, 0xaa, 0xe3, 0x89, 0xc6, 0x63, 0x50, 0xfe, 0x82, 0xde, 0xaf,
	0xe7, 0xfe, 0x72, 0x5e, 0xce, 0x87, 0x9d, 0xeb, 0x37, 0x9c, 0x3d, 0x33, 0x76, 0x12, 0xe7, 0x24,
	0xb1, 0xe1, 0x05, 0x34, 0x99, 0xb5, 0xf6, 0x5a, 0xd9, 0x7b, 0xd6, 0x4c, 0xd0, 0xae, 0x1b, 0x72,
	0xca, 0xc8, 0x36, 0x09, 0x7a, 0x5e, 0x40, 0xb6, 0x07, 0x8c, 0x76, 0x89, 0x1b, 0x31, 0x12, 0x6e,
	0xd3, 0xbe, 0x7d, 0x44, 0xf8, 0x09, 0x61, 0x21, 0x0d, 0x4e, 0x23, 0xd6, 0xfd, 0xc9, 0x61, 0x3d,
	0x12, 0xda, 0x7b, 0xae, 0x0e, 0x20, 0x4e, 0xf1, 0xfb, 0x8a, 0xa9, 0x2b, 0xa6, 0x3e, 0x17, 0x5e,
	0x5f, 0x8f, 0x25, 0x2e, 0x1c, 0x3f, 0x22, 0xa1, 0x62, 0xd7, 0x37, 0xd2, 0xba, 0x84, 0x31, 0xca,
	0xe2, 0xad, 0x46, 0x7a, 0xab, 0x4f, 0xc2, 0xd0, 0xe9, 0x91, 0x78, 0xf3, 0xdd, 0xe9, 0x4d, 0xee,
	0x78, 0xc1, 0x8f, 0x94, 0xf5, 0x1d, 0xee, 0xd1, 0x40, 0x81, 0xb6, 0x1e, 0x96, 0x10, 0x3a, 0x71,
	0x98, 0x03, 0xbb, 0xe0, 0x07, 0xef, 0xa1, 0x95, 0x81, 0xf4, 0x65, 0xf3, 0xe1, 0x80, 0xd8, 0x9e,
	0xab, 0x2d, 0xbd, 0xb3, 0xf4, 0xc1, 0xb2, 0xd1, 0xd0, 0xe3, 0xaf, 0x10, 0x3b, 0xf3, 0x02, 0x4e,
	0x7a, 0x84, 0x7d, 0x27, 0x56, 0x56, 0x55, 0x51, 0xbe, 0x05, 0x46, 0xcb, 0xc5, 0x3a, 0x5a, 0x4f,
	0x97, 0xb0, 0x83, 0xc8, 0xf7, 0xb5, 0xc7, 0x65, 0x28, 0x54, 0xb1, 0x56, 0x27, 0xb1, 0x6d, 0xd8,
	0xc0, 0xbb, 0xe8, 0x8d, 0x18, 0x0f, 0x6a, 0xaf, 0x65, 0xab, 0x55, 0x14, 0x1a, 0x94, 0xde, 0x1b,
	0x99, 0x4d, 0x44, 0x9e, 0x28, 0x91, 0x6a, 0x02, 0x91, 0x02, 0x5f, 0xa0, 0x2a, 0x67, 0x84, 0xd8,
	0x01, 0x75, 0xe5, 0x37, 0x2a, 0x64, 0x6b, 0x20, 0x41, 0x68, 0x03, 0x1e, 0x54, 0x3e, 0x44, 0x6b,
	0x93, 0x74, 0x25, 0xf4, 0x54, 0x09, 0xad, 0x8c, 0x71, 0x52, 0xea, 0x7b, 0xb4, 0x41, 0x23, 0x3e,
	0x88, 0xb8, 0x2d, 0x86, 0xea, 0x74, 0xa1, 0xa7, 0x5e, 0xc8, 0xbd, 0x2e, 0xf0, 0x9a, 0xda, 0xeb,
	0xd9, 0xba, 0x6f, 0x29, 0xf6, 0x57, 0x29, 0x72, 0xcb, 0x6d, 0xe2, 0x03, 0xb4, 0x39, 0xb7, 0xb0,
	0x72, 0xf4, 0x4c, 0x39, 0x6a, 0xcc, 0xa9, 0x90, 0x65, 0xcf, 0xd0, 0x8a, 0x37, 0xb6, 0x67, 0x2c,
	0xb2, 0x67, 0x28, 0x7b, 0xcf, 0x17, 0xda, 0x33, 0xb2, 0xec, 0x99, 0x5a, 0xe9, 0xc6, 0xf6, 0xcc,
	0x45, 0xf6, 0x4c, 0x65, 0xef, 0xc5, 0x42, 0x7b, 0xa6, 0xb0, 0xb7, 0xf5, 0xa8, 0x8a, 0x2a, 0x16,
	0x09, 0x07, 0x34, 0x08, 0x09, 0xfe, 0x08, 0x15, 0x65, 0x10, 0xe3, 0x7c, 0xd4, 0xf5, 0x74, 0xc4,
	0x55, 0x48, 0x0f, 0xc5, 0x5f, 0x4b, 0x01, 0xf1, 0x19, 0x5a, 0x15, 0x11, 0xb4, 0x27, 0x32, 0x08,
	0xc7, 0xbd, 0x00, 0x64, 0x7d, 0x8a, 0x3c, 0x9d, 0xd4, 0x63, 0x58, 0xb7, 0xc6, 0x6b, 0xab, 0xd6,
	0x4f, 0x7f, 0x00, 0x11, 0x2a, 0xc7, 0xd1, 0x87, 0xc3, 0x2d, 0x2a, 0x6e, 0xbe, 0x52, 0x51, 0x5d,
	0x0c, 0xc7, 0xea, 0xbf, 0x95, 0xc0, 0xf1, 0x11, 0x2a, 0x30, 0x7a, 0x09, 0x47, 0x53, 0xb0, 0x76,
	0xf4, 0x9c, 0xf7, 0x94, 0x9e, 0xb4, 0x41, 0xb7, 0xe8, 0xa5, 0x25, 0x2a, 0xd4, 0xaf, 0x10, 0x2a,
	0xc0, 0x02, 0xbf, 0x89, 0x4a, 0xb0, 0x14, 0x31, 0xbb, 0x6a, 0x43, 0x67, 0x8a, 0x56, 0x11, 0x96,
	0x90, 0xa2, 0x1f, 0xd0, 0xdb, 0x72, 0x64, 0x4d, 0x1b, 0x2e, 0x4c, 0xce, 0x3c, 0xe8, 0xae, 0x6b,
	0x77, 0x86, 0xf6, 0xc0, 0xe1, 0xd0, 0xe7, 0x40, 0xfb, 0xa5, 0x9d, 0xee, 0x63, 0x3c, 0x5f, 0x01,
	0x0d, 0x7a, 0x6a, 0xbc, 0x1b, 0xaa, 0x80, 0x35, 0xe2, 0xef, 0x0f, 0x4f, 0x14, 0x7b, 0x54, 0xdd,
	0x98, 0x53, 0xfd, 0xd7, 0xbc, 0xd5, 0x8d, 0x59, 0xd5, 0x77, 0x51, 0x85, 0x11, 0x1f, 0x5a, 0x7d,
	0x41, 0xb4, 0xdf, 0xda, 0x33, 0xcf, 0x61, 0x87, 0x52, 0x9f, 0x38, 0x41, 0x7c, 0x43, 0x25, 0x68,
	0x6c, 0xa2, 0x92, 0x04, 0x98, 0xda, 0xef, 0xd9, 0x0e, 0x62, 0xe8, 0x88, 0xd4, 0xd4, 0xfe, 0xc8,
	0x4b, 0x6a, 0xe2, 0xcf, 0xd1, 0x72, 0x14, 0x78, 0xdc, 0x0e, 0x87, 0xfd, 0x0e, 0xf5, 0xb5, 0x3f,
	0xb3, 0x99, 0x48, 0xe0, 0x4f, 0x25, 0x7c, 0x24, 0x69, 0x68, 0x7f, 0xe5, 0x95, 0x34, 0xf0, 0x21,
	0xaa, 0x85, 0xc9, 0xa9, 0xb0, 0xe5, 0x67, 0xda, 0xdf, 0xb3, 0xbb, 0xe3, 0x92, 0xae, 0xd7, 0x77,
	0x7c, 0x45, 0x5f, 0x19, 0x91, 0xe4, 0x1a, 0x7f, 0x8d, 0x56, 0xe5, 0xd5, 0xea, 0x92, 0xb0, 0xcb,
	0xbc, 0x81, 0xcc, 0xc5, 0x3f, 0xd9, 0x2e, 0x6a, 0x82, 0x74, 0x30, 0xe6, 0xe0, 0x8f, 0x51, 0x09,
	0x32, 0x2b, 0x66, 0xf4, 0x6f, 0x8e, 0x19, 0xc5, 0x58, 0xfc, 0xe9, 0xe4, 0xeb, 0xf3, 0x5f, 0xfb,
	0x3a, 0xcf, 0xcf, 0x0e, 0x2a, 0xcb, 0x96, 0x03, 0xf1, 0xff, 0x1c, 0xc4, 0x92, 0x00, 0x03, 0x0d,
	0x7c, 0x76, 0x58, 0xc4, 0x39, 0xd5, 0x6e, 0xe5, 0xf1, 0xa9, 0xb0, 0xf8, 0xcb, 0xa9, 0x47, 0xec,
	0x76, 0xfb, 0x7a, 0xaf, 0x18, 0x98, 0x4d, 0xa8, 0x77, 0xf2, 0x98, 0x0d, 0x14, 0xed, 0x0c, 0xd5,
	0xc7, 0x33, 0x96, 0xef, 0xf9, 0xe4, 0x98, 0xee, 0x66, 0x8f, 0x49, 0x1b, 0xd1, 0xc5, 0x93, 0x3f,
	0x39, 0xaf, 0x6f, 0xd0, 0xda, 0x54, 0x69, 0xf0, 0x76, 0x2f, 0x87, 0xb7, 0x5a, 0xaa, 0xe4, 0xc4,
	0xdd, 0x62, 0xce, 0x49, 0xff, 0xfd, 0xbc, 0xe9, 0x37, 0x67, 0xa5, 0xff, 0x13, 0x54, 0xf1, 0xc9,
	0x05, 0xf1, 0x85, 0xbd, 0x07, 0x39, 0xec, 0x95, 0x25, 0xba, 0xe5, 0xee, 0x9f, 0xa3, 0x86, 0x47,
	0xa7, 0xae, 0xd4, 0xf1, 0x8f, 0xc6, 0xf3, 0xcf, 0x7a, 0x34, 0x74, 0x7f, 0x4e, 0xf6, 0xdd, 0x6b,
	0xfd, 0xae, 0xec, 0x94, 0xe4, 0xaf, 0x37, 0xf3, 0x65, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x94,
	0xd9, 0xc4, 0x94, 0x0a, 0x00, 0x00,
}
